### ISSUE TITLE
Brews are reset every time I update the config.yml

### ISSUE THREAD

**Issue by devonmartino** [DieReicheErethons/Brewery#100]
Every time our config.yml file is updated, every existing brew loses its potency- it no longer retains its effects, is no longer alcoholic, etc. This only happens when we update the config.yml. To clarify, we add new brews to the bottom of the list, not the top, so the 11th brew before the update is still the 11th brew after the update.

**Comment by Sn0wStorm** [comment]
Check for errors in the console. If this still happens, please reopen
