### ISSUE TITLE
Plugin ignores config

### ISSUE THREAD

**Issue by Crankeedoo** [DieReicheErethons/Brewery#101]
When I tested out this plugin, not only could I not put ingredients in the cauldron (and I did make it correctly), but also I couldn't get any drinks using /br create (it can't find a drink named whatever I asked it to give me). Everything else (commands, barrels, etc) works, so I've come to assume it's some sort of issue with the config, where the plugin does not recognize any of the cooked tags or the recipes. I've attached my config file.
[config.txt](https://github.com/DieReicheErethons/Brewery/files/63442/config.txt)

**Comment by Sn0wStorm** [comment]
Check for errors in the Console. If this still happens please repoen
