### ISSUE TITLE
Distillation not working

### ISSUE THREAD

**Issue by slkjoy** [DieReicheErethons/Brewery#103]
Everything is working- fermentation, barrel aging, except distilling. The Glowstone powder gets consumed and the brew turns into vanilla Potion of Swiftness (from Sugar Brew). This happens even when Op. We use PermissionsEX with brewery.user permission set for Member group. This is on an ASkyBlock server.

Anyone else have this problem?

**Comment by Sn0wStorm** [comment]
There is probably a compatibility issue with another plugin. check for errors in the Console. If this still happens please repoen
