### ISSUE TITLE
Lack of Effect Information

### ISSUE THREAD

**Issue by salty6924** [DieReicheErethons/Brewery#106]
The wiki does not contain information on effect types, format, and values. 

Please add this information so i can customize the effects of our recipes. 

Also, you the man i love this plugin.

**Comment by Sn0wStorm** [comment]
The links in the config should be updated to use the Spigot documentation

**Comment by Sn0wStorm** [comment]
Updated the config with link to spigot javadoc. All informations can be found in the config.
