### ISSUE TITLE
"Error opening Barrel, please report to an admin...

### ISSUE THREAD

**Issue by Subby72** [DieReicheErethons/Brewery#107]
I am the  main admin for a server and am trying to set this plugin up on my server...however, i keep getting this error. i have enabled all permissions for this plugin for me. Please tell me how to fix this error. I don't use WorldGuard. I'm only running Essentials and GriefPrevention for protecting things. However, I don't see a place anywhere in these two configs, or in Brewery config to lead me to a 'fix'. Please help... Thank you!

**Comment by Feuerstern** [comment]
Maybe, it's because of GP. Support for it is very outdated (v7.8)

**Comment by Subby72** [comment]
is there any permission i can add in manually to a config somewhere? Anything to bypass the GP?

**Comment by Neotras** [comment]
i have that too

**Comment by Neotras** [comment]
wie kann man das den beheben

**Comment by Feuerstern** [comment]
Ich glaube nicht, dass man das kann...

**Comment by Sn0wStorm** [comment]
You can turn off the Plugin support in the config of Brewery and then do /brew reload

Also the Plugin support has been updated
