### ISSUE TITLE
weiterführung

### ISSUE THREAD

**Issue by Neotras** [DieReicheErethons/Brewery#108]
Hallo ich hab mal ne frage wird denn das plugin weiter entwickelt oder ist das eingestellt?

**Comment by Feuerstern** [comment]
Der ursprüngliche Autor ist und bleibt mit größerer Sicherheit auch inaktiv, aber ich werde es mindestens funktionstüchtig halten :)

**Comment by Sataniel98** [comment]
Diskussion / Antwort hierzu:

https://github.com/DieReicheErethons/Brewery/pull/116
