### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by BeyonderCraft** [DieReicheErethons/Brewery#109]
I added a new recipe and made sure everything was correct in config which it was but every time I make it it turns into that stupid infernebidle thing please reply on how to fix

**Comment by BeyonderCraft** [comment]
Indifinable brew was what I meant

**Comment by xXTrixieXx** [comment]
Did you make sure that all the ingredients listed for the recipe were also in the "cooked" section below the recipes? Each item must have a base:) Ex: Wheat is Fermented Wheat and so on:) And also make double sure that the item name is correct or even try using the item ID.
