### ISSUE TITLE
1.9 Braustand

### ISSUE THREAD

**Issue by LeonDelacroixe** [DieReicheErethons/Brewery#114]
Ich habe ein kleines Problem mit dem Plugin.

Der Braustand funktioniert leider nicht mit der version 1.3.2  , ich habe den Glowstone als Filter benutzt .Jedoch werden die Getränke nicht destilliert.

Gibt es dazu schon eine Lösung?

**Comment by Sataniel98** [comment]
In welcher Bukkit-Version denn?

**Comment by LeonDelacroixe** [comment]
In der version 1.9.

Habe vorhin auf die Brewery version 1.4 Shnapshot 2 geupdatet , leider funktioniert es trotzdem nicht.

**Comment by Sataniel98** [comment]
Dann schau ich es mir in den nächsten Tagen mal an.

**Comment by LeonDelacroixe** [comment]
Ok Vielen Dank , 

ich hatte auch den Ordner gelöscht und nochmal neu erstellen lassen , auch hier hat der Braustand nichts destilliert

**Comment by LeonDelacroixe** [comment]
Ich wollte mal nachfragen ob schon etwas erkennbar ist , denn wir können mom 80% unseres Alkohols / Getränke nicht nutzen

**Comment by Sataniel98** [comment]
Ich kümmer mich schon noch drum, aber ich bin gerade mitten in den Abiturprüfungen und nebenbei ist Brewery eigentlich nicht mein Plugin ^^ Es kann noch ein bisschen dauern.

**Comment by LeonDelacroixe** [comment]
Oh ok dann wünsche ich dir viel Glück bei den Prüfungen.

Dachte ich frage einfach nur mal nach
