### ISSUE TITLE
Distilling and Item Names/Numbers

### ISSUE THREAD

**Issue by NghtShad** [DieReicheErethons/Brewery#115]
I have been testing an issue with distilling in Brewery 1.4 in which the brewing stand does not show any status or animation when a new brew is added, glowstone is on top and blaze powder is in the fuel spot. Is there any update regarding this since 1.9 added the fuel cell to brewing stands?

I am also having issues with some ingredients not working after the update in SPIGOT to work with MC 1.9 and was not fixed by updating Brewery to 1.4. The following items no are no longer accepted into the cauldron when they were working in 1.8 SPIGOT. 

Allium (38,2)
Brown Mushroom (BROWN_MUSHROOM)
Cactus (CACTUS)
Dandelion (37 or YELLOW_FLOWER) <- neither worked
Leaves (LEAVES)
Poppy (38,0)
Pumpkin (86 or PUMPKIN) <- neither worked
Red Mushroom (RED_MUSHROOM)
Red Tulip (38,4)
Rose Bush (175,4)
Sand (SAND)
White Tulip (38,6)

In some cases I used the SPIGOT Materials name and in others the MC Item # but none are working.

**Comment by ProgrammerDan** [comment]
Considering the first bit -- check PR #116 which resolves this issue.

For the ingredients, I'll have to do some testing and get back to you.

**Comment by NghtShad** [comment]
So what I am getting out of PR #116 is that [this Beta](https://github.com/DevotedMC/Brewery/releases/tag/v1.4.0-beta) should be the answer to the Distilling issue.

**Comment by ProgrammerDan** [comment]
Correct; again, testing hasn't been extensive but I've got some pretty aggressive Brewery users on my server who are trying their damndest to find bugs. So far, nothing - fingers crossed.

> look forward to hearing the answer

Agreed! I will let you know.

**Comment by NghtShad** [comment]
Any information on the above listed items not being allowed to be placed in a cauldron?

Not sure if this makes a difference but even under the 1.8 plugin I got the below item errors on server startup.

[08:48:50 INFO]: [Brewery] Enabling Brewery v1.4.0
[08:48:50 INFO]: [Brewery] Experimental support for Bukkit 1.9 enabled.
[08:48:50 INFO]: [Brewery] Please note that the changes of 1.9 make a build of Brewery with the same quality as for older versions impossible.
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 175,4
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 351,3
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 175,1
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 175,5
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 38,8
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 38,4
[08:48:50 INFO]: [Brewery] ERROR: Unknown Material: 38,6
[08:48:50 INFO]: [Brewery] Brewery enabled!

These items all seemed to work in the past so I just ignored the errors but now a few of those errors match up with some of the items that will not be accepted by a cauldron.

**Comment by ProgrammerDan** [comment]
I'm so sorry, I've gotten caught up in some new development and forgot to check on these. I'll try to give them some attention soon if no-one else beats me to it!

**Comment by NghtShad** [comment]
Any further update?

**Comment by Sataniel98** [comment]
@Sn0wStorm

**Comment by Sn0wStorm** [comment]
To use the normal item names you have to have Vault installed, preferably the newest version.

Items supported by spigot itself are listed here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by NghtShad** [comment]
Does that also apply to item numbers? For example Allium (38,2)

**Comment by Sn0wStorm** [comment]
I dont know if item numbers work at all anymore in 1.9

They were definitely deprecated for years now and are probably not supported any more. Vault would recognize "Allium", see here for the Full list: https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/item/Items.java

**Comment by Sn0wStorm** [comment]
I tried multiple combinations of adding ingredients to the config. Material, Vault and item id all worked fine using Spigot 1.9.2
See the example recipe in the default config:
https://github.com/DieReicheErethons/Brewery/blob/master/resources/config/en/config.yml#L91

**Comment by Sn0wStorm** [comment]
Maybe it was the same issue as this? #130
