### ISSUE TITLE
1.9 Update

### ISSUE THREAD

**Issue by Sn0wStorm** [DieReicheErethons/Brewery#117]
Things still needed for the 1.9 Update:

Potions all have the same blueish color, the Potion color does not seem to work (Spigot 1.9.2).  
Also setMainEffect is deprecated and PotionType should be used, maybe there is the Problem?

There are more ways to change the water level in the cauldron (banners, dyed armor, rain) but we probably can not take care of all of them.

**Comment by jordanwilliams1** [comment]
Is the plugin going to get updated? Last updated on Jan 10, 2015 on bukkit

**Comment by Sataniel98** [comment]
Yes, most of it is updated.

**Comment by Sn0wStorm** [comment]
Potions created by brewery currently get the UNCRAFTABLE potion type. This results in the same color for every potion.

**Comment by Sn0wStorm** [comment]
The Potion color seems to be determined by the "potion type", or if the potion type is UNCRAFTABLE by one of the Custom Potion effects.

Setting the potion type to get the correct color works. The effect of the potion type is displayed in the Lore though which is extremely misleading.  
For example setting a potion type of poison to make the potion green also displays "Poison (0:45)" in the lore.

I have no solution for this currently.

**Comment by Sn0wStorm** [comment]
Workaround by hiding all Potion Effects in Brewery Potions with an Item Flag.

Some testing still needs to be done before release.

**Comment by CKGAR** [comment]
Update on release?

**Comment by Sn0wStorm** [comment]
Plugin updated to 1.9
