### ISSUE TITLE
Bekomme nur Wasserflaschen

### ISSUE THREAD

**Issue by Tunk99** [DieReicheErethons/Brewery#121]
Hallo, ich habe das neue Update eingespielt und meine alte config.yml weiterverwendet. Es läuft eigentlich auch alles gut da die console keine Fehlermeldung zu Brewery ausgibt, nur das alles funktioniert: 

[10:40:44 INFO]: [Brewery] Enabling Brewery v1.4.2
[10:40:44 INFO]: [Brewery] Brewery enabled!

Wenn ich jedoch im Spiel etwas im Braukessel zusammenmixe (natürlich nach Rezept) dann bekomme ich, am Ende nur Wasserflaschen heraus und nicht das entsprechende Getränk/Sud (je nachdem). Im Anhang ist eine .zip mit meiner config, könnt ihr mir vielleicht sagen woran es liegen könnte?

Viele Grüße!

PS: Sehr tolles Plugin übrigens =)
[config.zip](https://github.com/DieReicheErethons/Brewery/files/276228/config.zip)

**Comment by Sn0wStorm** [comment]
Also wenn du nur Wasserflaschen bekommst dann hört sich das sehr danach an als ob ein anderes Plugin dazwischen funkt... Von Brewery solltest du immer irgendwas anderes bekommen und sei es nur irgendwas undefinierbares.  
Sonst schau ob du die nötigen Permissions hast (brewery.cauldron.fill)

**Comment by Tunk99** [comment]
Ich hatte jetzt getippt das es an MoreItems liegen könnte aber weit gefehlt. Das mit den Permissions habe ich auch versucht und es hat nicht geklappt - bekomme immer noch nur Wasserflaschen.

Hast du eine Idee an welchen Plugin es möglicherweise liegen könnte, hier mal eine Liste meiner installierten Plugins: GoldIsMoney, WorldEdit, VoxelSniper, ArmorWeight, CommandBook, PorteCoulissante, Vault, PermissionsEx, Multiverse-Core, LogBlock, HolographicDisplays, HeroChat, LWC, WorldGuard, dynmap, Citizens, Dynmap-WorldGuard, WorldBorder, TreasureChest, ChestShop, Brewery, BetonQuest.

Aus der Minecraft 1.8 ist mir bekannt das soweit eigentlich alle Plugins zusammen gut funktioniert haben - abgesehen von BetonQuest da ich dies nicht nutzte.

Viele Grüße!

**Comment by Sn0wStorm** [comment]
Kann ich dir nicht sagen, keines sieht aus als würde es etwas mit den Kesseln zu tun haben. Da es vorher ohne BetonQuest funktioniert hat würde ich das mal entfernen und schauen ob es geht. Die config sieht soweit auch gut aus. Probiere sonst mal die mitgelieferte config

**Comment by Sn0wStorm** [comment]
Lösung gefunden?

**Comment by Tunk99** [comment]
Entschuldige bitte, hatte in den letzten Tagen wenig Zeit. Also: Ich habe jetzt nochmal Brewery neu installiert und die Standart Config genutzt - nichts. Wieder nur Wasserflaschen, das Problem bestand auch noch als ich dann einmal BetonQuest deinstalliert habe. Ich bin mittlerweile leider sehr ratlos. Ich probiere jetzt noch ein bisschen weiter, vielleicht hast du noch Ideen..?

Viele Grüße!

**Comment by Sn0wStorm** [comment]
Also das Problem hatte ich noch nie, stell noch mal sicher dass Feuer unter dem Kessel an ist, sonst kannst du mal versuchen in die Brewery config
debug: true
einfach als neue Zeile einfügen, vielleicht zeigt es dann etwas an wenn du einen Trank rausholen willst.

Sonst mal mit komplett standard Server versuchen, ich hab CraftBukkit, Spigot und Paper getestet und überall funktioniert es.
