### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Sataniel98** [DieReicheErethons/Brewery#123]
Using a clean environment with nothing but Brewery, the DrinkListener fails to recognize the brew [here](https://github.com/DieReicheErethons/Brewery/blob/master/src/com/dre/brewery/listeners/DrinkListener1_9.java#L22).

Steps to reproduce:
1. Setup a server with nothing but Brewery
2. Do "/brew create Fine Beer" and drink the item
3. The player gets fire resistance.

Error:
`[Brewery] ERROR: Database failure! unable to find UID -2 of a custom Potion!`

**Comment by Sn0wStorm** [comment]
Uh thats bad..
Probably because the ConsumeEvent in the DrinkListener1_9 and in PlayerListener are both on MONITOR. So its unclear which one is being called first.
The PlayerListener removes the brew so when DrinkListener1_9 is called after that for it cant find it.

**Comment by Sataniel98** [comment]
Seems legit.

**Comment by Sn0wStorm** [comment]
Fixed here: 20c68454f40614a712f20deab21ba1c465f36045

Dont set the base potion to Mundane, just replace the potion when drinking.
Tested and works on 1.9.2

**Comment by Sn0wStorm** [comment]
Do you remember if this was an issue in previous versions for 1.9?

**Comment by Sataniel98** [comment]
I didn't notice it at all. The issue has been posted at SpigotMC and I had my IDE opened, so I tested and debugged a bit. Aber warum zur Hölle schreiben wir überhaupt auf Englisch O_o

**Comment by Sn0wStorm** [comment]
Keine Ahnung, vielleicht will ja jemand mitlesen :D 
Ja danke, so konnte ich das schnell fixen.
Würde dann jetzt die 1.4.4 releasen, vielleicht kannst du es noch eben schnell bei dir testen wenn du Zeit hast?

**Comment by Sataniel98** [comment]
Erledigt. Es funktioniert prima :)
