### ISSUE TITLE
Question: Cauldron

### ISSUE THREAD

**Issue by ES-Vodoo** [DieReicheErethons/Brewery#124]
Why all items aren't allowed in cauldron?

**Comment by Sn0wStorm** [comment]
That would be confusing when trying out other ingredients. It would be too hard in my opinion.

You can add items to the cooked list in the config if you want then allowed in the cauldron

**Comment by ES-Vodoo** [comment]
I'm retarded... I forgot about this list in config :smile: 
Thank you for reply!
