### ISSUE TITLE
Big barrel bug

### ISSUE THREAD

**Issue by Defnder** [DieReicheErethons/Brewery#126]
We have noticed a little problem with the lore/item information. We made some recipes/drinks that should be aged in specific barrels. But in the lore the barrel color is always red, no matter which kind of barrel is used. Even in the right barrel.

**Comment by Sn0wStorm** [comment]
The Lore should have a line for woodtype, is that red?

**Comment by Defnder** [comment]
Yes, exactly, the line for the woodtype is always red.

**Comment by Defnder** [comment]
Update:
It seems, that the big barrels are "buggy". Everything works when using the small barrels.
But in the big barrels the lore shows wrong informations, e.g. wrong woodtype (red although its in the right barrel), wrong ingredients (yellow although they are right)...
