### ISSUE TITLE
absent absinthe

### ISSUE THREAD

**Issue by Gale67** [DieReicheErethons/Brewery#128]
Whenever I try to brew anything use grass (absinthe in particular) the cauldron will not take the grass. Is this a bug or was the recipe removed?

**Comment by CKGAR** [comment]
I am having this same issues.

**Comment by Sn0wStorm** [comment]
The recipe has not changed, somehow grass must fail to recognize for you.
What Server software are you using? Do /ver

**Comment by CKGAR** [comment]
![image](https://cloud.githubusercontent.com/assets/8227387/16138320/78af2a3c-340a-11e6-8ade-71e2764b6022.png)

**Comment by CKGAR** [comment]
Clean install, still isn't working. The grass isn't even recognized as an ingredient.

**Comment by Sn0wStorm** [comment]
It tried to add the off hand to the cauldron, it is fixed in the newest commit. See here #130
