### ISSUE TITLE
Items cannot be put inside a cauldron 1.9

### ISSUE THREAD

**Issue by Blackyvk** [DieReicheErethons/Brewery#130]
Items like

LONG_GRASS
CACTUS
RED_MUSHROOM
CHORUS_FLOWER

and every item that needs a block like grass, cannot be put sinde a cauldron if there isnt a block nearby of it

Example:

If you want to put long_grass inside, there must be a grass block next to the cauldron, same for mushrooms, you need mycelium.

Cactus wont work because  you need space to place a cactus...

**Comment by Sn0wStorm** [comment]
Thanks! This helped a lot. I think the Problem could be because of the off hand in 1.9, i will look further into it.

**Comment by Sn0wStorm** [comment]
It got confused with the off hand and tried to add that to the Cauldron instead. It works now on my Test environment, you can test it with the version in the attachment.
[brewery-1.4.4.zip](https://github.com/DieReicheErethons/Brewery/files/321204/brewery-1.4.4.zip)

**Comment by Blackyvk** [comment]
yep it works now, thank you! :)
