### ISSUE TITLE
Glowstone consumed

### ISSUE THREAD

**Issue by InfernoBee** [DieReicheErethons/Brewery#131]
My brews like fermented wheat turns into thick potion and consumes the glowstone dust when used on the brewing stand. 

Version: 1.10

**Comment by Sn0wStorm** [comment]
Are you using the latest version of Brewery? v1.4.4

**Comment by InfernoBee** [comment]
Yes I am using the latest version of Brewery. I'm not sure what went wrong

List of my plugins:
Advanced Portals
Backpacks
BetterBanner
BossBarAPI
Brewery
ChangeSkin
Citizens 2
Citizens 2 API
Classes
ColoredTags
CraftBook
Essentials
Essentials GroupManager
FastCraft Plus
HealthBar
ImageMaps
ItemRenamer
KillerMoney
LaggRemover
LibsDisguises
Lorinths RPG Mobs
Magic
Magic Worlds
McMMO
Morph_Libs
Multiverse-Core
Multiverse-Portals
NBTEditor
OldCombatMechanics
OpenInv
PerWorldInventory
PluginManager
ProtocolLib
Realistic Swimming
RPGitems
Scavenger
Second Chance
Shop
SkinsBukkit Module
SkinsRestore
Tim
UltimateHidePlugin
VanishNoPacket
Vault
WorldEdit
WorldGuard
WurmBarbeque

**Comment by Sn0wStorm** [comment]
May be fixed in this commit a31247efca119e75e3abb1b859a566d39a5b220c
