### ISSUE TITLE
Cannot create a barrel

### ISSUE THREAD

**Issue by NicoCcino** [DieReicheErethons/Brewery#134]
Hi,

I have a strange issue with brewery 1.4.5.
In fact, this has been happening since you solved the issue with grass (which could not be distilled)
I am playing on Minecraft 1.9.2, Spigot, and Java 8.

I cannot create a barrel anymore. More precisely, there is no message telling me I created the barrel when I place the sign, after having built the barrel in itself.

I'm doing it exactly as it is explained here : https://github.com/DieReicheErethons/Brewery/wiki/Usage and I have the permission node brewery.user
It was perfectly working on brewery 1.4.4, but then I could not put grass in cauldrons (and same for other ingredients).

Thank you very much in advance.

**Comment by NicoCcino** [comment]
Ok, so I put Brewery back to English and now it works. It wasn't working in French, I don't know why.

**Comment by Sn0wStorm** [comment]
Ok thanks for clearing that up

The Sign to create the Barrel is different in every language :)
