### ISSUE TITLE
Brews turn into water bottles when placed in Playervaults /pv

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#135]
This plugin conflicts and wipes the data for brewery bottles, turning them into water bottles:

http://dev.bukkit.org/bukkit-plugins/playervaults/

This did not happen in older versions.

**Comment by Deiscorides** [comment]
I filed a ticket with them as well:

https://github.com/drtshock/PlayerVaults/issues/200

**Comment by Sn0wStorm** [comment]
Do normal potions turn to water as well? Brew potion items are only different to normal potion items in that they have custom potion effects added to them that store the brew id

**Comment by Deiscorides** [comment]
No, vanilla potions do not have this problem.

**Comment by Sn0wStorm** [comment]
Data storing in Brewery has been rewritten WIP to store data in Lore in a seperate branch, where as long as other Plugins keep the Lore it should still work. If other Plugins strip all data from items then there is not much i can do.

**Comment by Deiscorides** [comment]
Well, it seems that the open issue on the playervault page was closed and the official response was, "Correct. It only serializes what Bukkit knows about." Which was in reply to:

"I've found any item with anything for hiding flags (hiding enchantments & modifiers) will get completely wiped. I gave myself a few banners through commands (With "HideFlags:44" at the end to hide all the lore) and they were reset to white banners when I closed and reopened the vault."

**Comment by Sataniel98** [comment]
Bukkit does not know the others hide flags (32) for some reason, just 1-16 (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html). Therefore, it can't handle 44 (32+8+4). tl;dr; The serialization system of Bukkit does not cover all features of Minecraft. Issues like this one are, unfortunately, likely to occur if a plugin relies on nothing but it.

**Comment by Sn0wStorm** [comment]
Brewery uses default simplest bukkit serialization for items inside Barrels as well and Hide flags and everything else works completely fine. Brews use Hide flag for Potion Effects (32 i think) and they work in Barrels and keep their data. Tested Banner with Hideflags 63, works fine. See https://github.com/DieReicheErethons/Brewery/blob/master/src/com/dre/brewery/Barrel.java#L561 
Barrels get deserialized on server restart and world unload/reload if you want to test it. 
Ive always found the default bukkit serialzation to work the best of all, because it does store books, etc and a lot of custom data as well. 
So if i am not completely mistaken the problem is somewhere else.

**Comment by Deiscorides** [comment]
I personally think the playervaults plugin merely lacks full functionality, as evidenced by other plugins not working with the latest update of playervaults. If the dev(s) of that plugin don't update it with proper full support, it unfortunately forces everyone else to be handicapped and limited with their own plugins.

**Comment by Sn0wStorm** [comment]
I think not serialising items correctly could show a lot more problems, like books and anything with more than the bare data being wiped for example. So they probably need to fix that sooner or later.

**Comment by Sn0wStorm** [comment]
I could add a simple workaround by removing the hide flags when putting into a vault, maybe there are other custom inventories that would need this?

**Comment by Dovisary** [comment]
I am having this issue as well, except my brews are turning to water in normal chests and in the barrels (also pv).
