### ISSUE TITLE
Distilling = Thick Potion

### ISSUE THREAD

**Issue by Slothiful** [DieReicheErethons/Brewery#138]
**Hello,**

I am using Brewery v1.5 on Spigot 1.10.2, and ever since 1.9, I've never been able to distill beverages correctly. I'm placing blaze powder in the fuel spot and then glowstone as the ingredient, but it just quickly creates a Thick Potion by Vanilla Minecraft, but then slowly brews at the same time and after, but the result is nothing. Is there a way to fix this? I know it's because brewing was changed in 1.9, but I've waited a while for a solution but I've discovered none.

**Keep it Slothy,
Slothiful**

**Comment by Squeeing-Onion** [comment]
In case you didn't solve it yet / other people having the issue:

Don't use blaze powder when distilling, that right there is probably your problem.

All it takes is the glowstone up top to use as a filter, which doesn't get consumed.

**Comment by Slothiful** [comment]
@Squeeing-Onion This does not fix the issue. Video to show: https://youtu.be/PFxle1Qwxug
