### ISSUE TITLE
fass

### ISSUE THREAD

**Issue by jojoa** [DieReicheErethons/Brewery#139]
hallo ich kann kein fass erstellen weder groß noch klein es passirt nix kommt keine nachricht  etc.
<img width="647" alt="screenshot_2" src="https://cloud.githubusercontent.com/assets/18380579/18054047/9776f896-6e02-11e6-8f82-834ca26a1ae4.png">
<img width="333" alt="screenshot_3" src="https://cloud.githubusercontent.com/assets/18380579/18054049/9791a6dc-6e02-11e6-882e-c96b7f500ff5.png">

**Comment by Sataniel98** [comment]
Hast Du die deutschen Sprach-Files korrekt installiert? Ansonsten ist Englisch und "Barrel" Standard.

**Comment by jojoa** [comment]
Ja die sind installiert

Am 29.08.2016 17:21 schrieb "Daniel Saukel" <notifications@github.com>:
