### ISSUE TITLE
Brauen bzw. Kochen auch mit items von Slimefun

### ISSUE THREAD

**Issue by GiuseppeGroth** [DieReicheErethons/Brewery#140]
Hallo,
ich habe dass Plugin Slimefun
und dort gibt es Einige Früchte etc. zusätzlich
und wollte fragen ob man dies bei euch integriegen könnte
da dies einen den Handlungsspielraum und Fantasie deutlich erweitern würde
https://dev.bukkit.org/bukkit-plugins/slimefun/
https://dev.bukkit.org/bukkit-plugins/exotic-garden/
würde mich tierisch freuen 

Gruß

Giuseppe

**Comment by Sn0wStorm** [comment]
Custom items hinzugefügt in v2.0
