### ISSUE TITLE
Can't add ingredients to cauldron in 1.11

### ISSUE THREAD

**Issue by australr14** [DieReicheErethons/Brewery#142]
I'm running Spigot 1.11.2; after making the update, I installed and configured Brewery and tested it in game by fermenting some apples into apple cider (in a cauldron over fire with right click, the whole shebang). It came out fine.

Now, however, no ingredients can be added to cauldrons like this. I tried several times and so did a few of my players; no dice. I also tried adding the basic brewery user permission to the default group just in case, removed and reinstalled the plugin and all its folders, and it still isn't working for some reason, though commands still work normally.

Am I missing something really obvious? Or is this a compatibility issue with 1.11 and I should just be patient until there is actual support for 1.11.x? :P

**Comment by Sn0wStorm** [comment]
Did it work with 1.11 before? When did it stop working?

**Comment by australr14** [comment]
I only tested it the once with 1.11.2 when I first installed-- it worked fine when I first tried it, then I left it alone for a few hours and when I attempted to try again it no longer worked. I didn't even restart the server in that time.
