### ISSUE TITLE
Indefinable Brew - Can't figure out why

### ISSUE THREAD

**Issue by KhaosLeper** [DieReicheErethons/Brewery#144]
One of my recipes keeps coming up as an Indefinable Brew and I cannot figure out why.

I've tried changing to IDs, tried using Vault ways of using the name... nothing works.

   4:
      name: Skunked IPA/IPA/Dirt Drop IPA
      ingredients: 
      - WHEAT/4
      - WHEAT_SEEDS/1
      - MELON_SEEDS/1
      - PUMPKIN_SEEDS/1
      - DIRT/1
      - SUGAR/1
      cookingtime: 10
      distillruns: 0
      wood: 3
      age: 2
      color: PINK 
      difficulty: 1 
      alcohol: 6

**Comment by Squeeing-Onion** [comment]
Not sure if it will make a difference or not, but are all the ingredients you wanna use added to your ingredients list in the config?

**Comment by LordDecay26** [comment]
i get this same issue
