### ISSUE TITLE
Cannot Add Leaves as Ingredient

### ISSUE THREAD

**Issue by Squeeing-Onion** [DieReicheErethons/Brewery#145]
Hiya!
We've gotten the plugin installed and working with all the base recipes.  However, we are having issues implementing our custom recipes.

We cannot get any Leaf items to be able to be put into cauldrons as an ingredient for our custom recipes for teas.

   1:
     name: &7Leafy Water/&9Dark Tea/&3Shadow Tea
     ingredients:
     - LEAVES2,1/10
     cookingtime: 3
     distillruns: 1
     wood: 6
     age: 1
     color: BLACK
     difficulty: 5
     alcohol: 0 

is one example of a tea recipe.
Putting the leaves as a cookable ingredient doesn't work, it won't let us add them to the cauldron.

For the leaves ingredient list we've tried:

LEAVES2,1
LEAVES2:1
Dark_Oak_Leaves
Dark Oak Leaves
162:1
162,1

We were able to configure other items like a diamond item to be added, but not saplings.  Bedrock block was addable.

Any suggestions on troubleshooting this would be greatly appreciated. This plugin is absolutely godsend for our players RPing being brewers.  Thanks much!

~Squeeing Onion

**Comment by Sataniel98** [comment]
Most likely because it's supposed to be "LEAVES_2" with an underscore. You can find all values in the Bukkit JavaDocs.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by Squeeing-Onion** [comment]
Tried:
LEAVES
LEAVES_2
LEAVES_2,1
LEAVES_2:1

Still no go :(
Has anyone used leaves successfully in their plugin setup?

We do not have vault installed, but we're looking into setting it up if it might be the reason we can't add in new ingredients.

**Comment by Squeeing-Onion** [comment]
Update:  Fixed! Something must not have been formatted properly in the code, I started off a fresh config and added in the ingredients and now they're working perfectly for being added.
