### ISSUE TITLE
Ability to make players immune/resistant to being drunk [enhancement]

### ISSUE THREAD

**Issue by Squeeing-Onion** [DieReicheErethons/Brewery#146]
We host a roleplay server with several races each with their own lore and abilities, and it'd be awesome if we could make players who are of the Dwarven race far more resistant to becoming drunk, and, say, elves far more easily become drunk.

No idea if that's something easy or not to implement, but it's a thought!

**Comment by Sn0wStorm** [comment]
There could be a permission, for example "brewery.immunity75" for 75% alcohol immunity

**Comment by Sn0wStorm** [comment]
Implemented in 3166f8c81bcd61fb087305babfbd48c712294d12
