### ISSUE TITLE
Config formatting error

### ISSUE THREAD

**Issue by nightspider** [DieReicheErethons/Brewery#148]
I've been messing around with the config file for Brewery, removed all the factory presets and added my own custom drinks. I run 1.11.2 and it works just fine using the default configuration, but when I changed it, fermenting using the couldron stopped working. When I right click on the couldron, the ingredient isn't taken from my inventory. Can you help me format this correctly?

recipes:
#  Example Recipe with every possible entry first:
   0:
      name: Bad Example/Example/Good Example
      ingredients:
      - SUGAR_CANE/5
      - 264/1
      - INK_SACK,3/20
      - 5,1/8
      - BEDROCK/1
#     - Jungle Leaves/64  # Only with Vault
#     - Green Dye/6       # Only with Vault
      cookingtime: 3
      distillruns: 2
      distilltime: 60
      wood: 4
      age: 11
      color: DARK_RED
      difficulty: 3
      alcohol: 23
      effects:
      - FIRE_RESISTANCE/20
      - HEAL/1
      - WEAKNESS/2-3/50-60
      - POISONX/1-0/20-0

   1:
    name: Ruined Latte/Mediocre Latte/Pumpkin Spice Latte
    ingredients:
    - PUMPKIN/2
    - SUGAR/5
    - COCOA/5
    - MILK_BUCKET/2
    cookingtime: 2
    distillruns: 4
    distilltime: 40
    color: ORANGE
    difficulty: 5
    effects:
    - SPEED/1/0-30
    - REGENERATION/0-2/10
    - GLOWING/1/30
    

   2:
      name: Gritts/Strong Coffee/Black Roast
      ingredients:
      - COCOA/10
      cookingtime: 2
    distillruns: 4
      color: BLACK
      difficulty: 3
      effects:
      - REGENERATION/1/0-10
      - SPEED/2-4/30-140

   3:
      name: Gritts/Coffee/French Roast
      ingredients:
      - COCOA/10
    - SUGAR/1
    - MILK_BUCKET/1
      cookingtime: 2
    distillruns: 4
      color: BLACK
      difficulty: 4
      effects:
      - REGENERATION/2/3-5
      - SPEED/2/30-140

   4:
      name: Gritts/Decaf Coffee/Decaf Roast
      ingredients:
      - COCOA/5
    - SUGAR/2
    - MILK_BUCKET/2
      cookingtime: 2
    distillruns: 4
      color: BLACK
      difficulty: 1
      effects:
      - REGENERATION/1/3-5
      - SPEED/1/30-140

   5:
      name: Gritts/Good Espresso/Pure Espresso
      ingredients:
      -COCOA/20
    -GHAST_TEAR/1
    -MILK_BUCKET/2
      cookingtime: 4
    distillruns: 8
      color: BLACK
      difficulty: 6
      effects:
      - DAMAGE_RESISTANCE/1/30
    - HUNGER/2/50-200
    - JUMP/1/30-140
      - SPEED/6/30-140

   6:
    name: Ruined Brew/Mediocre Vodka/50' Vodka
    ingredients:
    - POTATO_ITEM/20
    cookingtime: 4
    distillruns: 3
    distilltime: 80
    age: 4
    wood: 0
    color: WATER
    difficulty: 3
    alcohol: 30
    effects:
    - DAMAGE_RESISTANCE/2/10-40
    - CONFUSION/1/100-40
    - FIRE_RESISTANCE/1/5-20
    - POISON/1/5-0

   7:
    name: Ruined Brew/Rum/Spiced Rum
    ingredients:
    - APPLE/2
    - WHEAT/20
    - REDSTONE/5
    cookingtime: 2
    distillruns: 2
    distilltime: 50
    age: 6
    wood: 2
    color: ORANGE
    difficulty: 6
    alcohol: 15
    effects:
    - SPEED/1/0-40
    - REGENERATION/0-2/50

   8:
    name: Ruined Brew/Hard Liquor/Scotch
    ingredients:
    - WHEAT/32
      cookingtime: 2
    distillruns:3
    age: 12
    wood: 2
    color: ORANGE
    difficulty: 8
    alcohol: 55
    effects:
    - CONFUSION/2-1/40-10
    - LUCK/0-2/10-50
    - HEALTH_BOOST/0-2/20-50
    - FIRE_RESISTANCE/2/20-100

   9:
    name: Ruined Brew/Hard Liquor/Whiskey
    ingredients:
    - WHEAT/20
      cookingtime: 2
    distillruns: 2
    age: 8
    wood: 2
    color: ORANGE
    difficulty: 5
    alcohol: 43
    effects:
    - CONFUSION/2-1/50-10
    - LUCK/1/0-30
    - HEALTH_BOOST/0-1/10-60
    - FIRE_RESISTANCE/1-2/10-80

   10:
    name: Ruined Brew/Wheat Beer/Wheat Draft
    ingredients:
    - WHEAT/10
      cookingtime: 2
    distillruns: 1
    age: 2
    wood: 0
    color: BLACK
    alcohol: 6
    difficulty: 2
    effects:
    - LUCK/1/5
    - HUNGER/1/3

   11:
    name: Mixed Chemicals/Acid/Refined LSD
    ingredients:
    RED_MUSHROOM/10
    CACTUS/10
    GHAST_TEAR/1
    ROTTEN_FLESH/20
      cookingtime: 2
    distillruns: 10
    age: 30
    wood: 0
    color: PINK
    difficulty: 10
    alcohol: 99
    effects:
    CONFUSION/10-5/200
    BLINDNESS/1/10-3
    GLOWING/3/200
    LEVITATION/1/20

And here are my ferments

   WHEAT: Hops
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: xXXXx
   MILK_BUCKET: Cream
   COCOA: Gritts
   REDSTONE: Spice Brew
   GHAST_TEAR: Raw Spirits
   PUMPKIN: Pumpkin Extract
   RED_ROSE: Herbal Mixture
   SNOW_BALL: Icy Mix
   YELLOW_FLOWER: Herbal Mixture
   CACTUS: Cactus Soup
   ROTTEN_FLESH: Congealed Blood

Any help you could give me would be appreciated

**Comment by nightspider** [comment]
I found the issue. Spaces matter. Thanks for making it easy to figure out. Maybe put a comment that says spaces matter, or it might just be because I'm new to this. Great mod though!

**Comment by Sataniel98** [comment]
Spaces and so on are a matter of the YAML syntax. This might help you a bit in the future :)

http://www.yamllint.com/
