### ISSUE TITLE
Normalize the ID's of brews with identical attributes

### ISSUE THREAD

**Issue by kholbekj** [DieReicheErethons/Brewery#154]
I don't know how feasible it is, but in the matter of shop incompatibility, perhaps a solution could be for a brew to check if there's already a brew entry with identical properties, and if so, persist it and become a copy of it. It'd mean you'd have to precisely emulate your previous runs to make a working shop, which seems like a reasonable requirement regardless.

This could be barred by a command, like "labeling" or "finalising" the brew, to reduce when we check for existence, as well as making the persistence optional.

**Comment by Sn0wStorm** [comment]
A Solution to this is being worked on, store all data on the Item itself. https://github.com/DieReicheErethons/Brewery/tree/2.0-StoreDataInLore
