### ISSUE TITLE
Barrel Issues

### ISSUE THREAD

**Issue by doitliketyler** [DieReicheErethons/Brewery#158]
Currently, I have some big barrels set-up at spawn and only the jungle and oak barrels open for players while the rest can only be opened as OP. Do you know why this is happening?

**Comment by BlueSoapTurtle** [comment]
Probably too close to /spawn?
Server.properties has a spawn-radius setting set to deny any non op player from doing anything in 16 block radius

**Comment by doitliketyler** [comment]
Haha...I can't believe I didn't think to check that and that's exactly what it was. Thank you. Cheers.
