### ISSUE TITLE
Aging config

### ISSUE THREAD

**Issue by Turkslayer** [DieReicheErethons/Brewery#170]
A new option to make aging much much slower? I would like the option to make 1 year 3 real life days. Possible? Thank you, love the plugin,

**Comment by max12rcg** [comment]
I also need this i can't get anything added

**Comment by Sn0wStorm** [comment]
You could always change the recipes so that each one needs a lot more years in aging? Or would that not be enough

**Comment by max12rcg** [comment]
yes but its not working no idea why

**Comment by Sn0wStorm** [comment]
If it still isn't working, please reopen
