### ISSUE TITLE
Unable to revoke overdrink and logindeny bypasses for OPs

### ISSUE THREAD

**Issue by eirikh1996** [DieReicheErethons/Brewery#171]
So on my server, I want to make it so that even OPs can be kicked or denied login due to being drunk. I have tried this by negating the permissions for EVERYONE, including for OPs.

This is how I have made it in the permissions.yml file in the server directory.
server.brewery:
       description: Brewery overdrink permissions
       default: false
       children:
        brewery.bypass.logindeny: false
        brewery.bypass.overdrink: false
\
However, no matter how I try to take away these permissions from the OPs, they are ALWAYS able to bypass overdrink or logindeny.

**Comment by thomaboehi** [comment]
Maybe you should reduce the OP level in server.properties. Or simply remove OP and use only permissions (longer but easier for the future).

**Comment by Sn0wStorm** [comment]
Tried it with LuckPerms and setting the permissions to false works perfectly fine
