### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by ItsAAP** [DieReicheErethons/Brewery#173]
I have tried editing the config file to create custom recipes for the Brewery plugin, and I first tried using just the item name, but it didn't work. The second time, I used the Item ID, and that didn't work either. Please fix this! Thank you!

**Comment by Sn0wStorm** [comment]
Could you post the recipe you tried to add?

**Comment by renaudgaming** [comment]
i am french guy 
I think I have the same problem,
I created this

11:
      name: Bad Miner/Miner/Good Miner
      ingredients:
      - diamond_block/1
      cookingtime: 3
      distillrun:3
      distillrun:30
      color: CYAN
      difficulty: 1
      effects:
      -FAST_DIGGING/2/360-580/

I have even to add to the cooked :

 diamond_block: miner brew 

but is doesn't work

I hope you could help me because I’d like to have this potion for my server

**Comment by Sn0wStorm** [comment]
you’ve got distullruns in there 2 times. Also it should be distillruns (with s) and it needs a space after the : so distillruns: 30

Also make sure you don’t have any other 11.th recipe

It would be best to run in through an online yml parser to see any errors immediately
