### ISSUE TITLE
linking Brewery to Herbalism

### ISSUE THREAD

**Issue by Dave5080** [DieReicheErethons/Brewery#174]
Hi there, I love this plugin and i had an idea to use it in a revolutionary way. But to accomplish that I'd like to use in brewery's recipe some custom items implemented by other plugins (like Herbalism in my case). Could it be possible?

**Comment by Sn0wStorm** [comment]
Its not possible currently and i don't have a clear idea how to accomplish this with the current way how recipes are defined in a config

**Comment by Sn0wStorm** [comment]
Added custom items in v2.0
