### ISSUE TITLE
[Feature request] Custom items

### ISSUE THREAD

**Issue by jordanwilliams1** [DieReicheErethons/Brewery#178]
Hello, I Recently downloaded the brewery and the plugin is awesome. However, I Did Want to tinker with it and put my own custom touch to it but I was unable to. I Wanted to make special drinks for quests, etc. I Think it would be a brilliant addition if you were able to require custom items(custom name/lore items) for the recipes. This would open so many more doors for this plugin. 

For example, I could have a custom item like a grape that I could add to a custom brew?https://i.gyazo.com/027b56b367e560f5dd184240a0ae4dc2.png

Example of custom items in config:
https://pastebin.com/raw/sC1sPdW4

**Comment by Sn0wStorm** [comment]
Yes this could be a nice addition

**Comment by jordanwilliams1** [comment]
Would this be something that you would consider adding soon? @Sn0wStorm

**Comment by Sn0wStorm** [comment]
Currently i dont have time to implement this, so no :(

**Comment by Sn0wStorm** [comment]
Added custom items in v2.0
