### ISSUE TITLE
World Guard Compatibility

### ISSUE THREAD

**Issue by Foxstone1** [DieReicheErethons/Brewery#181]
The config is not reading the worldguard selection properly. Whether set to true or false, it still checks to see if worldguard is enabled on the server and if it is, it will not register the selection in the config file.

**Comment by Sn0wStorm** [comment]
I can not reproduce this, when disabling WorldGuard in the config, i can open any barrel and WorldGuard is not checked.
You can test this by installing a broken WorldGuard config (i.e. install latest WG and FAWE, makes WG crash) and it results in an error when WorldGuard is enabled in the config and it works fine when it is disabled.
