### ISSUE TITLE
1.14 Minecraft Update

### ISSUE THREAD

**Issue by LordBanshee** [DieReicheErethons/Brewery#182]
Due to the 1.14 Minecraft Update, I haven't been able to get the Brewery Plugin to work. I am on the development build for Spigot at the moment, so that could also be related to the issue. In my console, I am given error codes which refer to duration values inside the database. Alcoholic beverages spawned in still don't give any drunk value to the player.

When should an update be expected? Thanks!

**Comment by Sataniel98** [comment]
Resolved in #183

**Comment by LordBanshee** [comment]
Is this being worked on? I really enjoy the plugin, but if it's not being worked on I'd like to know, as to not get my hopes up too high. Thanks.

**Comment by Sataniel98** [comment]
As for my part, I'll at the latest fix the remaining issues when I update my own server since I also need this. This however might not happen within a few days or weeks.

**Comment by LordBanshee** [comment]
I look forward to the update. Thank you a bunch.

**Comment by Yukyxy** [comment]
Hello please could you update to 1.14 soon? :)

**Comment by TristanVdElzen** [comment]
Issue can be closed. #183 was merged some time ago.
