### ISSUE TITLE
Change prefix

### ISSUE THREAD

**Issue by RyanFlm** [DieReicheErethons/Brewery#184]
https://github.com/DieReicheErethons/Brewery/blob/13d13dcf7211dbd391664cb9f20f87c2c9917bf8/src/com/dre/brewery/P.java#L272

Hey there.
Is it possible to change the prefix of messages or can you make it possible?
That would be very nice!
Thank you for your support!

Ryan

**Comment by Sn0wStorm** [comment]
May i ask for what reason you need to change the prefix?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sn0wStorm** [comment]
Will not be implemented for now. If someone still needs this please reopen
