### ISSUE TITLE
Unable to Find UID of Potions

### ISSUE THREAD

**Issue by karitkake** [DieReicheErethons/Brewery#185]
I've been trying to create vodka and beer, but the distillation and aging proccesses only leave me with meassages such as the following:

[23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -36 of a custom Potion!
--
173 | [23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -48 of a custom Potion!
174 | [23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -44 of a custom Potion!
175 | [23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -40 of a custom Potion!
176 | [23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -32 of a custom Potion!
177 | [23:33:14] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -52 of a custom Potion!

**Comment by Sn0wStorm** [comment]
Something must have gone wrong with your data file for brewery

**Comment by Sn0wStorm** [comment]
Turns out this was an error that happened in 1.14. This is fixed with commit e62e9a61c2b031c6a70ff1fa7c637c5cffb12f22
