### ISSUE TITLE
Can't Build From github.

### ISSUE THREAD

**Issue by iarepandemonium** [DieReicheErethons/Brewery#186]
Trying to build this project directly from your github but the world edit dependency isn't building because it's not present in the maven repo.

**Comment by sarhatabaot** [comment]
Change the version to 7.0.0-SNAPSHOT

**Comment by iarepandemonium** [comment]
@sarhataboat yes i did n made a pr to the repo

**Comment by Sn0wStorm** [comment]
PR accepted
