### ISSUE TITLE
Recipes don't work with dyes?

### ISSUE THREAD

**Issue by QueenSatina** [DieReicheErethons/Brewery#190]
I am trying to create "fruity brews", with dyes as the fruit as an ingredient.
I've tried the following (for orange dye):
351:15
351,15
ORANGE_DYE
This is the full config for it, with INK_SACK
   7000:
      name: Bad Apricot Brandy/Good Apricot Brandy/Perfect Apricot Brandy
      ingredients:
      - 338/2
      - INK_SACK,14/2 
      cookingtime: 2
      distillruns: 3
      distilltime: 60
      wood: 2
      age: 1
      color: ORANGE
      difficulty: 1
      effects:
      - WEAKNESS/1/90-30
      - SLOW/1/90-30
      - CONFUSION/1/90-30
I don't really know what else I could do to make it work, but maybe I'm just not thinking about it enough. I just keep getting indefinable brew. I have added it to the cooked part for what the name is after cooking. If I continue the brew process, the name later comes up, but I'm afraid of players thinking they did it wrong and just throwing the brew out.
Also, it seems as though, though I have it to need aging, it will come up as "perfect apricot brandy" after just distilling without any aging.
Edit: This happens with any item like the dye, that has :_ after it. I tried tall grass and it also didn't work.

**Comment by Sn0wStorm** [comment]
If you are on 1.13 you will not be able to use numeric ids and data values as they have been removed by bukkit. 
So the 338 won’t work and the ,14 won’t work.
ORANGE_DYE is the correct one, so using that should be fine 

It comes out as perfect because the difficulty is set to 1, this means the players can do a lot of things wrong and still get good results like in this case not aging at all still resulting in perfect drinks.

**Comment by QueenSatina** [comment]
<img width="523" alt="Screenshot 2019-07-03 at 11 03 10" src="https://user-images.githubusercontent.com/50128763/60602635-2b57e280-9d82-11e9-9c17-f4d900044ce7.png">

I tried ORANGE_DYE and put it in at the bottom, but it doesn't register. The server is 1.12.2
The item ids work for other brews that require sugar cane.

**Comment by Sn0wStorm** [comment]
On 1.12 and below, the new names like ORANGE_DYE don't work yet. (They were simply not implemented by Bukkit yet) 
You will have to try and find older descriptions of Bukkit names or you could try 351,14

**Comment by Sn0wStorm** [comment]
If you or anyone still has the problem to find the correct name for an item or ingredient,  
you can now hold that item in your hand and use /brew ItemName to find the correct material name.
