### ISSUE TITLE
Big Barrels Aren't removed after breaking the sign

### ISSUE THREAD

**Issue by zek2468** [DieReicheErethons/Brewery#191]
Im using version 1.7.2 stable
I noticed that if you make a Big barrel of any wood type or sign type then break the sign the barrel still persist but its not a big deal because it go away after you break any block thats apart of the structure.

Heres video of it happening on my server
[https://www.youtube.com/watch?v=TvVs0QDgP2I&feature=youtu.be](https://www.youtube.com/watch?v=TvVs0QDgP2I&feature=youtu.be)

For some reason this do not effect the small barrels

**Comment by Sn0wStorm** [comment]
This is intended behavior.

Big barrels main block is actually the front fence. Removing that will destroy the barrel.
This is intended so players can make the Barrels look a bit nicer without the sign on top.
I know this is confusing as the small barrels need the sign, but i thought it is still nice to allow the sign to be removeable on the big barrels.
