### ISSUE TITLE
Request for authorization of Chinese translation, and some additional problems.

### ISSUE THREAD

**Issue by sjackser** [DieReicheErethons/Brewery#193]
I am a Chinese player and I do love the feeling and creativity of this plugin, hence I translated the plugin into Chinese, however, there are a few issues I have encountered to be are very specific to the Chinese language, thus I need some help.
1. We don't have suffixes for plural on most occasions, thus I want to remove it. It seems like I cannot simply remove the line or something. What should I do?
2. We usually don't use spaces, how can I get rid of them?

**Comment by Sn0wStorm** [comment]
1. For the suffixes you can remove them by using an empty line with 2x ' like so: 
Brew_MinutePluralPostfix: ''
2. I dont think its possible to get rid of all spaces, it would need some code changes to remove spaces based on a specific language.

**Comment by Sn0wStorm** [comment]
Implemented in 1.8.1
