### ISSUE TITLE
Water & Lava bucket

### ISSUE THREAD

**Issue by sgalasso42** [DieReicheErethons/Brewery#195]
Hello,
When we place water with a bucket, if there is a bloc next to it then it destroy that one, and the bucket is changing place on the inventory..<br>
Thanks

**Comment by Sn0wStorm** [comment]
Do you mean placing water in a cauldron? 
I have tried and no blocks are destroyed. Maybe could you do a video?

**Comment by sgalasso42** [comment]
No use the water on the cauldron is fine
There is a video :
https://drive.google.com/open?id=1afDN0o4TjpTn2OTlLnPDLpzEAQWX5pJa

**Comment by Sn0wStorm** [comment]
I cant see Brewery in the plugin list.
The problem is very likely the plugin ItemStackReloaded
