### ISSUE TITLE
[Suggestion] Ingredients NBT/Custom naming.

### ISSUE THREAD

**Issue by Patbox** [DieReicheErethons/Brewery#200]
It would be useful to be able to set ingredients as items with a custom name. This would be useful on servers with their own custom items.

**Comment by Sn0wStorm** [comment]
This will be added in one of the next updates.
Duplicate #178 , #174 , #140 , #79

**Comment by Sn0wStorm** [comment]
Some plugins to test custom items
https://www.spigotmc.org/threads/brewery.43694/page-15#post-3529139

**Comment by galacticwarrior9** [comment]
This would be an excellent addition, especially when using plugins such as ExoticGarden and Vineyard.

**Comment by Sn0wStorm** [comment]
Added Custom items in v2.0
