### ISSUE TITLE
[Suggestion] Storing player effects in database

### ISSUE THREAD

**Issue by jere62smi** [DieReicheErethons/Brewery#208]
Hello,
I saw that you have resumed activity on the Brewery plugin and I would like to make a suggestion for multi-servers. Indeed, our infrastructure is divided into bungee for more performance but unfortunately the effects of alcohol are not synchronize between the servers. I would like to know if it would be possible for you to store these effects in database in order to fix this problem.

**Comment by Sn0wStorm** [comment]
This is a good idea!
I usually prefer to use plugin-messages for multi server, but a simple database table would work well in this case too. I have to compare the downsides of either method.

**Comment by jere62smi** [comment]
Hello,
I hope you are well, I would like to know if you started the option to store players' alcohol effects in database for mutli-servers?
I know I'm impatient but still have no news, I've been waiting for this option for years.

**Comment by Sn0wStorm** [comment]
In the new Update, you can set a shared MySQL database and that will sync the playerdata between servers.
