### ISSUE TITLE
Suggestion: Add Spicy Whiskey and Bourbon

### ISSUE THREAD

**Issue by FrostyLadyLoki** [DieReicheErethons/Brewery#210]
_**Spicy Whiskey**_
**Ingredients**
5x Wheat
2x Sugar
1x Blaze Powder

**Distill Time**
5 Distills

**Age Time/Barrel Type**
7 Years/Oak Barrel

_**Scotch**_
**Ingredients**
16x Wheat Seeds
2x Sugar

**Distill Time**
2 Distills

**Age Time/Barrel Type**
3 Days/Oak Barrel

**Comment by Sn0wStorm** [comment]
I don't really want to add too many recipes, as i want to let server owners create them for themselves as they want to.
Otherwise players can just read the recipes in this github and make it too easy for everyone to brew them

**Comment by Sn0wStorm** [comment]
Added some new default recipes in v2.0
