### ISSUE TITLE
I can´t add new recipe in minecraft brewery plugin

### ISSUE THREAD

**Issue by alexandermhg** [DieReicheErethons/Brewery#211]
hi, guys, I am playing Minecraft with my friends on a server with the brewery plugin and we want new recipe I tried to make new but it doesn't works i added it to the config and i tried it out but it not work here my recipe:
1:
      name: Schlechtes Weizenbier/Weizenbier/Gutes Weizenbier
      ingredients:
      - WHEAT/3
      cookingtime: 5
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Skunky Beer/Beer/Fine Beer
      ingredients:
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
      ingredients:
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Awkward Mead/Mead/&6Golden Mead
      ingredients:
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 9
   5:
      name: Apple Mead/Sweet Apple Mead/&6Sweet Golden Apple Mead
      ingredients:
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 4
      alcohol: 12
      effects:
      - WATER_BREATHINGX/1-2/150
   6:
      name: Bitter Rum/Spicy Rum/&6Golden Rum
      ingredients:
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      distilltime: 30
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 30
      effects:
      - FIRE_RESISTANCE/1/20-100
      - POISONX/1-0/30-0
   7:
      name: Lousy Vodka/Vodka/Russian Vodka
      ingredients:
      - POTATO_ITEM/10
      cookingtime: 5
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 20
      effects:
      - WEAKNESS/15
      - POISON/10
   8:
      name: Poor Absinthe/Absinthe/Strong Absinthe
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      distilltime: 80
      color: GREEN
      difficulty: 8
      alcohol: 45
      effects:
      - POISON/20-30
   9:
      name: Potato soup
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
      effects:
      - HEAL/0-1
   10:
      name: Stale Coffee/Coffee/Strong Coffee
      ingredients:
      - INK_SACK,3/12
      - MILK_BUCKET/2
      cookingtime: 2
      color: BLACK
      difficulty: 3
      effects:
      - REGENERATION/1/2-5
      - SPEED/1/30-140
   11:
      name: Schlechter Whisky/Whisky/Perfekter Whisky
      ingredients:
      - WHEAT/15
      - APPLE/5
      cookingtime: 10
      distillruns: 6
      age: 6
      color: ORANGE_DYE
      difficulty: 7
      alcohol: 55
      effects:
      - POISON/20
      - SLOWNESS/30
      - BLINDNESS/25
Thanks for help

**Comment by Sn0wStorm** [comment]
What does it say when you do /brew reload ?
Use an online yml parser to check if the config is correct
