### ISSUE TITLE
Dumb question about recipe format

### ISSUE THREAD

**Issue by mercurialmusic** [DieReicheErethons/Brewery#214]
I'm sorry, I know this is a stupid question, but in the config is the numbering system necessary for the brewing recipes or can it be any YAML-appropriate name? For example `gin:` instead of `2:`? In trying to retain some organization in the config, I'm finding that the number system is only making things more confusing with lots of recipes and frequent additions.

Thanks for humoring me!

**Comment by Sataniel98** [comment]
This should work from what I can tell.

**Comment by mercurialmusic** [comment]
It worked!

**Comment by Sn0wStorm** [comment]
The name only has to be unique as far as i know!
