### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by Sn0wStorm** [DieReicheErethons/Brewery#216]
### The development of Version 2.0 can be followed in this branch [v2.0](https://github.com/DieReicheErethons/Brewery/tree/v2.0)

The main new features as planned at the Moment are:
A completely new Save System for Brews, new API with Events, more versatile Recipes with custom Items, custom Lore and general enhancements.

Progress:

**Save Brewdata**
- - [x] implement new save system
- - [x] invisible Lore for old Minecraft versions
- - [x] into NBT
- - [x] remove old legacy data
- - [x] testing

**API**
- - [x] Basic Events and API 
- - [x] More Events
- - [x] Player API
- - [x] Recipe API
- - [x] refining
- - [x] testing

**Recipes**
- - [x] Config entry for custom items
- - [x] More options for items like name, lore, custom
- - [x] Support Items of other Plugins
- - [x] add recipes by plugins
- - [x] changeable by plugins
- - [x] Execute Commands when drinking
- - [x] Messages when drinking
- - [x] testing

**Lore**
- - [x] Better Lore Handling
- - [x] Custom Lore
- - [x] Star rating for quality
- - [x] %Alc when in distiller
- - [x] testing

**More**
- - [x] Bounding Box for barrel detection
- - [x] More performance optimizations
- - [x] Performance profiling
- - [x] Reenable Metrics
- - [x] refractoring
- - [x] testing

**Comment by illumeleet** [comment]
which minecraft versions will it support?

**Comment by Sn0wStorm** [comment]
It will support all versions from 1.8 to 1.14 as before. Versions below might still work as well.
I've made it a point to keep supporting as many versions as possible, but future versions like 2.1 will likely drop support for older versions.

**Comment by jere62smi** [comment]
Oh great, I see that the 2.0 is ready soon, I am presser to test that :)

**Comment by Sn0wStorm** [comment]
The Update to 2.0 is almost done. Mainly testing needs to be done now.

It would be very helpful if someone wants to test this on a server with some player and just test the brewing process. If someone is able to do that, please let me know!

**Comment by jere62smi** [comment]
Hi, I can volunteer to test the version but I will need additional information to install this new version.

**Comment by Sn0wStorm** [comment]
Cool thank you! I'm finishing the configs now and could send you the plugin after that.

**Comment by Sn0wStorm** [comment]
Instructions for Beta testing and Beta download here: #227
