### ISSUE TITLE
Chat Distortion Not Working

### ISSUE THREAD

**Issue by CraftyBr** [DieReicheErethons/Brewery#217]
I'm not sure what's happening but my chat distortion is not working for me. 
Brewery Config Version: 1.8
Chat Plugin: Venture Chat
Evidence: 
![image](https://user-images.githubusercontent.com/27068897/66871382-8ac4b180-ef71-11e9-8a60-772c2ef26dda.png)

**Comment by Sn0wStorm** [comment]
Please set these three config options to true:
_enableChatDistortion_
_logRealChat_
_distortSignText_

1. Test again and see if you get a line in the console or server log saying 'CraftyBr tried to say ...'
2. Test if you write on Signs they get distorted

Maybe the Chat plugin only works at Bungee level?

**Comment by CraftyBr** [comment]
Okay so apparently there was nothing wrong with the plugin, there was just a small error in my config that caused chat distortion to not function properly. 
**Problem Resolved.**
