### ISSUE TITLE
TownyAdvanced support

### ISSUE THREAD

**Issue by illumeleet** [DieReicheErethons/Brewery#220]
would be nice if you add towny support in new 2.0 version

**Comment by Sn0wStorm** [comment]
What doesn't work with towny?

**Comment by illumeleet** [comment]
Sorry for late answer, i meant something like adding switch permissions check before opening barrels, so that outstanders  couldn't open them in towns they don't belong to.

**Comment by SmallSansSerif** [comment]
Would also love a hook/option with Towny so that you could force when drunk that the garbled chat to be local if desired. Towny has general/town/nation and local chat.
