### ISSUE TITLE
Permission nodes for MC 1.14 barrels

### ISSUE THREAD

**Issue by TKwSni** [DieReicheErethons/Brewery#222]
Is it possible to add a permission to use MC barrels as  Brewery barrels?
brewery.createmcbarrel
brewery.openmcbarrel

And maybe permission for the "maxBrewsInMCBarrels" option in the config? 
brewery.maxBrewsInMCBarrels.X

As i have rankups in my server for my cooking job, people are able to create barrels and use them accoring to their rank level.

I have noticed that you can also use hoppers and bypass the amount of brews you can put in the barrel

**Comment by Sn0wStorm** [comment]
> I have noticed that you can also use hoppers and bypass the amount of brews you can put in the barrel

You can, but they will not age.

(This is because checking the Hopper Events would be _very_ expensive)

**Comment by Sn0wStorm** [comment]
Implemented Permission node brewery.openbarrel.mc
