### ISSUE TITLE
Add an option to disable creative access to barrels

### ISSUE THREAD

**Issue by Syrkulous** [DieReicheErethons/Brewery#223]
Players are able to access barrels using creative mode which allows duping.
This can be quite an error for many servers that separate the 2 inventories.

**Comment by Sn0wStorm** [comment]
Which plugin are you using that separates the 2 inventories?

**Comment by Syrkulous** [comment]
GamemodeInventories

**Comment by Sn0wStorm** [comment]
I have added a check that automatically disallows opening Barrels in Creative Mode when GamemodeInventories restricts inventory access. It will be in v2.0
