### ISSUE TITLE
1.14.4 no aging.

### ISSUE THREAD

**Issue by Rpuxshi** [DieReicheErethons/Brewery#224]
I just downloaded the plugin 2 day ago, everything works well except the "aging" proces, no matter what I do, time, wood, amount, it just doesn´t age the drinks.
¿Any idea of what could it be?

The server actually runs in "offline mode", and we also have a plugin called "Harbor" that help us to skips night time when 1 playes goes to bed.

Besides that, everything seems to work really well.

**Comment by Sn0wStorm** [comment]
Could you try both the Minecraft Barrels and the Brewery Barrels?
Also close the barrel and wait at least 10 minutes before opening it, it is supposed to take a while before they get aged.
I have found no issue with using Harbor, but if it still doensn't work, maybe you could try if it works without Harbor.

**Comment by Rpuxshi** [comment]
Ok. So I tried the MC barrels and they seems to work. But small and big brewery barrels didn't. 
Do I need to put in the bottles in an specific way or something? I always recived the confirmation message in the chat about the creation of the barrels.

**Comment by Sn0wStorm** [comment]
That is very strange indeed. The routine for aging the MC Barrels and the Brewery Barrels is almost the same and called one after the other.
It works fine for me with Harbor installed!
No you don’t need to do anything special if you can open the Barrels.
Does it work without Harbor for you?
You could also try the new Brewery 2.0-beta here #227 and see if it works with that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rpuxshi** [comment]
I've not had the oportunity to try without Harbor on that server. 
However, I tried on a different one just with Harbor and brewery installeds, and worked perfectly.
I assume that the problem might be a different plugin. Now I'm gonna try disabling everything and checking one by one. I will let you know if I found anything about it.
Thank you for your help about all this :D

**Comment by Sn0wStorm** [comment]
Thank you for testing your other Plugins, i appreciate it! Please let me know if you find which plugin is incompatible with Brewery so i can see what i can do about it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rpuxshi** [comment]
After a maintenance night I finally found the problem.
Looks like "OpenInv" is not compatible with Brewery.
If you would like to take a look, here is the link:
https://dev.bukkit.org/projects/openinv

Any suggestion about a plugin to look into players inventory that could work?

Thank you for all your help :D

**Comment by Sn0wStorm** [comment]
There seems to be a bug in OpenInv, I have opened an issue with them here https://github.com/lishid/OpenInv/issues/115
As long as you disable "silentcontainer" in OpenInv, it _should_ be fine
Thank you for the find!

**Comment by Rpuxshi** [comment]
Thank you for all your help.
I really love your plugin, everyone on the Server os enjoying it so much!
