### ISSUE TITLE
Brewery potions pop out of brewing stands

### ISSUE THREAD

**Issue by Duvetyn** [DieReicheErethons/Brewery#225]
I'm not sure if this is an already established and addressed issue, but I couldn't find anything about it by googling it.

Whenever anyone tries to put a brewery beverage into a brewing stand, when they exit the brewing menu the potion pops out again, like with items in a crafting table. I'm not sure why this is happening, but none of the plugins we have on the server should be causing this and I don't see anything about it in the brewery config.

I'm using Brewery-1.8.2.jar, my server is 1.12.2 paperspigot. The brewery config has been heavily changed in order to add a lot of new drinks for the players, so that may be the root of the issue but I'm not sure what would be the cause in it. https://pastebin.com/bT0F4Ct5

**Comment by Sn0wStorm** [comment]
I have never seen that happening, and there is nothing in Brewery that would make them pop out. Does this also happen with other Potions?

**Comment by Duvetyn** [comment]
I hadn't tested that before I made this, which was kind of dumb, but yes it happens for every potion. I've been looking up this issue with brewing stands for a while now and haven't found anything on it in google either, which is strange.

**Comment by Sn0wStorm** [comment]
I don't know what could cause that. I don't think its Brewery.

**Comment by Duvetyn** [comment]
I think you're right, sorry for the distraction.
