### ISSUE TITLE
Beta testing needed

### ISSUE THREAD

**Issue by Sn0wStorm** [DieReicheErethons/Brewery#227]
The version 2.0 has now been released and i’ve tested all of the new features. I would appreciate if people using and testing it could send me some logs and timing reports

You can download the source and compile it yourself with `mvn install`
or download here: 
[Releases](https://github.com/DieReicheErethons/Brewery/releases)

Put Brewery in your plugin folder and restart server
Set debug: true in the config file and do /brew reload
Check your log for errors

If possible send me the log file later

### Please test:

- Config Updater
   - Test if the config with your recipes gets updated
- Brewing Process
   - Test the Brewing Process of new and existing Brews
   - Everything should work fine
- Timings
   - Do a timings report over a timespan with players using the plugin
- Existing Brews
   - Check if existing brews still work and look ok
- Feedback
   - Do you like the stars on the brew always showing?
   - New way of defining Cauldron Recipes
   - Other changes?

### Optional:
- Send me the brewery data.yml before and after updating
- Check if existing barrels can still be opened
- test custom items in recipes
- Feedback to the new API

#### Please send me the server log file and any other files **here**, or on [Spigot: Message to Sn0wStorm](https://www.spigotmc.org/conversations/add?to=Sn0wStorm), or on [Bukkit: Message to sn0wystorm](https://dev.bukkit.org/private-messages/send?recipient=sn0wystorm)

**Comment by jere62smi** [comment]
I have done some tests and I do not see anything abnormal at the moment, however, there is still no option to store players' alcohol effects in database for multi-servers?

**Comment by Sn0wStorm** [comment]
Glad it worked for you!
Sorry no the database support is not working yet, but i have made some preparations and it will also include the encode Key so that all Multi Servers have the same encode key. It will be included in the next update!

**Comment by Valaron-Jakob** [comment]
Habe es ebenfalls mal durchgetestet und auch bei komplizierteren Rezepten keine Probleme gehabt.
Bin sehr begeistert, dass es so wundervoll funktioniert. Gute Arbeit!

Endlich kann ich mich an das Alchemiesystem setzen :P

**Comment by Sn0wStorm** [comment]
Sehr schön, danke fürs testen :)

I've made some fixes and added lots of new default recipes: 214bb5293920ca4dd01d24de411125817feb9916
You can test the new Beta now but apart from that its the same: [Brewery-2.0-beta2.zip](https://github.com/DieReicheErethons/Brewery/files/3933386/Brewery-2.0-beta2.zip)

**Comment by Sn0wStorm** [comment]
V2.0 has been released, i would still appreciate if people could send me a timings report and keep their eyes open for bugs :)
