### ISSUE TITLE
barrel 2.0 -- all oak planks are now barrels

### ISSUE THREAD

**Issue by mrcoffee1026** [DieReicheErethons/Brewery#228]
ALL oak planks are now barrels on the server... so entire houses... anything made of oak planks as of version 2.0.  Unplayable with this bug.  Opens as a 9 slot barrel.  Small barrels also no longer work by clicking their signs... although clicking oak plank steps will open a 9 slot barrel.

**Comment by Sn0wStorm** [comment]
Thank you for your Bug report! I have found and fixed the issue and will update the Plugin shortly.

**Comment by Sn0wStorm** [comment]
You can update to the v2.0.1 and it should now work fine!
It was a problem with converting Barrels that were located in large coordinates.
