### ISSUE TITLE
Brewery for Bungeecord

### ISSUE THREAD

**Issue by thebigbadcow222** [DieReicheErethons/Brewery#231]
Would it be possible to make a bungeecord equivalent to brewery. I love this plugin and the only reason I cant use it is because of bungeecord servers.

**Comment by Sn0wStorm** [comment]
So what you want to do is have players be drunk on all your bungeecord servers?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thebigbadcow222** [comment]
yes

**Comment by thebigbadcow222** [comment]
But mainly I can't use it at all and would like to at least use it on the
server.

**Comment by Cerexus** [comment]
Bungeecord support would be really nice!

**Comment by Sn0wStorm** [comment]
Bungeecord support was implemented in 11c7fa13785c81aa8a0a0186ad9fcd2166c083f5
You will need to install Brewery on every Server and put the same mysql database into the config.
