### ISSUE TITLE
"Wood type" appearing on golden rum when aging it in oak barrel.

### ISSUE THREAD

**Issue by TheRayNoodle** [DieReicheErethons/Brewery#233]
[Picture Here](https://cdn.discordapp.com/attachments/611604059161362432/663639020261081098/2020-01-06_02.03.41.png)

I made golden rum and it says "WoodType" in the lore. 14 sugar, distilled twice, aged for a bit and this is what popped up.

**Comment by MrRayhonda** [comment]
not a huge issue actually since it's only while in barrel and aging. Once removed it's not shown.

**Comment by Sn0wStorm** [comment]
If it is green you are using the right wood type. So this is intended to show when in a barrel
