### ISSUE TITLE
Custom Recipe issue...

### ISSUE THREAD

**Issue by CloneCluke** [DieReicheErethons/Brewery#234]
I've worked with Brewery for many years now, though I've come across an issue I have in the past, and I can't recall if I found a workaround, or if one even exists. I have a few recipes that use other brewery recipes, such as using a Rum and a coke to make a rum and coke. However, it uses up the glass bottle as well. Is there a work around, or a way to fix that?

**Comment by Sn0wStorm** [comment]
There is no workaround for that, however that is something that could be fixed

**Comment by Sn0wStorm** [comment]
#259

**Comment by Sn0wStorm** [comment]
Implemented in v2.1.1
