### ISSUE TITLE
Clicking in inventory resets distill runs

### ISSUE THREAD

**Issue by Justinclewis94** [DieReicheErethons/Brewery#236]
This isn't a huge problem, but it is a minor inconvenience.  I've notice that if I'm watching a potion distill in the brewing stand, clicking on anything in my inventory will reset the distill process.

**Comment by Sn0wStorm** [comment]
This is an issue with how we have to change the Brewing stand. It is safer/easier to just reset the distill process every time, than to catch all the bugs and problems that clicking in unexpected places could lead to
