### ISSUE TITLE
Any way to target player with ServerCommands?

### ISSUE THREAD

**Issue by jamesipod** [DieReicheErethons/Brewery#237]
If I want to give a player a specific item from another plugin, is there a way to target the player that drank the brew when running a ServerCommand via brew? Such as 'mythicmobs item give player item 1' or 'mythicmobs item give [player] item 1'?

**Comment by jamesipod** [comment]
Or similarly, is there a way to make the PlayerCommands bypass permissions needed and run that single command as an Operator?

**Comment by Sn0wStorm** [comment]
Yes in Server commands you can use for player names: %player_name%
So that would be: mythicmobs item give %player_name% item 1

No, there is no way to bypass permissions for PlayerCommands.
