### ISSUE TITLE
Add a new barrel type, made with the MC barrel block?

### ISSUE THREAD

**Issue by Leonardo-Fiori** [DieReicheErethons/Brewery#238]
What about adding support to a new type of big barrel, made with barrel themselves instead of wood?
Look at this pic!
https://i.redd.it/k5d8vzp12uf31.jpg

**Comment by Sn0wStorm** [comment]
That would be a good idea, sadly probably too much work for what its worth, Barrel detection is pretty hardcoded at the moment for the two Barrel types
