### ISSUE TITLE
brew persist is no longer a command

### ISSUE THREAD

**Issue by FracturedDream** [DieReicheErethons/Brewery#239]
When I attempt to make a brew persist it comes back unknown command.  Persist is not listed on any page of /brew help anymore.  I do not see anywhere where this command was removed.  Without the ability to make brews persistent they cannot be sold with chestshops unless I am missing something?

**Comment by Sn0wStorm** [comment]
With the new Version you don't need to make the Brews persistent anymore, as the brew data is now saved on every item.
