### ISSUE TITLE
Quality and Server/Player Commands

### ISSUE THREAD

**Issue by FracturedDream** [DieReicheErethons/Brewery#240]
Is it possible to make server and player commands that only run on a specific quality of a brew?  Similar to how the lore can be changed at different brew qualities?

**Comment by Sn0wStorm** [comment]
No that is not currently possible, but i might add that in the future

**Comment by Sn0wStorm** [comment]
You can now use the Quality with a placeholder %quality% , hope that already helps a bit

**Comment by Sn0wStorm** [comment]
Feature added in v3.0
