### ISSUE TITLE
Enabling set alcohol value at low quality

### ISSUE THREAD

**Issue by 22bansaln** [DieReicheErethons/Brewery#243]
I'm making a 100% alcohol mixture where the recipe needs to be followed perfectly or else you get a low quality brew with 0% alcohol.
For reference, this is the brew.
   

> purealcohol:
      name: Distilled Water/&cRubbing Alcohol
      ingredients:
      - BEACON/7
      - NETHER_STAR/2
      - DIAMOND_BLOCK/64
      cookingtime: 0
      distillruns: 0
      wood: 3
      age: 3
      color: 'FBF8F7'
      difficulty: 10
      alcohol: 100
      lore:
      - ++ Accidentally messed this one up while trying to make vodka.
      - +++ This probably isn't safe for consumption.

I want to make the alcohol level 0 for Distilled Water, and 100 for Rubbing Alcohol. Is that possible?

**Comment by Sn0wStorm** [comment]
If you wouldn't follow the recipe perfectly you would get a ruined potion, wich has just a small amount of alcohol, is that what you are trying to do?

**Comment by 22bansaln** [comment]
yes, exactly that! sorry if i didn't explain it too well

**Comment by Sn0wStorm** [comment]
You could try difficulty: 9, then you would get Distilled Water when you mess up the recipe, with very little alcohol.

Also you always need either 1 or 3 names for the potion, so in your case:
Distilled Water/Distilled Water/&cRubbing Alcohol

**Comment by 22bansaln** [comment]
I see. Around how much alcohol would the distilled water have?

**Comment by 22bansaln** [comment]
The "second tier" of distilled water so to speak

**Comment by Sn0wStorm** [comment]
I don't think anyone could even make the second tier with that high difficulty, it would either be perfect or ruined. But you would have to try i'm not sure really
