### ISSUE TITLE
murky distillate / ruined potions?

### ISSUE THREAD

**Issue by fleaspek** [DieReicheErethons/Brewery#248]
we recently added this plugin to our server, and were excited to try it. it seems that some of the original recipes work perfectly, while others do not work at all. 

the first recipe i had tried was vodka, which requires 10 potatoes in the brewing cauldron for 15 mins. it successfully turns into potatomash but upon trying to distill it, it only ever turns into 'murky distillate'. the same can be said for absinthe as well.

the guide i have been following was from 2016 ( https://forum.maestrea.com/threads/barrels-and-beer-a-complete-guide-to-brewing-with-recipes.948/ ).

thanks!

**Comment by Shedopen** [comment]
I have exactly the same problem

**Comment by ItsAAP** [comment]
I am having the same problem with both distills and barrels

**Comment by DJLost12** [comment]
Confirmed. Same issue. Removed all plugins all 52. 1 by 1. All the way down to only brewery left. Same issue.

**Comment by Sn0wStorm** [comment]
Can you send me a data.yml where you tried to brew a vodka?
It should work with 10 potatoes, then 15 mins cooking (check with clicking the watch on the cauldron) and then in the distiller with glowdust.

**Comment by DJLost12** [comment]
I can when I get off work. 10 potatoes cooking works to give me the
potatomash.  Every time. But distilling that on the brewing stand, every
time turns it into murky distillate. Changed the recipe to require zero
distilled while testing. Got vodka after cooking

**Comment by mohdomari** [comment]
@DJLost12 Did you turn distell option off for all recipes?

**Comment by Sn0wStorm** [comment]
Same as #235

**Comment by DJLost12** [comment]
I wiped the entire config folder with the server offline. Regenerated with server restart. All issues have been resolved.
