### ISSUE TITLE
Recipes are not working

### ISSUE THREAD

**Issue by Shedopen** [DieReicheErethons/Brewery#249]
Every recipe I try to destilate becomes an undefinable destilate. I also used this plugin in August, where everything worked fine, but now I can't brew anything.

**Comment by Sn0wStorm** [comment]
Have you changed anything in the config.yml ? If not you can try to delete the config.yml so it generates a new one.
What does it say when you do " /brew reload " ?

**Comment by Shedopen** [comment]
As you may have seen in the comments of other people on a different (but same) issue, nothing I can do resolves the problem.

**Comment by Sn0wStorm** [comment]
Duplicate to #235
