### ISSUE TITLE
ITEM ID ISSUE

### ISSUE THREAD

**Issue by frile933** [DieReicheErethons/Brewery#251]
Hello, we are currently having issues with the plugin as we try to sell brews via a Villager Shop (Ultimate Economy) and we would need to know the exact item ids for adding the item via a command to the shop. How can this be solved? :)

**Comment by Sn0wStorm** [comment]
I don't know how Villager Shop works, but the Item Ids should be the same as the normal Minecraft Potions, just with a lot of custom nbt data, so every potion is unique at the moment

**Comment by Sn0wStorm** [comment]
Try again with the new update. You can put a seal on the brews with the Brew Sealing Table, and then they should be able to sell with the Shop.
