### ISSUE TITLE
Issues with recepes

### ISSUE THREAD

**Issue by OMVredleader** [DieReicheErethons/Brewery#252]
I'm having an issue with the recipes that are in a server config file, some of the recipes like tequila and whiskey don't seem to work. Whiskey just gives undefinable distillate and tequila won't accept cactus. If someone can point me to the issue so I can go and fix certain recipes that would be great.

(attached is our config)

[Brewery_configs_en_config.zip](https://github.com/DieReicheErethons/Brewery/files/4378924/Brewery_configs_en_config.zip)

**Comment by Sn0wStorm** [comment]
I don't see any issue with your config. You could try to delete the config and let it recreate a new one and try with that one?

**Comment by mcgodbuild** [comment]
having an issue with the absinthe recipe. It says you need 12 grass and the grass is turned correctly into the proper bottle of herbs. But distilling it does not give absinthe.

**Comment by Sn0wStorm** [comment]
Did it work before the 2.1?
Do other recipes work?

**Comment by mcgodbuild** [comment]
other recipes work fine, it just turned the herbs into ruined the moment it does its first distillrun. I added green_absinth to the list. its stronger and takes 2 extra ingredients. It worked fine and turned out the way its intended.

**Comment by mcgodbuild** [comment]
changed absinthe to 15grass and it worked again.
