### ISSUE TITLE
Issue adding custom recipes

### ISSUE THREAD

**Issue by PandaMan420** [DieReicheErethons/Brewery#254]
ive had some luck adding 2 recipes so far but some just wont work right this is one im having issues with 
  Melon_Vodka:
    name: Melon Vodka
    ingredients:
      - Potato/3
      - melon_slice/12
    cookingtime: 10
    distillruns: 2
    color: RED
    difficulty: 3
    alcohol: 69
    lore: +++ &8A strong vodka with heavy melon flavor.

**Comment by Sn0wStorm** [comment]
What is the issue with this one? What does it tell you when you do /brew reload ?
Make sure that all the spaces are correct, they are very important in yml files
