### ISSUE TITLE
Issue Creating Any Recipe

### ISSUE THREAD

**Issue by sterr14** [DieReicheErethons/Brewery#255]
I just added Brewery to my friends and I survival world. we have a few other plugins installed however when we try following in the provided brewing recipes, after putting them through the brewing stand all we are left with is a "Murckey Distillate". I tried doing /br reload and that was successful however the recipes still didn't work after reloading. This goes for all the included recipes.

**Comment by Sn0wStorm** [comment]
This might be the same issue as this? #235 
Remove CivModCore from your Plugins and see if it works. I'm currently trying to fix the problem.
