### ISSUE TITLE
Boiling starts at minute 1 instead of minute 0

### ISSUE THREAD

**Issue by LeeSpork** [DieReicheErethons/Brewery#256]
When you first put the items into the cauldron, right clicking with a clock returns that it has just started boiling. But then after 0 to 1 minutes, it says that it has been boiling for _2 minutes._ As the items have only been in the cauldron for 0 to 1 minutes, this is clearly incorrect; I believe that it should instead say that it has been boiling for 1 minute.

Because of this bug, if you want to boil something for "4 minutes", I find that you're actually better off setting a timer for just under 3 real minutes, not 4.

**Comment by Sn0wStorm** [comment]
I think you're right, it might actually start boiling at minute 1, i'll have a look if i can safely change it to minute 0
