### ISSUE TITLE
Brews inserted into Minecraft barrels via hoppers or droppers/dispencers don't age

### ISSUE THREAD

**Issue by LeeSpork** [DieReicheErethons/Brewery#257]
I was looking to adding some automation to my winery by using hoppers just to make is so I don't have to manually move around an entire double chest of items by hand, but it turns out that brews don't age if a player doesn't open the barrel. After 12 hours of storing the brews in the barrels after inserting them in with hoppers or droppers, they are still just "Grape must" or the same complete brew with an age of 0, not even using the fancy coloured lore text stuff that usually appears when you put it into a barrel.
![image](https://user-images.githubusercontent.com/24984194/78085258-f662e400-7416-11ea-829e-efab63f638c1.png)

**Comment by Sn0wStorm** [comment]
Yes it would be a big performance hit to check for brewables every time a hopper moves something. The MoveItemEvent of Hoppers is already a big performance killer on so many servers, I intentionally didn't want to make it worse.

You will have to open the barrels manually once for the plugin to realise that it has brews in it.
