### ISSUE TITLE
Brewery multiblock barrels are not protected in Towny claims or lockable

### ISSUE THREAD

**Issue by Kwikxilver** [DieReicheErethons/Brewery#258]
Hello! First, thanks for your continued work on this mod. My players love it!

We're having an issue with some players coming into our towns and stealing brews from Brewery's multiblock barrels, which are still accessible even within Towny claims. We have a Lockette-esque plugin called Blocklocker which uses signs to protect inventories and that doesn't do anything either.

Is it possible to change this so barrel inventories respect Towny claims, and perhaps respond to Blocklocker and Lockette-esque sign locks? I'm not sure if it's a bug or intentional design but it would be good to have protection as a configurable option at least.

Happy to provide any additional info or test anything you need, just let me know! Cheers.

**Comment by Sn0wStorm** [comment]
Thank you for reporting that, i don't really know how Towny works tbh, so i might need some help. I will look into it, basically Barrels in a Towny claim should not be able to be opened by Players that don't have access to the claim?

**Comment by yntel** [comment]
Yes. Inventories within a Towny claim should be inaccessible to players not allowed to switch in that claim. [Join the Towny Discord by clicking here](https://discord.gg/tXvrSea) - I know they're always happy to provide support!

**Comment by mcgodbuild** [comment]
Grief prevention plugin (gold shovel) claims it corerctly and sees the barrel as a container when you have set /containertrust. 

The lwc protection mod made by hidendra does not see the mc barrel or either barrels you make as lockable containers if anyone as wondering.

**Comment by Sn0wStorm** [comment]
With LWC can you lock the Sign on the Barrel? Can you then still open the Barrel with the sign locked? If so then thats a new bug

**Comment by mcgodbuild** [comment]
ahhh i did not know it was the sign that needed it. Both the small and the big barrel were lockable with the lwc command on the sign. However removing the sign from the big barrel takes the lock off again even if the barrel is still usable. 

Still that will be very helpfull setting up public areas on the server.
