### ISSUE TITLE
Small barrels destroying any recipe.

### ISSUE THREAD

**Issue by mcgodbuild** [DieReicheErethons/Brewery#264]
Sorry if this is a dupe. Did not see any about the barrels after the latest version.

We just added the 2.1 update to brewery on the server. Placed the small buildable barrels and the big barrels. Default recipe or custom says you need to add to any wood type barrel. Yet in the small barrels the bottle says ruined and in the large barrels it works fine.

Is there a error in the config that blocks the use of the small barrel? Placing the sign on it with barrel says the barrel is created. but the bottles are ruined inside.

current config of recipes we are using. there are no errors popping up with the file so i am pretty sure the recipes are good.

https://hastebin.com/uzinevahip.coffeescript

**Comment by Sn0wStorm** [comment]
Do you have CivModCore installed?
1. Does ist ruin the Potions as well when you take a good one out of the Big barrel and then place it in the small one?
2. And does a ruined potion from a small barrel turn good when you take it out and put it in the big one?

**Comment by mcgodbuild** [comment]
![2020-04-10_15 51 03](https://user-images.githubusercontent.com/63448947/78996817-adf9a380-7b45-11ea-8588-79efa3cda3b7.png)

I dont think we have anything like the civmodcore

It seems to me after some testing that it goes wrong when the bottle is updated the first time. So going from the bottle out of the cauldron to the first stage of the bottle in the barrel. The big barrels just shows wether its the good wood in green or the bad wood in red. It does not go to ruined state as far as i can tell similair to a bottle that is aged to long. 

The good bottle from a big barrel to a small barrel lets it age further, a ruined bottle does not transfer to a good one in the big barrel. We currently have 45 recipes in the config and i have been testing it further. Most of the recipes have duel results so some ruined some not in the small barrels that you make. I have not tested the mc vanilla barrels.

All barrels were freshy placed after the 2.1 update on the 8th of april. Not sure why it randomly updates correctly and why often it does not.  i have currently added the fermented wheat to all 6 small barrels and all 6 big barrels just to see what would happen as its the same ingredient and cooktime of 3 default recipes if i am correct.

**Comment by Sn0wStorm** [comment]
>  i have currently added the fermented wheat to all 6 small barrels and all 6 big barrels just to see what would happen as its the same ingredient and cooktime of 3 default recipes if i am correct.

Did you test it out? What happened?
I'm not sure why small barrels should behave differently.. I'm going to try if it maybe has something to do with Slimefun and ExoticGarden.

Could you please send me your config?

**Comment by mcgodbuild** [comment]
https://hastebin.com/uzinevahip.coffeescript

This is the current one were using. the recipe was working fine on the big barrels. Using mpre of the small barrels produced a weird behaviour. had 2 of each type fully filled up. roughlty 15 to 20% did not get ruined like the others. Would that suggest the difficulty would effect it so much on a low 1 or 2 setting?

**Comment by Sn0wStorm** [comment]
I've tried the same with fermented wheat in small and big barrels.
They all turned out fine, as they should. Tried with your config and Slimefun and Exoticgarden installed.

Could you enable debug: true in the config and then send me what it says when you open a small barrel that ruins the potions?

**Comment by mcgodbuild** [comment]
had to do a complete re-install and no more ruined potions so far. Only the murky stuff and low grade ones. Guess there must have been a corruption in the system. Sorry for all the trouble

**Comment by Sn0wStorm** [comment]
I would still like to know what caused this as maybe it affects other people as well?
Maybe can you tell me which plugins you deleted and now it works?

**Comment by mcgodbuild** [comment]
i did not delete anything. I probably should have been more specific. We re-installed only the brewery plugin 

cause having just the brewery on a small simple free test server did not give any issues. To prevent further issues we did all the config work on a seperate server without any other plugins installed. The config file could then be replaced back to the actual server. It allowed me to have over 45 recipes using vanilla items and 21 coctail recipes requiring the previously made 5star potions set as custom items.

As the barrels no longer cause ruined potions, the debug wont show me anything anymore. I have not used the sf items or exotic garden items in any of the recipes. only vanilla items and all custom items are made within brewery itself. As far as i can tell there is currently no interaction with any other plugin item or double using of the same item. 

Seeing the problem is resolved by coincidence i closed the issue post as theres not much else i can add :) i am sure there are other thinks requiring your attention

**Comment by Sn0wStorm** [comment]
Ok thank you for your explanation :)
