### ISSUE TITLE
Option for minecraft barrels

### ISSUE THREAD

**Issue by ZDragon07** [DieReicheErethons/Brewery#265]
Hi, your plugin is great. Me and my friends really enjoy it.

But I have a small issue. I want to store drinks in minecraft barrels but that makes them age. I was wondering if it was possible for you to make an option in the config file to disable minecraft barrels  as aging barrels.

Thank you for your time!

**Comment by Sn0wStorm** [comment]
Ok thats a good idea, i'll add an option to disable Minecraft Barrels at some point

**Comment by Sn0wStorm** [comment]
What you already can do is use "/brew static" on your drinks and then they will not continue to age in any barrel!

**Comment by ZDragon07** [comment]
Thanks! And yeah, I know that but its difficult when you have 2 double chests full of them. 

May I suggest you make two options in the config file;
1. Disable minecraft barrels as aging barrels
2. Drinks that went in the "Brew Sealing Table" don't count as Brews in MC Barrels. (This will get rid of maxBrewsInMCBarrels when stored)

**Comment by mcgodbuild** [comment]
wont doing the bottles in the brew sealing table stop them from aging in barrels? Or do you want to store before aging?

**Comment by ZDragon07** [comment]
If I understand what you are saying, I think the plugin doesn't work as it's suppose to for me. 

I already had issues with the brewing stand part of the plugin. Putting brews in a brewing stand would always result in making murky distillate (I've already read the post for this issue and tried everything). I fixed this issue by removing the distill option in the config.

Now I'm starting to think that the brew sealing table doesn't work correctly. When I put brews in the sealing table, it gives me back the same brew (without the brackets). The brackets appear after a server restart.

All of this worked fine before I had to wipe out clean the plugins folder due to an unrelated server issue. I even tried to install the plugin alone on a localhost server and it still wasn't working.

I'm running the latest 1.15.2 spigot server.

**Comment by ZDragon07** [comment]
By the way, thanks for the quick update. Very appreciated!

**Comment by Sn0wStorm** [comment]
So the Distiller gives you only Murky Distillate, the Sealing table doesnt work propery but Aging in Barrels works fine?
Could you please give me a list of your plugins?

**Comment by ZDragon07** [comment]
![Screenshot_20200413-075436_Chrome](https://user-images.githubusercontent.com/63492084/79118521-22a62b00-7d5c-11ea-934a-3a234bc19049.jpg)

Yes, the Aging works fine. Like I said, I don't think any of the other plugins are interfering. I tried a spigot server with Brewery alone and it still didn't work.

**Comment by Sn0wStorm** [comment]
I'm running a server with spigot 1.15.2 and installed all your plugins. It works fine, distilling and the sealing table..

Could you please enable debug: true in the config and paste here what it says when a potion is ruined in the distiller, that shouldnt be ruined

**Comment by ZDragon07** [comment]
Weird... Now it works on my localhost server. I'll try it on my main server after resetting the config file.

By the way, how can I add the new option you just implemented?

**Comment by Sn0wStorm** [comment]
Thats weird..

You can wait for the full update
or use this beta: 
[Brewery-2.1.1-beta1.zip](https://github.com/DieReicheErethons/Brewery/files/4469536/Brewery-2.1.1-beta1.zip)

**Comment by ZDragon07** [comment]
Didn't work on my main server. 
[profile-results-2020-04-13_15.10.50.txt](https://github.com/DieReicheErethons/Brewery/files/4469620/profile-results-2020-04-13_15.10.50.txt)
I started debugging before inserting the 15 grass in the cauldron.

Is the beta stable? I'll gladly test it.

**Comment by Sn0wStorm** [comment]
No sorry i meant the debug option in the Brewery config.yml
Then it will print debug messages to the Server Log

The Beta is stable, but doesn't update the config options. So Minecraft Barrel aging will always be disabled with this one

**Comment by ZDragon07** [comment]
There
[latest.log](https://github.com/DieReicheErethons/Brewery/files/4469822/latest.log)

Did you know distilling brews doesn't consume glowstone? Idk if it's suppose to do that but it does it for me.

**Comment by ZDragon07** [comment]
There
[latest.log](https://github.com/DieReicheErethons/Brewery/files/4469846/latest.log)

Did you know distilling brews doesn't consume glowstone? Idk if it's suppose to do that but it does it for me.

**Comment by mcgodbuild** [comment]
glowstone is not consumed for me either and no fuel needs to be added either

**Comment by Sn0wStorm** [comment]
Thats intended, the Glowstone is more like a "filter" for distilling

**Comment by ZDragon07** [comment]
Did you check the debug info?

**Comment by Sn0wStorm** [comment]
Yes nothing seems wrong, except that it just can't find a matching recipe
