### ISSUE TITLE
If you pass out by drinking a brew, the brew won't get turned into a bottle

### ISSUE THREAD

**Issue by LeeSpork** [DieReicheErethons/Brewery#266]
If you drink a brew that causes your alcohol level to go above 100 and the server setting causes you to get kicked from the game due to this, all of the brew's effects (e.g. server commands) will get executed, however when you re join the game, the brew will still be there, even though you drank it.

I'm guessing this can be fixed by delaying when it kicks the player from the game?

**Comment by Sn0wStorm** [comment]
I thought i had already fixed that, which version are you on?

**Comment by LeeSpork** [comment]
Oh whoops, still on v2.0.1 my bad :P
