### ISSUE TITLE
Default config doesn't mention that "%player_name%" can be used in the server commands of brews

### ISSUE THREAD

**Issue by LeeSpork** [DieReicheErethons/Brewery#267]
I wanted to create a brew that used a server command on the player, however nowhere is it noted that it is possible to target the player with a command. I had to read through the code here to find out about the "%player_name%" feature.

**Comment by Sn0wStorm** [comment]
Oh yes i should add that to the config!

**Comment by Sn0wStorm** [comment]
Added
