### ISSUE TITLE
Color coding question

### ISSUE THREAD

**Issue by mcgodbuild** [DieReicheErethons/Brewery#268]
Hi am am working in the config file and i am setting color codes like the info explains is possible. However i am having issues setting a color to certain recipes. The weird part is that only a few recipes are affected while the other ones do not have the issue even though its done the exact same way. Can someone take a look and explain why exactly those color codes are giving these errors?

Console **error** list:
https://mclo.gs/wbCviao

config **after** the changed that stopped the console errors:
https://hastebin.com/kejalocihe.coffeescript

Out of the 45 recipes i currently have in the config file, 6 recipes dont accept &4 in front of the first name and i dont know why. Leaving them out lets t he plugin start without issues.

**Comment by Sn0wStorm** [comment]
This is an annoying strange oddity of yml, you need to put the whole string into ' '
see the Vodka Recipe, the names are put into ' ' so yml knows its a String and not a Number
name: 'Rancid Vodka/&6Golden Vodka/&6Shimmering Golden Vodka'
for your recipe it would be
name: '&4Mezcal/&2Tequila/&6Tequila anejo'

**Comment by mcgodbuild** [comment]
well managed to deal with it by doing the following: 
&4 Mezcal/&2Tequila/&6Tequila_anejo

The extra space makes a difference too appearantly
