### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns

### ISSUE THREAD

**Issue by FrozenBeard** [DieReicheErethons/Brewery#269]
Ahoy from PirateCraft!

Using Paper 1.12.2
I up[dated from Brewery 1.8.2 to 2.1 today as I noticed the 1.12.2 backwards compatibility was added again!
Sadly it spams the console on boot, It looks like its trying to load each chunk for either brew/barrel in async which Paper apparently does not like!

Not sure if this will damage the data for brews and I should backdate?

Could this please be fixed, here is a snippet, it has a lot more of these on boot:

https://gist.github.com/FrozenBeard/b3beb8905d3335188df769430e6bdde4

**Comment by Sn0wStorm** [comment]
Thank you for the Report, this issue doesn't happen on newer versions, which is very strange.

You should definitely keep backups of your Brewery data, but it should'nt corrupt anything, just maybe slow down the Data load times.

I'll try to figure out why this happens on 1.12.2

**Comment by Sn0wStorm** [comment]
Fixed the issue by disabling Async loading for 1.12 and lower. 
Attached is a fixed version, but I'll also release a full update soon.
[Brewery-2.1-hotfix.zip](https://github.com/DieReicheErethons/Brewery/files/4466631/Brewery-2.1-hotfix.zip)

Hope you continue to enjoy Brewery, i've put some effort into making sure it still runs on 1.12 so it really should run fine.

**Comment by Sn0wStorm** [comment]
Implemented in v2.1.1
