### ISSUE TITLE
Milk can’t be put into cauldron for recipes

### ISSUE THREAD

**Issue by minerdeviant** [DieReicheErethons/Brewery#270]
When trying to place milk in cauldron, instead of pouring the player ends up stuck in a infinite drinking animation

**Comment by Sn0wStorm** [comment]
Adding Milk works fine for me without problems. Which Minecraft version are you on?

**Comment by minerdeviant** [comment]
1.15.2 running brewery 2.1

**Comment by Sn0wStorm** [comment]
Works for me on Paper and Spigot. Maybe you have another Plugin that does this?
