### ISSUE TITLE
2.1 - Cant place placeable items into cauldron unless item in offhand/block next to cauldron

### ISSUE THREAD

**Issue by TomLewis** [DieReicheErethons/Brewery#271]
using paper 1.12.2
Brewery 2.1

New bug, placeable items cant be put into cauldrons from the top at all, only from the side if theres a block net to it to place the item, for example grass into a cauldrons needs a block of dirt next to it, to place the item which will then go into the cauldron.

Here is a video, you cant tell but the cauldron no the left im trying to place the grass into and its doing nothing, then I place it on the side of the cauldron on the right and it goes in because of the block of dirt.

Also neither of them can I place it via the top.

its also reported that having something in your offhand allows you to place the items.

https://youtu.be/5AWosj-F7A4

**Comment by Sn0wStorm** [comment]
Sadly this has always been a problem, since 1.9
If a placeable item can not be placed on the Cauldron the server completely ignores it, doesn't even fire the event for it. This doesn't apply to many items though, mainly grass and i think mushrooms.
The workaround i implemented back then as you noticed is catching the event for the off-hand, so just holding an item in the off-hand works.

**Comment by FrozenBeard** [comment]
Very weird, the user that reported this to me said they have only had this issue since this latest update.
Any idea why?

**Comment by Sn0wStorm** [comment]
The only thing i can think of is that maybe another plugin or a setting changes the way right clicking is handled?
But this issue definitely existed in older versions, ie. https://github.com/DieReicheErethons/Brewery/issues/130

**Comment by FrozenBeard** [comment]
Bump.

**Comment by Sn0wStorm** [comment]
Are you still running a 1.12 Server? Is this still an issue? As i said, i remember this always being an issue and not something that's easy to fix.

**Comment by TomLewis** [comment]
@Sn0wStorm yes I am! I updated recently hoping it would be fixed, its weird as it never did it before whatever update I was on about before!
