### ISSUE TITLE
Adding barrel creator command

### ISSUE THREAD

**Issue by ZDragon07** [DieReicheErethons/Brewery#273]
Like I said in my previous post, your plugin is great and I love it. But lets face it, a giant barrel with a sign on it that says "Barrel" isn't very pleasing for the eyes.

I thought it would be great to implement a command to create barrels without any signs.

Maybe add the command **/brew barrel add** to create a barrel and **/brew barrel remove** to delete a barrel.

I know it would be more work because of plugins like WorldGuard and "land claim" plugins, but I think it would be great.

This could be working aside the sign system.

**Comment by Sn0wStorm** [comment]
You can remove the Sign after creating the Barrel (on the big barrel) -> no signs on the Barrel.
The command would be easy as well, but more to remember for players

**Comment by ZDragon07** [comment]
Okay, thanks!

**Comment by mcgodbuild** [comment]
so removing the sign lets the setup still be recognised as a barrel? that would open up a lot more design options

**Comment by Sn0wStorm** [comment]
Yes for the big barrel the Fence is the important Block, while for the Small Barrels the Sign is the important Block. So the sign can be removed on the Big Barrel.

Is there a need to be able to remove the Sign from the small barrel? if you want a barrel without a sign, you could use the Big Barrel or the Minecraft Barrel.
