### ISSUE TITLE
maby intended barrel creation options

### ISSUE THREAD

**Issue by mcgodbuild** [DieReicheErethons/Brewery#274]
I think the picture says enough. Few players found this one out.

![2020-04-13_17 03 15](https://user-images.githubusercontent.com/63448947/79131655-388e0d00-7da9-11ea-9185-47cc5c3dc3ea.png)

It seems taht as long as the bottom stairs are facing up, the direction or the top stairs placing does not matter. Is this intended behaviour?

**Comment by Sn0wStorm** [comment]
Jup if you want your barrel to be ugly you can do that as long as you use the correct blocks 🤷‍♂️
