### ISSUE TITLE
Issue adding recipies

### ISSUE THREAD

**Issue by Cjk1231** [DieReicheErethons/Brewery#275]
Hello, I have been trying to add custom recipes and by copy and pasting other recipes then changing them up to fit a new one. I have also tried adding one from scrath by typing it all out but every time I add one the plugin stops working. I am not sure if i am adding a extra space but i would love some help with figuring out how to add custom recipies. Thank you.

**Comment by mcgodbuild** [comment]
please provide the config file containing the recipes. I suggest using https://hastebin.com/ or something similair as it allows the layout better then copy paste it in a reply and one can see it online without the need to download.

**Comment by Cjk1231** [comment]
https://hastebin.com/yoximurewi.coffeescript

**Comment by mcgodbuild** [comment]
What did you add? Cause i dont see any new recipes, just the default ones

**Comment by Cjk1231** [comment]
The hot chocolate at the bottom, it was in the suggested part so i copied it over to test it

**Comment by mcgodbuild** [comment]
Take a good look at the spacing. The name does not have enough spacing. Same with all the other parts of the recipe. A easy way to fix this is to select the space in front of the default recipe above it and replace the space of the new recipe with it.

https://hastebin.com/ecavinudex.coffeescript

i added comments and an empty example.

**Comment by Cjk1231** [comment]
thank you, also is it possible to have an easy way of telling if I have too many spaces or too little just by eyeballing it?

**Comment by mcgodbuild** [comment]
Well if you hold your mouse next to the first letter of the default recipes name and the incredients list, when scrolling down without moving the mouse, all the letters of the top name should match and all the ingredients and there names need to match in a similair way. Basicly every name, ingridient, cooking time, it all nees to be on the same spot in the config

Even if your server is giving an error that it cant read the config file, just above it in all that text usually says why or at what point/row the issue is. Its very helpfull finding recipe errors for example.

**Comment by mcgodbuild** [comment]
Just noticed something funny and easier. Heck the fact i did not even know this before makes my mind blown hahaha.

--whiskey:
----name: Unsightly Whiskey/Whiskey/Scotch Whiskey
----ingredients:
------- Wheat/10
----cookingtime: 10
----distillruns: 2
----distilltime: 50
----wood: 4

its 2 spaces for the recipe names, 4 spaces for the bottle name and lines like ingredients, cooking time, stuff like that. Its 6 spaces for the actual ingredient parts.

**Comment by Sn0wStorm** [comment]
You can download Sublime Text or Notepad++ and they make it really obvious if spaces are wrong and also any other mistakes will be marked red.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
