### ISSUE TITLE
Adding recipe causes plugin trouble

### ISSUE THREAD

**Issue by LazyCrazyPirate** [DieReicheErethons/Brewery#280]
Hi! I started creating my own recipes step by step with your video tutorial and I created two working recipes which I could succesfully make. Unfortunatelly something gone wrong when I did the third one and the plugin totally stopped working. I don't know what gone wrong, I did everything the same way as at previous two recipes. I tried to modify the third recipe but the problem was still in the plugin. Can You check the code for me or give me advices how to do it well? I am adding the file config.yml which is modified by myself. I am using Sublime Text as a code editor.
[help.txt](https://github.com/DieReicheErethons/Brewery/files/4495907/help.txt)

**Comment by Sn0wStorm** [comment]
Your config looks really messed up?
![Bildschirmfoto 2020-04-18 um 12 48 42](https://user-images.githubusercontent.com/4077108/79635766-18789800-8173-11ea-9ffd-32e6d4e0d229.png)
This is what it should look like
![Bildschirmfoto 2020-04-18 um 12 50 38](https://user-images.githubusercontent.com/4077108/79635780-3b0ab100-8173-11ea-9a3b-a8988d143fdc.png)

The recipes you added look ok though

**Comment by LazyCrazyPirate** [comment]
Thanks Bro!
Everything is working now. My mistake was that at the beginning I copied text to default Windows notepad and it ruined the continuousness of the document with random spaces. I fixed this problem and now everything work correctly. Really thanks for your help.
