### ISSUE TITLE
could not read config.yml

### ISSUE THREAD

**Issue by Menschlich1** [DieReicheErethons/Brewery#281]
[22:32:43 INFO]: [Brewery] ERROR: Could not read file config.yml, please make sure the file is in valid yml format (correct spaces etc.)

I am using the standard config file.
It does work with the same plugins on a local server.

**Comment by Menschlich1** [comment]
I got it to work but after a restart it gave the same error again

**Comment by Sn0wStorm** [comment]
Which minecraft version are you on? And which language config are you using?

**Comment by Menschlich1** [comment]
1.15.2
When i installed it first it did not work.
After copying the config from configs/de
it worked fine till the server restarted

**Comment by Menschlich1** [comment]
The config file exists and looks the exact same like on my local server

**Comment by Sn0wStorm** [comment]
Komisch, bei mir geht die "de" config ohne Probleme unter 1.15.2
Du solltest mal sicherstellen dass dein Server mit UTF-8 startet.
Was passiert wenn du bei einem anderen Plugin in der config etwas mit ä und ö schreibst?

**Comment by Menschlich1** [comment]
Wir sehe ich ob der mit utf 8 startet?

**Comment by Menschlich1** [comment]
Ich hab das plugin nochmal komplett neu installiert und es scheint zu funktionieren ich starte den mal neu.
Ich denke das mit einem anderen plugin zutun das outdated war, der ist jetzt nicht mehr drauf.

**Comment by Menschlich1** [comment]
Ich habe das Problem gefunden.
Bei Pterodactyl kann man 1. die Startoptionen nicht ändern, 2. wird die config wenn man die Sprache auf Deutsch stellt nicht gespeichert (keine ahnung warum sie ist dann einfach leer)
Jedenfalls scheint es jetzt auf englisch zu funktionieren.

**Comment by Sn0wStorm** [comment]
Ok also scheint es jetzt zu gehen? Wenn die deutsche config immer noch nicht geht, vielleicht mal den server herunterfahren, deutsche config drauf und dann wieder hochfahren

**Comment by Menschlich1** [comment]
Es funktioniert aber der Server löscht aus irgendeinen Grund den inhalt der config wenn sie auf deutsch gestellt ist.

**Comment by Menschlich1** [comment]
Ich eröffne nochmal da ich noch hinzufügen möchte dass nach jedem neustart die config "geleert" wird und sie somit immer wieder gelöscht werden muss.

**Comment by Sn0wStorm** [comment]
Passiert das immer noch? Wenn ja einfach noch mal eröffnen
