### ISSUE TITLE
Whiskey makes beer

### ISSUE THREAD

**Issue by thebiglarry99** [DieReicheErethons/Brewery#282]
Everytime i try to make whiskey, it turns into beer(fermented wheat before distilling or aging. If i distill the fermented wheat, it turns into murky distillate after the first run. If I age without distilling, it makes beer. Do you have a more specific recipe than just 1 wheat per min? Am I making a mistake?
Any help is greatly appreciated!

**Comment by mcgodbuild** [comment]
please add your config file using the free https://hastebin.com/ so we can see what is going on with the recipes.

**Comment by Kbryst** [comment]
Sounds like you have the default config file.

The "difficulty" of the brew will determine which one you get. Some might argue that its the placement in the file itself too. Doesn't matter. The issue you are having is that your recipes are too similar. If you don't want to accidentally brew the wrong item pump the difficulty up and change the ingredients more.
