### ISSUE TITLE
Adding new opportunity

### ISSUE THREAD

**Issue by beattebalo** [DieReicheErethons/Brewery#283]
Hello, working with your plugin, I came across the idea of ​​adding the ability to produce in the boiler not only alcohol, but also cheeses and soups. It would be possible to add the ability to add an item ID to the config that will interact with the boiler and the item ID, which will be issued to the inventory. What do you think?

**Comment by Sn0wStorm** [comment]
You could simply create a new recipe, with 0 alcohol that results in cheese or soup and then change the texture with Custom Model Data?

**Comment by beattebalo** [comment]
Collect cheese / soup with a bottle? This is strange, especially after eating the bottle remains. So why not add variation? Whoever wants to keep the original ones.

**Comment by Sn0wStorm** [comment]
Currently all the logic and code is only run on Bottles. This is especially good for performance, as the plugin is basically deactivated for any other item. So opening up to all other items would be a big change in code and also might have some performance impact. 
Seeing as there are lots of other plugins that allow you to add custom items, that would seem like the best solution, maybe even adding integration with them to allow custom items as output.

**Comment by beattebalo** [comment]
You can try to make an addon or a full-fledged plugin to the brewery, where you can make food, give it through the config the number of restored food points, cooking food through structures (like the same barrels from the brewery). What do you think?

**Comment by Sn0wStorm** [comment]
Yes that would be a whole different plugin, not much to do with Brewery
