### ISSUE TITLE
Large Barrels made prior to plugin upgrade not recognized. 

### ISSUE THREAD

**Issue by vapecloudbear** [DieReicheErethons/Brewery#284]
Player can build large barrels and they work after the upgrade from the old version prior to 2.0 to the latest. But large barrels made on the old version are no longer recognized as barrels after the upgrade.

**Comment by Sn0wStorm** [comment]
Did it give you any errors when it converted the Barrels over to v2 ?
you can remove the data.yml and the worlddata.yml and load the data.yml from a backup before v2, and see if it then converts them properly

**Comment by mcgodbuild** [comment]
Would it not just be a case of replacing the sign saying brewery?

**Comment by Sn0wStorm** [comment]
@mcgodbuild yes but then it would have its inventory cleared, but otherwise thats the easiest solution
