### ISSUE TITLE
Adding Custom Brews as an Ingredient

### ISSUE THREAD

**Issue by Cjk1231** [DieReicheErethons/Brewery#286]
Hi, I am trying to add the vanilla potions as make able brews and I cant make it so the custom Awkward potion I made as an ingredient. The config updates with no problem but I still can't but the custom base potion as a ingredient. The custom config is in the hastebin link. Thank you so much for helping and I love the plugin

https://hastebin.com/ebezozupic.coffeescript

**Comment by mcgodbuild** [comment]
night_vision:
    name: Dusk Vision/Night Vision/Eclipse Vision
    ingredients:
      - Golden_Carrot/3
      - Brewery:Awkward Potion/1

I dont see it in the materials list. If its not under 

cauldron:

 # -- One Ingredient: --

Or

 # -- Multiple Ingredients: --

The cauldron wont regognise it and you may get the error missing ingredient

**Comment by Cjk1231** [comment]
So now I can put the awkward potion in but even if I do the brew correctly I always get golden carrot water. I am not sure if i did something wrong or if i forgot to add something.

https://hastebin.com/ayixogimap.coffeescript

**Comment by mcgodbuild** [comment]
your probably getting that as its only seeing your 1 carrot need. Try adding it under the multiple ingredients part 

night_vision:
    name: can be what ever you want
    ingredients:
      - Golden_Carrot
      - Brewery:Awkward Potion

This way the cauldron knows if you add the 2 together its something different and the recipe will determen the amount.

**Comment by Cjk1231** [comment]
Are saying to add the final brew into it or the golden carrot one into multiple ingredients part?

**Comment by mcgodbuild** [comment]
multiple ingredients part. that should let the cauldron know its and additional recipe option

**Comment by Cjk1231** [comment]
It just gives me a ruined potion. I copy and pasted the example you did and put it into the multiple ingredients part. I did everything correctly that the potion required but it doesn't seem to work.

**Comment by mcgodbuild** [comment]
I'll load your cconfig up on a test area later today and see what i can find for you

**Comment by Cjk1231** [comment]
Here is my current config. Hastebin wasn't saving so I used Hatebin

**Comment by Cjk1231** [comment]
https://hatebin.com/nplikpvdez

**Comment by mcgodbuild** [comment]
Let me start by  apologizing for not realizing you were actually making your own awkward potion in Brewery. That does change things a bit. 

When your using previously created brews from brewery they are infact custom items by them selfs. You would need to add it to the custom item section of the config.  As shown in the screens i was able to make the brews on the test world.

![2020-05-02_10 12 14](https://user-images.githubusercontent.com/63448947/80859261-82a73780-8c5f-11ea-9060-3867b752e666.png)
![2020-05-02_10 25 26](https://user-images.githubusercontent.com/63448947/80859268-98b4f800-8c5f-11ea-8b0f-0be60f7a940d.png)

To prevent any wrongs in copying the texts, i've added the changes already to the config. Do look at the changes. https://hatebin.com/uqbiggzfdo

**Comment by Cjk1231** [comment]
Thank you for the help. It works now and I added another one without problem. I really appreciate it.
