### ISSUE TITLE
Dupe Distilling Bug

### ISSUE THREAD

**Issue by FracturedDream** [DieReicheErethons/Brewery#290]
If a brew is put in a brewing stand to distill, then while the it is distilling, is replaced with another brew (does not matter what the replacement is, trash brews work just fine) via hoppers (so the replacement is immediate) it does not interrupt the brewing process and the distilled brew will be the result as if the original brew was properly distilled.

Example:
Berry Brew will give Sweet Berry Crush.
While it was distilling it was replaced with Muddy Brew which should yield indefinite distillate
It instead gave the Sweet Berry Crush and the player still has the original Berry Brews to repeat the process.
![DistillBug1](https://user-images.githubusercontent.com/58870131/80918559-a6d44880-8d33-11ea-95ce-0fc2f047affe.png)
![DistillBug2](https://user-images.githubusercontent.com/58870131/80918561-a76cdf00-8d33-11ea-9458-b4720abe092b.png)
![DistillBug3](https://user-images.githubusercontent.com/58870131/80918563-a8057580-8d33-11ea-989a-286efb3d5c20.png)

**Comment by mcgodbuild** [comment]
what was the muddy Brew intended to be? MAy be an update bugg thing

**Comment by FracturedDream** [comment]
We tested it by brewing with just 1 item (sugar in this case).  Fermented 1 piece of sugar, bottled it and could use that brew to replace others as seen above.

**Comment by FracturedDream** [comment]
Update: The Muddy brew is just what they got when they added something to the cauldron and immediately bottled it so they could test the bug.  It was just one item added to a cauldron and should not have ever resulted in a brew.

**Comment by Sn0wStorm** [comment]
Thank you for your detailed description. I'll try to figure out why this is happening!

**Comment by Sn0wStorm** [comment]
Sorry i thought i had replied to this. I could not reproduce this issue, anything i tried, even with hoppers and stuff i could not make it happen.

Try in v3.0, as some code with the Distiller has been changed.
