### ISSUE TITLE
Saturation effect is instant instead of continous

### ISSUE THREAD

**Issue by InflamedSebi** [DieReicheErethons/Brewery#292]
No matter how I try:
`SATURATION/1/300`
`SATURATION/300`
They are both instant instead of giving saturation for 5 minutes.
Is there a way to make it longer?

I tried to compensate this by giving players a negative Hunger effect:
`- HUNGER/-10/300`
which ends up as ordinary Hunger V effect.
Is there a way to apply negative levels of an effect?

**Comment by Sn0wStorm** [comment]
We only support the Potion Effects of here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
And sadly no negative effects, is that even possible?

**Comment by InflamedSebi** [comment]
Wiki states that the Hunger page: "Negative levels decrease food exhaustion, although they do not increase saturation or the hunger bar." /effect in Minecraft does not allow negative levels, but they must have gathered that piece of information somehow.

yeah spigot must have screwed saturation up, since "/effect give @p minecraft:saturation 300" does work. It is 300 ticks and not seconds, but still fine ...

Is there a way to workaround the `SATURATION/1/300-1200` effect? For example by having quality specific commands to run?:
```
    servercommands:
      - + effect give %player_name% minecraft:saturation 300
      - ++ effect give %player_name% minecraft:saturation 750
      - +++ effect give %player_name% minecraft:saturation 1200
    servercommands:
      - effect give %player_name% minecraft:saturation (300+450*%quality%)
```
