### ISSUE TITLE
Help with customModelData

### ISSUE THREAD

**Issue by Feefkroete** [DieReicheErethons/Brewery#293]
Hi everyone
I was kinda struggeling with the custom Model Data...
Could anyone explain, how it has to be done?
Thanks in advance^^
Matthi

**Comment by Sn0wStorm** [comment]
Maybe look at an example Pack, this one changes brews with Custom Model Data 557 to a Beer Glass

https://zebradrive.de/index.php/s/hLuDo3sdFUmo6Od

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Feefkroete** [comment]
Danke dir^^
