### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jahsduje** [DieReicheErethons/Brewery#294]
I am having trouble figuring out the times that say Very Long, Long, and Short . Also the ingredients that call for lots of something, potatoes and mushrooms, or a sixth of a stack of potatoes. I looked around, but I can't find anything specific.

**Comment by Feefkroete** [comment]
This is that you aren't just Looking at the recipies but trying out stuff yourself…
If you want exact recipies you need to download the plugin and look inside the config.yml
