### ISSUE TITLE
Issue using ingredients in cauldron

### ISSUE THREAD

**Issue by oguh43** [DieReicheErethons/Brewery#296]
Hi, i have a custom ingredient:
` 
  bilinky:
    name: Vyvarené bylinky
    ingredients:
      - blue_orchid
      - poppy
      - cornflower
    color: '00ccff'
`
How can i use the produced bottle in a recipe like so:
`
  Tatratea:
    name: Tatratea 17%/Tatratea 52%/Tatratea 72%
    ingredients:
        - wither_rose/10
        - oak_sappling/4
        - Brewery:bilinky
    cookingtime: 15
    color: BLACK
    difficulty: 4
    alcohol: 72
    wood: 0
    age: 1
    lore: A traditional Slovak drink.
    distillruns: 3
    distilltime: 600
`
I can make the bilinky bottle but cant place it into thr cauldron to make Tatratea according to the example this should be possible: 
`
  ex:
    name: Bad Example/Example/Good Example
    ingredients:
      - Diamond/1
      - Spruce_Planks/8
      - Bedrock/1
      - Brewery:Wheatbeer/2

      - ex-item/4 #+ what is this please?
`

**Comment by oguh43** [comment]
Sorry for the weird formatting, i tried my best.

**Comment by Feefkroete** [comment]
Which Editor are you using?
Because I used Notepad ++ and had no issues adding my Potions after the "Brewery:" by using tab...
But that's the only thing I know you could do...

**Comment by oguh43** [comment]
Resolved after looking deeper into the config
