### ISSUE TITLE
Error in Placeholder

### ISSUE THREAD

**Issue by C4BR3R4** [DieReicheErethons/Brewery#298]
Error in variable data

Wood Type
[https://i.postimg.cc/PrTfbXjR/captura-2020-05-13-at-20-36-27.png](url)

Brew Sealing Table
[https://i.postimg.cc/vZmQj0D7/captura-2020-05-13-at-20-37-12.png](url)

**Comment by Sn0wStorm** [comment]
Delete your language folder in the Brewery Folder to see if it regenerates them
