### ISSUE TITLE
Russian localisation

### ISSUE THREAD

**Issue by NitroxBro** [DieReicheErethons/Brewery#301]
Hi guys! It can be hard to understand for any who cant understand russian, but we have 3 count types in our language. For example, in english we have year/years, but in russian we have год/года/лет. It depends only on the number of it self. For example: one year  - один год, but two years - два года and so on. Next count type is "лет". For example: 5 years - пять лет. 
So, how can i add new count type in plugin? Im speaking about aging in the barrels, in russian language we need this third count type, otherwise there will be a lot of lore errors.

**Comment by Sn0wStorm** [comment]
Currently there is no way to do this. Would this be easy to implement? Maybe just add one more case for 5 years?
