### ISSUE TITLE
Brew Create + name bug

### ISSUE THREAD

**Issue by Kbryst** [DieReicheErethons/Brewery#305]
This one wrecked my day.

Paper spigot 1.15.2
Brewery 2.1.1
**This has been an issue for me for at least Feb and we only just discovered what it is.

So when we create new brews we use `/brew create` to test and make sure it works. We often get "No recipe with {name} found". 

Using the recipe below running /brew create d - gives the error. 
Running /brew create a - gives the drink
Running /brew create b - gives the drink
Running /brew create c - gives the drink

So pretty much any one word name for the "name:" will work for brew create, but not the actual drink ID name. 

  d:
    name: a/b/c
    ingredients:
      - apple/5
      - Brewery:Wine/2
    cookingtime: 17
    distillruns: 8
    distilltime: 90
    wood: 0
    age: 0
    color: '8D0E46'
    difficulty: 10
    alcohol: 5
    lore:
      - '&7'
      - '&7Drink me Daddy!'

We also had issues with putting color codes in brew names, but after this testing I feel that error only came up because the command would have changed to "/brew create &ea" from "/brew create a". (Because of its color code?)   I did not test this part. I figured it would be better to test after this first issue is addressed, but I did want to note it here.

**Comment by Sn0wStorm** [comment]
The id, in your case `d` is not used for anything. It is only because yml needs it to be there.

`/brew create` uses the Name of the Brew, which in your case is `b` and nothing else. That `a` and `c` (the quality names) also work is simply and only for convenience .

**Comment by Kbryst** [comment]
Yes... you explained the issue in a different way.

/brew create d
^That SHOULD be how the command works. A, B, and C, should not be what brew create pulls from.

**Comment by Sn0wStorm** [comment]
The command always worked by pulling the name from B for years now, so this is intended behavior

**Comment by Kbryst** [comment]
No its not intended. Its something that was never fixed.

**Comment by Sn0wStorm** [comment]
From v3.0 its pulling the names from any a, b, c, d
