### ISSUE TITLE
About Green Absinthe

### ISSUE THREAD

**Issue by imsalze** [DieReicheErethons/Brewery#311]
Hi, I really like this mod. But there's a green absinthe in the brewing recipe.The ingredients are Lots of Grass Another Greenish thing. I've tried and failed many times to figure out what that green thing is. Can you tell me? Thank you.

**Comment by NitroxBro** [comment]
Hi! Actually you can look up for it in the config.yml. If you dont want to do it, well, here you are
ingredients:
      - Grass/17
      - Poisonous_Potato/2
