### ISSUE TITLE
1.16 update?

### ISSUE THREAD

**Issue by mcgodbuild** [DieReicheErethons/Brewery#312]
Less then an issue and more a question. Will you be updating the brewery plugin for 1.16? The server is really enjoying the plugin, but were currently making a list of plugins we wanna wait on to update and those that are not gonna.

**Comment by ColonelKai** [comment]
I have been using the plugin in 1.16, it works like a charm, i haven't encountered any bugs yet.

**Comment by mcgodbuild** [comment]
> 
> 
> I have been using the plugin in 1.16, it works like a charm, i haven't encountered any bugs yet.

thats amazing, so it accepts the 1.16 even if its still a 1.15 plugin? How about the new items?

**Comment by ColonelKai** [comment]
> > I have been using the plugin in 1.16, it works like a charm, i haven't encountered any bugs yet.
> 
> thats amazing, so it accepts the 1.16 even if its still a 1.15 plugin? How about the new items?

Yes, i just used the same JAR file. And new items don't have any functionality in the plugin so they don't cause a problem.
