### ISSUE TITLE
Error when trying to load plugin 2.0 or higher on mc 1.7.10 couldron 

### ISSUE THREAD

**Issue by Dekad300** [DieReicheErethons/Brewery#313]
- **When trying to enable version 2.1.1**

`[13:26:03 INFO]: [Brewery] Enabling Brewery v2.1.1                                                                                [13:26:03 ERROR]: Error occurred while enabling Brewery v2.1.1 (Is it up to date?)                                                java.lang.NoClassDefFoundError: com/dre/brewery/api/events/ConfigLoadEvent                                                                at com.dre.brewery.P.onEnable(P.java:84) ~[?:?]                                                                                   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                                    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                             at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                          at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                       at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]                          at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]                          at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]                          at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]                             at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]                                   at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]                                                                     Caused by: java.lang.ClassNotFoundException: Failed to remap class com.dre.brewery.api.events.ConfigLoadEvent                             at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 ... 12 more                                                                                                               Caused by: java.lang.RuntimeException                                                                                                     at org.objectweb.asm.MethodVisitor.visitTypeAnnotation(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                 at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                     at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]                                 at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]                                 at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 ... 12 more `

- **When trying to load version 2.0**

`[13:29:09 INFO]: [Brewery] Enabling Brewery v2.0                                                                                  [13:29:09 ERROR]: Error occurred while enabling Brewery v2.0 (Is it up to date?)                                                  java.lang.NoClassDefFoundError: com/dre/brewery/api/events/ConfigLoadEvent                                                                at com.dre.brewery.P.onEnable(P.java:82) ~[?:?]                                                                                   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                                    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                             at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                          at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                       at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]                          at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]                          at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]                          at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]                             at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]                                   at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]                                                                     Caused by: java.lang.ClassNotFoundException: Failed to remap class com.dre.brewery.api.events.ConfigLoadEvent                             at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 ... 12 more                                                                                                               Caused by: java.lang.RuntimeException                                                                                                     at org.objectweb.asm.MethodVisitor.visitTypeAnnotation(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                 at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                     at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]                                                at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]                                 at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]                                 at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]                                                                                                                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]                                                                 ... 12 more                           `

**Comment by Sn0wStorm** [comment]
Sorry i don't know what this error could be. Does it work with CraftBukkit or Spigot?
