### ISSUE TITLE
Residence support?

### ISSUE THREAD

**Issue by bobhenl** [DieReicheErethons/Brewery#316]
How, could you add way to block opening barrels in residences? I saw it in upcoming features, just asking when it could be?

**Comment by Volgeop** [comment]
Nothing?

**Comment by Volgeop** [comment]
@Sn0wStorm

**Comment by Sn0wStorm** [comment]
Could you test if this version works with Residence? Players should not be able to open Barrels in protected areas.

[Brewery-2.1.2-DEV.zip](https://github.com/DieReicheErethons/Brewery/files/5483934/Brewery-2.1.2-DEV.zip)

**Comment by Sn0wStorm** [comment]
Use v3.0 and set `useVirtualChestPerms: true` to true
