### ISSUE TITLE
Remove mention on bottle

### ISSUE THREAD

**Issue by Thefirstalpha** [DieReicheErethons/Brewery#317]
Helo
Is there a way to remove the mention "Alc XXml" on alcoholic Potions ? It appear after every distilling.
![Sans titre2](https://user-images.githubusercontent.com/25564305/88491532-a13d7600-cfa3-11ea-878f-0edd69153279.png)
![Sans titre](https://user-images.githubusercontent.com/25564305/88491533-a1d60c80-cfa3-11ea-803f-7376f2412546.png)
Because it's become realy longer, I've already put alwaysShowAlc to false in the config file

Thanks

**Comment by Sn0wStorm** [comment]
Fixed, same as #328
