### ISSUE TITLE
Error On Startup

### ISSUE THREAD

**Issue by ellaira-ash** [DieReicheErethons/Brewery#319]
Paper: 1.16.1 (Build #130)
Brewery: 2.1.1

When I start up the server, I get this error. I haven't run into any issues so far in using the plugin.
https://pastebin.com/6UsKGYF3

**Comment by Sn0wStorm** [comment]
Is this Error still happening?

Looks like it is just an issue with the Updater Website where Brewery checks for updates. Nothing to worry about
