### ISSUE TITLE
Bottle Stack drinking error

### ISSUE THREAD

**Issue by JaHollYT** [DieReicheErethons/Brewery#320]
Hey, if you have for example 5 beer bottles stacked and you drink one the others also disapper.
Hope you can fix :)

**Comment by Sn0wStorm** [comment]
How can you even stack Bottles? I don't think i added support for stacked bottles so thats why it doesn't work

**Comment by Sn0wStorm** [comment]
Sadly this is a problem with how effects on potions are handled. We need to remove the whole stack on drinking to stop any unwanted effects from applying.
