### ISSUE TITLE
Formatting codes Bug about 'Define custom items'

### ISSUE THREAD

**Issue by Mr-Mint** [DieReicheErethons/Brewery#321]
Example:

  rum:
    matchAny: true
    name:
      - §f§6RUM

If I use a apple name ' §f§6RUM' ,it couldn't be recognized as a ingredient.
But if I use a apple name ' §6RUM' ,it could be recognized as a ingredient.
So I think the formatting code '§f' would be ignored when you define a custom item.

And the drinks of Brewery would have a '§f' in front of its name....

Hope it could be fixed, thank you

**Comment by Sn0wStorm** [comment]
You can use Brewery Drinks by using Brewery:Rum, you don't have to define a custom item
