### ISSUE TITLE
Storing alcohol in chests ruins it

### ISSUE THREAD

**Issue by ZeeRaider** [DieReicheErethons/Brewery#322]
My players have been trying to store alcohol, when they place it into chests, it ruins(treats it like a barrel).
Is this a known issue?

Running Spigot 1.16.1

**Comment by Sn0wStorm** [comment]
I have not heard of this before, is this everywhere on the world?

If this is still an issue, remove all the potions from barrels, stop the server and delete worlddata.yml in the Brewery folder. Then start the server again. This will delete all the Barrel inventories in case there is a bugged barrel somewhere.

**Comment by Sn0wStorm** [comment]
Before you try this, make sure you are on at least 2.0.1 or newer of Brewery, as this bug has been fixed in 2.0.1
