### ISSUE TITLE
Pistons are stopped from extending if used in the same chunk as a barrel

### ISSUE THREAD

**Issue by TomLewis** [DieReicheErethons/Brewery#323]
A very obscure bug I figured out (After wondering why the hell pistons were not working)

If you have a piston machine in the same chunk you have a barrel, they will not extend.
https://github.com/PirateCraft/dev/issues/18

**Comment by Sn0wStorm** [comment]
Which Server Version are you running?  
Is this with our custom Barrels or the Minecraft Barrels?

**Comment by Sn0wStorm** [comment]
This may fix it 0e02355cca7db7a4d4a5728f9fa6380a663d4a4f

**Comment by TomLewis** [comment]
1.12.2 Paper.

This is with your custom barrels as barrels came in 1.13.

I will ask my community if the update fixed it.

**Comment by Sn0wStorm** [comment]
Please reopen if this is still an issue
