### ISSUE TITLE
Alcohol content lore is not removed properly.

### ISSUE THREAD

**Issue by Uboaaaaa** [DieReicheErethons/Brewery#328]
After each distillation phase, a new alcohol content lore is added to the brew without removing the previous ones.
Besides that, the alcohol content lore remains on the item even if alwaysShowAlc=false

Plugin v2.1.1, MC1.16.2, Paper-186. Lang zh is used.

This is how it looks like on my _Spirytus_, which requires to be distilled 70 times.
https://i.loli.net/2020/09/09/roxEHCwLfGQ4g7P.jpg

**Comment by Kbryst** [comment]
Same issue, same specs, Lang english/default

**Comment by Yukyxy** [comment]
hi, same issue (spigot 1.16.3) https://zupimages.net/up/20/39/ztdh.png

**Comment by Sn0wStorm** [comment]
Fixed in eeb9be74f9b699f7914a5f23e30d07c08c0bbf75

**Comment by Sn0wStorm** [comment]
Thank you for the Bug report, fixed in the new update v2.1.2
