### ISSUE TITLE
can't distill anything

### ISSUE THREAD

**Issue by Sam1000000** [DieReicheErethons/Brewery#331]
![distillatore](https://user-images.githubusercontent.com/73889833/97987381-756c3080-1ddb-11eb-97b8-5f4f7a0d77bb.png)
i don't know why but it doesn't want to distillate (sorry for my bad english) the version is 1.12.2

**Comment by Sn0wStorm** [comment]
I just tested it again on Spigot 1.12.2 and it works. What did you put as ingredients?

![Bildschirmfoto 2020-11-03 um 16 39 05](https://user-images.githubusercontent.com/4077108/98007133-511c4e00-1df3-11eb-9ef9-b623516a12fe.png)

**Comment by DereWah** [comment]
Hi, I am having a similar issue not being able to distillate.
I currently am playing on a modded server, using the magma version Magma-28edb4c. (1.12.2)
The crafting recipes in the crafting table are working fine but when trying to distillate anything the process just doesn't start.
I have tried opening a ticket on the magma git repo aswell, but I yet have to receive a repy.
Anyone has any suggestion or is able to help?

**Comment by Sn0wStorm** [comment]
Any Errors in the Log? Do you have CoreProtect installed?

**Comment by DereWah** [comment]
> Any Errors in the Log? Do you have CoreProtect installed?

Consider the ticket moved to #334 . I'm working with @Sam1000000 and I decided to open a new ticket with more detailed informations.
