### ISSUE TITLE
A brewery give command

### ISSUE THREAD

**Issue by itslukemango** [DieReicheErethons/Brewery#333]
We'd love to have the ability to sell drinks via NPC's and custom GUI's, and realistically the only way to do that would be to have a /brewery give (name) (drink) (amount) command added.

**Comment by ArcticRaven** [comment]
Having the command would enable so much functionality and compatibility to this resource. Would like to see this implemented.

**Comment by Sn0wStorm** [comment]
Do you mean the /brew create (name) (quality) command?

**Comment by itslukemango** [comment]
> 
> 
> Do you mean the /brew create (name) (quality) command?

I literally had no idea that exists, thanks.

**Comment by Sn0wStorm** [comment]
Ok maybe i should do a **give** command that is just an alias to the create command
