### ISSUE TITLE
Issue distillating anything

### ISSUE THREAD

**Issue by DereWah** [DieReicheErethons/Brewery#334]
Hello,
I am working on a modded server using magma foundation.
I managed to get the plugin to work, however the distillating process is creating some issues.
Whenever I put a potion in the brewing stand (after boiling it for the right amount of time with the correct ingredients in the cauldron) I get this warning message in the console:

```
03.11 20:08:45 [Server] WARN at java.lang.Thread.run(Thread.java:748)
03.11 20:08:45 [Server] WARN at net.coreprotect.consumer.Consumer.run(Consumer.java:107)
03.11 20:08:45 [Server] WARN at net.coreprotect.consumer.Process.processConsumer(Process.java:124)
03.11 20:08:45 [Server] WARN at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:289)
03.11 20:08:45 [Server] WARN at net.coreprotect.database.Logger.log_container(Logger.java:291)
03.11 20:08:45 [Server] WARN at net.coreprotect.database.Logger.container_logger(Logger.java:144)
03.11 20:08:45 [Server] WARN at net.coreprotect.database.Database.insertContainer(Database.java:242)
03.11 20:08:45 [Server] WARN at net.coreprotect.Functions.convertByteData(Functions.java:259)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
03.11 20:08:45 [Server] WARN at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
03.11 20:08:45 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.11 20:08:45 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.11 20:08:45 [Server] WARN at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
03.11 20:08:45 [Server] WARN at java.util.ArrayList.writeObject(ArrayList.java:766)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
03.11 20:08:45 [Server] WARN at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
03.11 20:08:45 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.11 20:08:45 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.11 20:08:45 [Server] WARN at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
03.11 20:08:45 [Server] WARN at java.util.ArrayList.writeObject(ArrayList.java:766)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
03.11 20:08:45 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
03.11 20:08:45 [Server] WARN java.io.NotSerializableException: org.bukkit.Color
03.11 20:08:40 [Server] WARN at java.lang.Thread.run(Thread.java:748)
03.11 20:08:40 [Server] WARN at net.coreprotect.consumer.Consumer.run(Consumer.java:107)
03.11 20:08:40 [Server] WARN at net.coreprotect.consumer.Process.processConsumer(Process.java:124)
03.11 20:08:40 [Server] WARN at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:289)
03.11 20:08:40 [Server] WARN at net.coreprotect.database.Logger.log_container(Logger.java:290)
03.11 20:08:40 [Server] WARN at net.coreprotect.database.Logger.container_logger(Logger.java:144)
03.11 20:08:40 [Server] WARN at net.coreprotect.database.Database.insertContainer(Database.java:242)
03.11 20:08:40 [Server] WARN at net.coreprotect.Functions.convertByteData(Functions.java:259)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
03.11 20:08:40 [Server] WARN at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
03.11 20:08:40 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.11 20:08:40 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.11 20:08:40 [Server] WARN at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
03.11 20:08:40 [Server] WARN at java.util.ArrayList.writeObject(ArrayList.java:766)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
03.11 20:08:40 [Server] WARN at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
03.11 20:08:40 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.11 20:08:40 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.11 20:08:40 [Server] WARN at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
03.11 20:08:40 [Server] WARN at java.util.ArrayList.writeObject(ArrayList.java:766)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
03.11 20:08:40 [Server] WARN at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
03.11 20:08:40 [Server] WARN java.io.NotSerializableException: org.bukkit.Color
```

I tried restarting, clearing the config and even without editing it the problem persists. I tried removing any RGB color information  (replacing it with the classif format as ORANGE or DARK_RED) from the config but that didn't work either

The magma modded version is Magma-28edb4c and the version is 1.12.2
The mods are the following:
Better Animals Plus    cybercat5555    betteranimalsplus-1.12.2-9.0.1.jar
Chocolate Quest Repoured    Lordepos    Chocolate-Quest-Repoured-1.12.2-1.21.9A.jar
Davincis Vessels    darkevilmac    davincisvessels-1.12-6.340-full.jar
Just Enough Items (JEI)    mezz    jei_1.12.2-4.16.1.301.jar
LLibrary    _ForgeUser11902522    llibrary-1.7.19-1.12.2.jar
Matchlock Guns    korallkarlsson    Matchlock Guns Mod-1.12.2-7a.jar
MovingWorld    darkevilmac    movingworld-1.12-6.353-full.jar
Pirates    spectre0987    pirates-0.0.6B.jar
Traveler's Backpack    Tiviacz1337    TravelersBackpack-1.12.2-1.0.34.jar
Xaero's Minimap
The plugins are the following:
Brewery, BuycraftX, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, iDisguise, Mobcash, PermissionsEx, PlayerReport, SkQuery, skRayFall, Skript, SuperVanish, TrollPlus, TuSKe, Vault, WorldEdit, WorldGuard

**Comment by Sn0wStorm** [comment]
The cause of the error seems to be CoreProtect. Does Distilling work if you remove the CoreProtect Plugin?

**Comment by DereWah** [comment]
> The cause of the error seems to be CoreProtect. Does Distilling work if you remove the CoreProtect Plugin?

I just tried removing it and the error on the console seems to disappear. However, the distillation process still doesn't work.

**Comment by Sn0wStorm** [comment]
Could you enable debug for Brewery in the config `debug: true` and post what it says in the log when you add a Brew to the Distiller?

**Comment by DereWah** [comment]
> Could you enable debug for Brewery in the config `debug: true` and post what it says in the log when you add a Brew to the Distiller?

Just tried doing that:
without CoreProtect AND with the debug activated, while trying to distillate some Sugar Brew nothing appears in the console and nothing happens. However, when I remove the 3 potions from the brewing stand, this message is logged:
```
03.11 21:50:05 [Server] INFO [Brewery] [Debug] Unscrambled data
03.11 21:50:05 [Server] INFO [Brewery] [Debug] Unscrambled data
03.11 21:50:05 [Server] INFO [Brewery] [Debug] Unscrambled data
```

**Comment by Sn0wStorm** [comment]
So it doesn't even say `Starting brew inventory tracking`?
Use this and post what it says when you open the Distiller, i've only added some debug messages

[Brewery-2.1.2-DEV.zip](https://github.com/DieReicheErethons/Brewery/files/5484342/Brewery-2.1.2-DEV.zip)

**Comment by DereWah** [comment]
> So it doesn't even say `Starting brew inventory tracking`?
> Use this and post what it says when you open the Distiller, i've only added some debug messages
> 
> [Brewery-2.1.2-DEV.zip](https://github.com/DieReicheErethons/Brewery/files/5484342/Brewery-2.1.2-DEV.zip)

Here's the log:
```
[Debug] Holder is BrewingStand: true
03.11 23:18:01 [Server] INFO [Brewery] [Debug] is Brewer? false
03.11 23:18:01 [Server] INFO [Brewery] [Debug] inv: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory@209f5b45
```

**Comment by Sn0wStorm** [comment]
So something is changing the Inventory of the Distiller to be a CraftInventory instead of BrewerInventory, any idea what that might be?

**Comment by DereWah** [comment]
> So something is changing the Inventory of the Distiller to be a CraftInventory instead of BrewerInventory, any idea what that might be?

I don't really know...
Maybe it's the magma server that does that to allow compatibility with all the mods?
If so, wouldn't it be possible to edit the plugin and make the distillation happen on the CraftInventory?
Also I see that it displays"true" when a Brewing Stand is opened. Isn't it possible to bypass the second check (is Brewer? false)?

I'm not really familiar with the plugin code so I might just be getting wrong a lot of stuff, but wouldn't it be possible?

**Comment by Sn0wStorm** [comment]
In theory it would be possible, but currently we reference the BrewerInventory in a lot of places and changing all of that would be a lot of work and might introduce new bugs

**Comment by Sn0wStorm** [comment]
I've just downloaded Magma and the strange thing is if you get the Block (holder) from the CraftInventory and on that you do getInventory() again, suddenly it **is** a BrewerInventory... So i think its a bug in Magma, i'll open a ticket with them

**Comment by DereWah** [comment]
> I've just downloaded Magma and the strange thing is if you get the Block (holder) from the CraftInventory and on that you do getInventory() again, suddenly it **is** a BrewerInventory... So i think its a bug in Magma, i'll open a ticket with them

I'll try to do the same; Lmk if you find anything :)

**Comment by DereWah** [comment]
> I've just downloaded Magma and the strange thing is if you get the Block (holder) from the CraftInventory and on that you do getInventory() again, suddenly it **is** a BrewerInventory... So i think its a bug in Magma, i'll open a ticket with them

Sooooo any news? I saw the issue you opened on Magma's repo. Is it possible to make the plugin compatible with magma?

**Comment by DereWah** [comment]
Hi,
Great news!
After opening the [issue](https://github.com/magmafoundation/Magma/issues/284) on Magma's github, they have released a patch downloadable at this link: https://github.com/magmafoundation/Magma/commit/ded9d6ceabcc6beb5e3df199bd70959cf080aed4

The brewing process now works fine and it is possible to distill! Thank you for the help,!

**Comment by Sn0wStorm** [comment]
I'm glad this works now!
