### ISSUE TITLE
Errors like that

### ISSUE THREAD

**Issue by JakonSU** [DieReicheErethons/Brewery#338]
![image](https://user-images.githubusercontent.com/50838200/98282183-1e628900-1f9e-11eb-8972-ffdfabba6cc8.png)

**Comment by Sn0wStorm** [comment]
Thank you for the report!
Is it like that all the time or just sometimes?
When this happens, does Distilling and Barrel-aging stop working?

**Comment by JakonSU** [comment]
> Thank you for the report!
> Is it like that all the time or just sometimes?
> When this happens, does Distilling and Barrel-aging stop working?
 Yeah, when this happens distilling and barrel-aging stops working

**Comment by Sn0wStorm** [comment]
Could you please try if this version fixes the problem? Thank you.

[Brewery-2.1.3-DEV.zip](https://github.com/DieReicheErethons/Brewery/files/5505711/Brewery-2.1.3-DEV.zip)
Compiled from 3fa16414d0e002db18e36e6ecabe741b18de3651

**Comment by JakonSU** [comment]
It fixed aging in barrel, but destiling still resorts always in murky distillate, yet without the error that was the previous time

**Comment by Sn0wStorm** [comment]
To help me reproduce the problem, could you please tell me what you are trying to distill? Which ingredients? Then

1. Take the Brew from the Cauldron
2. _Hold in Hand_ and do /brew debuginfo which will put info into the Server-Log
3. Distill and when it turns into Murky Distillate _hold in hand_ und do /brew debuginfo again
4. Post the Server-Log of both commands here.

**Comment by JakonSU** [comment]
![image](https://user-images.githubusercontent.com/50838200/99450004-6f6c6880-2920-11eb-9959-fe6233187cec.png)

**Comment by JakonSU** [comment]
and this is ruined potion, because it has stopped working again

**Comment by JakonSU** [comment]
![image](https://user-images.githubusercontent.com/50838200/99450238-c70ad400-2920-11eb-897c-9e25f7d511a9.png)
and this one is before brewing

**Comment by Sn0wStorm** [comment]
You have added 6 sugar and there is no recipe that needs 6 sugar?

**Comment by JakonSU** [comment]
okay, I can't read, there was sugar cane, not sugar
