### ISSUE TITLE
Config option - disable stagger

### ISSUE THREAD

**Issue by kylewilk567** [DieReicheErethons/Brewery#339]
Hello,

I really love your plugin, however the stagger messes with my anticheat plugin but creating false positives when a player is drunk. Can you create an option to disable the stagger when drunk?

Thank you!

kwilk

**Comment by Sn0wStorm** [comment]
Like #196 
might be added soon as an option to have a stagger scale

**Comment by Sn0wStorm** [comment]
Feature added in v3.0
