### ISSUE TITLE
Brewery plugin causes long server startup time and really low TPS.

### ISSUE THREAD

**Issue by DereWah** [DieReicheErethons/Brewery#341]
Note:
This happens only in the first 10 minutes after the server is restarted.

After adding the brewery plugin onto my server, it started taking long times to boot up and a started lagging a lot in the first 10 minutes after startup.

I think the problem is that it takes a lot of time to load the brews aging in all player's barrels.
logs:

```
[23:47:03] [Server thread/INFO] [com.dre.brewery.P]: [Brewery] Enabling Brewery v2.1.2
[23:47:03] [Server thread/INFO] []: [Brewery] [Debug] Loading data.yml: 0ms
[23:48:37] [Server thread/INFO] []: [Brewery] Bukkit took 93.856s to load Inventories from the World-Data File (in the Background),
[23:48:37] [Server thread/INFO] []: [Brewery] consider switching to Paper, or have less items in Barrels if it takes a long time for Barrels to become available
[23:48:39] [Server thread/INFO] []: [Brewery] Brewery enabled!
```

After the startup for the first 10 minutes after the server startup the CPU is over 70% usage and the TPS are around 3

When removing the plugin and restarting the server it starts up in 15 seconds and the TPS are from start at 20 tps.

Is this a know issue? I'm running the plugin on a modded server with MagmaFoundation, so I can't really switch to Paper ):
Thank you

**Comment by Sn0wStorm** [comment]
This is a problem with old versions of spigot like 1.12.
It is literally only one line, telling bukkit to load the file which takes so long!
There is no way to tell it to only load half the file or anything.

``` Java
BData.worldData = YamlConfiguration.loadConfiguration(file);
```

Thats why i added the message, as in Paper this only takes a tiny amount of time and also in later MC versions we do all of the loading in the background, which would crash on 1.12.
Also in 1.12 it loads chunks when loading barrels for some reason.

So i'm afraid for this old version there is nothing I can do, the only thing that helps is to use less barrels...
