### ISSUE TITLE
Similar recipes not differentiating

### ISSUE THREAD

**Issue by Inceris** [DieReicheErethons/Brewery#343]
Running Brewery 2.1.2 on Paper 1.16.4 build 271.

I'm having an issue where I have some very similar recipes and the plugin doesn't seem to be able to differentiate between them very well.

If you pay particular note to Vokda and Holy Water Vodka, you'll see the second recipe is the same except it has an extra ingredient, an iron nugget, and has a different name and different lore. This works fine. The same can't be said for Tequila and Brother Cuervo's Special Tequila, currently commented out. Whenever I or my players make the recipe for regular Tequila, they always get Brother Cuervo's Special Tequila instead.

Am I doing something wrong, or is this a bug?

**Comment by Sn0wStorm** [comment]
Could you post your recipes so i can have a look? Maybe using pastebin or similar?

**Comment by Inceris** [comment]
https://pastebin.com/t1gSV8GS

Whoops, made the pastebin and everything but didn't attach it! My bad.

**Comment by Sn0wStorm** [comment]
I've just tried with your recipes, and i get exactly whats expected. Only when i add the iron it turns into the special tequila.
Am i missing something?
