### ISSUE TITLE
Free Splash Potion

### ISSUE THREAD

**Issue by Kovalskki** [DieReicheErethons/Brewery#344]
If there is a vanilla potion along with the brew during the distillation process, the vanilla potion can be turned into a splash potion for free.

_Filter is not consumed after distillation_

Paper-1.16.3
Brewery v2.1.2

**Comment by Sn0wStorm** [comment]
This is not the case for me. I have put a Potion of Healing in with a Brew and it never changes. The Brew gets distilled and the Potion is not a Splash Potion afterwards.
