### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by illumeleet** [DieReicheErethons/Brewery#345]
Brewery causes console spam while loading data
![image](https://user-images.githubusercontent.com/51333325/99888409-abc00180-2c5d-11eb-8b97-035430b60a81.png)
and also randomly if players are on server

**Comment by Sn0wStorm** [comment]
This seems to be a Bug from Minecraft:
https://bugs.mojang.com/browse/MC-152265

This may be triggered by some items in Barrels, but i really don't know.

You can safely ignore this, but if you want to delete all Items from all Barrels, stop your server and delete the worlddata.yml from the Brewery folder.

**Comment by illumeleet** [comment]
Ok, thanks!
