### ISSUE TITLE
🚨 Maven repository down 🚨 

### ISSUE THREAD

**Issue by SaltyAimbOtter** [DieReicheErethons/Brewery#346]
Hey 👋 
Your maven repo is down... which breaks our build 😞 
Is this intended? When will it be available again?

**Comment by Sn0wStorm** [comment]
Thank you for the notice, i'm currently working on fixing it.

**Comment by Sn0wStorm** [comment]
I will likely switch to using JitPack from now on, as the repository will be down for a while.

I have uploaded a fixed version on JitPack that you can use @SaltyAimbOtter :

```
<repository>
   <id>jitpack.io</id>
   <url>https://jitpack.io</url>
</repository>

<dependency>
   <groupId>com.github.DieReicheErethons</groupId>
   <artifactId>Brewery</artifactId>
   <version>2.1.3</version>
   <scope>provided</scope>
</dependency>
```

Built from https://github.com/DieReicheErethons/Brewery/commit/86de4a0382155ce85c86df4759c5a7f6e2685293
Sorry for the inconvenience!

**Comment by SaltyAimbOtter** [comment]
Thank you for the fast response 👍
