### ISSUE TITLE
Confused about sealing

### ISSUE THREAD

**Issue by Gengyen** [DieReicheErethons/Brewery#347]
I had no clue about the sealing table until a brewer in my server brought it up; he sells his drinks via the [Quickshop](https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/) plugin, but all of them are not registering. There's 14 Strong Absinthes, and the shop is only showing the **bottom 3** for sale. The drinks have 3 different descriptions, and I have separated them by **row**.

ROW 1
![image](https://user-images.githubusercontent.com/42317852/99911230-2439c780-2d1d-11eb-8f05-d1920c8dd961.png)
ROW 2
![image](https://user-images.githubusercontent.com/42317852/99911246-429fc300-2d1d-11eb-8221-73b3d96b5e39.png)
ROW 3 (The ones being sold)
![image](https://user-images.githubusercontent.com/42317852/99911256-4fbcb200-2d1d-11eb-9fa0-56f2efc17166.png) 
![image](https://user-images.githubusercontent.com/42317852/99911265-59461a00-2d1d-11eb-8035-c075f87a970b.png)

I have never used the table either, so I don't know how it's supposed to work. I put in 2 from **row 3** and 1 from **row 2**; it then spit them out as they were. So... I have many questions D:
a) Am I meant to wait? How exactly do I seal?
b) Do I fill all 9 slots?
c) If I do, which drink is it going to take on?
d) Are these drinks just not similar enough? How sensitive is sealing?
e) It says NBT: 5 tags but that seems vague. Is there a way to get & compare exact numerical ID?
We're just trying to figure out why they're being detected & thus sold differently. Being able to make them uniform would have been great for us.

**Comment by Sn0wStorm** [comment]
The items your are showing are already sealed, you cannot put them in the sealer again. (As seem by the Brackets [ ] around the stars)

The simplest way to see is if they can all be sold the same is: The description lore is exactly the same.

In this case, the top row items are 4 star, the middle items have a bug from a previous version and are more distilled and the bottom row items have 5 stars.
If either the amount of quality-stars or distilling is not the same, then even the sealing table can't make them uniform.

**Comment by Gengyen** [comment]
Tysm!
> If either the amount of quality-stars or distilling is not the same, then even the sealing table can't make them uniform.
Then what does it make uniform? How similar do the drinks have to be?

**Comment by Sn0wStorm** [comment]
Well really 3 things have to be the same:
Recipe (Name)
Quality (Stars)
Distill-runs (Shown in Lore)

The sealing table is really more of a workaround for a technical issue, where most shop plugins use the `itemStack.equals()` method (rightfully so) to compare items when selling or trading them.
This means that when even the smallest detail is different when brewing Brews, like one minute boiling difference, just one more ingredient, or aging for just that bit longer, the items will no longer be exactly equal.

The sealing table basically just removes all of those brewing data details. Then items that equal in the 3 things above, will be equal by the method.
