### ISSUE TITLE
Some items cannot be put in the cauldron.

### ISSUE THREAD

**Issue by Aarteek54** [DieReicheErethons/Brewery#348]
Hello, I've installed the plugin for my 1.14.4 server yesterday. I didn't change the config file or didn't add any recipes, but when I tried to make some drinks, some items just couldn't get into the cauldron when i right clicked on it. I found this happening with wheat seeds, pumpkin seeds, orange dyes and yellow dyes. Other items, like milk bucket, or apples is working as it should. I'd be really grateful for any help.

**Comment by Sn0wStorm** [comment]
The cauldrons need a heat source under them. Also the dyes are not used in any of the default recipes?

**Comment by Aarteek54** [comment]
There's a heat source underneath, as I said, some items go in with no problem, but few do not. 
I looked up some guide for this plugin and I found a recipe for "Banana Mango Smoothie" with dyes so I thought I'm gonna try it, but now I see it's not in the official wiki so I think it is either outdated, or an other plugin. Not sure.
