### ISSUE TITLE
Darkbeer doesnt brew

### ISSUE THREAD

**Issue by turner10** [DieReicheErethons/Brewery#349]
So I have brewery 2.1.3-DEV for the version, and when I go into config for recipes, the darkbeer one just doesn't work. It said it needed wood 6 which doesnt exist since it is wood 0-5, 5 being dark oak, so I changed it to wood 5, and now when I brew in dark oak, following the recipe exactly, it just gives me beer. I even changed the amount of wheat for each, so I dont even know why it doesnt work, when I made each recipe pretty different from eachother.

**Comment by Sn0wStorm** [comment]
Something in your config seems to be wrong to me, Dark Oak is definitely wood 6
https://github.com/DieReicheErethons/Brewery/blob/0b9b364f28634a8dff7bb66eb8c3675d747b2eec/resources/config/v13/en/config.yml#L412

Also you say it gives you dark beer? Do you mean it gives you normal Beer? That would be correct, as you can see the normal Beer and Darkbeer are exactly the same recipe at the start, and only the wood type **and** the long aging makes it darkbeer, after waiting long enough.

**Comment by turner10** [comment]
> Something in your config seems to be wrong to me, Dark Oak is definitely wood 6
> https://github.com/DieReicheErethons/Brewery/blob/0b9b364f28634a8dff7bb66eb8c3675d747b2eec/resources/config/v13/en/config.yml#L412
> 
> Also you say it gives you dark beer? Do you mean it gives you normal Beer? That would be correct, as you can see the normal Beer and Darkbeer are exactly the same recipe at the start, and only the wood type **and** the long aging makes it darkbeer, after waiting long enough.

Right, I meant normal beer, and I also forgot to add that when I age it, it is being aged for 40 years, but I will edit the config to wood 6 and see if it works.

**Comment by Sn0wStorm** [comment]
Ah ok. Keep in mind that if you change it to be aged 40 years, that it will take a lot longer to become dark beer.

Imagine it like this for example, if you keep it in a barrel for 10 years, it is still a lot closer to Beer (3 years) than to Dark Beer (40 years), so it will be Beer for a long time until it turns to dark beer, as Beer also has a lower difficulty.

**Comment by turner10** [comment]
Could you please explain what difficulties do.

**Comment by Sn0wStorm** [comment]
Lower difficulty means you don't have to follow the recipe as precisely in every step

**Comment by turner10** [comment]
> Lower difficulty means you don't have to follow the recipe as precisely in every step

So I tried the recipe again, with wood six, and I just have 87 year old fine beer.

**Comment by Sn0wStorm** [comment]
If you want to have Darkbeer with 80 years, you need to put Beer at a higher difficulty of 2. Otherwise it is "too easy" to get beer and it will start prefering beer over others.

If you still have this issue, you can reopen, or create a new one.
