### ISSUE TITLE
Compatibility with the latest version 1.16.4 I don't know if there is any conflict

### ISSUE THREAD

**Issue by vc606** [DieReicheErethons/Brewery#350]
After the server upgrade paper-1.16.4-294, the tps is often abnormally low. It seems that the brewery plug-in occupies extremely high resources (not generated immediately, it may be opened for a while)

https://imgur.com/hlGqK89

I also used mmocore related plugins and found that there is a suspected loading incompatibility message

[23:28:33] [Server thread/WARN]: [Brewery] Loaded class net.mmogroup.mmolib.api.item.NBTItem from MMOLib v1.4.4 which is not a depend, softdepend or loadbefore of this plugin.

**Comment by Sn0wStorm** [comment]
Thank you for the notice.

You seem to have Multiverse, do you have anything Brewery related on Worlds that you unload?
Could you send me the link to the timings report?
Thank you

**Comment by vc606** [comment]
https://timings.aikar.co/?id=ae4b796d90964584a0d08985c8fc435b

**Comment by Sn0wStorm** [comment]
Thank you, i will be fixing that lag in the next update. As you can see from count(1) it only happened once, when you were unloading a world. The other high resource usage seems to be coming from entities and is not related to Brewery

**Comment by Sn0wStorm** [comment]
Fixed in v3.0
