### ISSUE TITLE
Negative alcohol values?

### ISSUE THREAD

**Issue by Imouto-Kaede** [DieReicheErethons/Brewery#355]
Is it possible, and does it work? - assigning negative alcohol values to brew.
I kinda want to make something that helps when you're too drunk. I know that you can drink milk over and over again, but something on-the-go is what I'd prefer. So, I wanted to ask if you even can set the alcohol value to a negative number without the plugin crashing on load, and if you can, does it work properly?

**Comment by Sn0wStorm** [comment]
Not yet possible, but is being worked on

https://github.com/DieReicheErethons/Brewery/pull/352

**Comment by Feefkroete** [comment]
@Sn0wStorm
You could add a possibility to add the "Brewery:" tag in front of an Item in "drainItems"
_If you know what I mean^^_
