### ISSUE TITLE
recipe of the champagne

### ISSUE THREAD

**Issue by helpmeplis** [DieReicheErethons/Brewery#357]
help, i search for the recipe of the champagne to do it, but all i make is murky distille, i dont know what i do wrong, i follow the recipe here https://www.reddit.com/r/Elementos/wiki/brewery#wiki_aging

**Comment by Sn0wStorm** [comment]
They have added the champagne to their server, it is not a default recipe.
The default recipes can be found here: https://github.com/DieReicheErethons/Brewery/wiki/Recipes

**Comment by helpmeplis** [comment]
how can the recipe be added?

**Comment by Sn0wStorm** [comment]
In the config.yml
