### ISSUE TITLE
"/brew create" only gives best quality

### ISSUE THREAD

**Issue by Feefkroete** [DieReicheErethons/Brewery#358]
**_Config file:_**
beer:
  name: awful beer, beer, tasty beer
  ingredients:
    - Wheat/3
[...]

**_Plugin version:_** 
3.0

If I want to create awful beer by using "/brew create awful beer" I get tasty beer every time.
Is this a bug or is it intended to be like that?

_I use /brew create a lot to try out new textures and models for the drinks..._

**Comment by Sn0wStorm** [comment]
Use `/brew create beer 1` where 1 is the quality, to give you bad quality beer

**Comment by Feefkroete** [comment]
Ok
Thanks^^
