### ISSUE TITLE
Crimson & Warped Break Recipes

### ISSUE THREAD

**Issue by Moyye99** [DieReicheErethons/Brewery#361]
Using Brewery 3.0.0
Recipes set to use either Crimson or Warped barrel variants for aging fail to load.

![image](https://user-images.githubusercontent.com/56613755/103329183-a5c1fb00-4a29-11eb-9222-a6cae623e2d8.png)

**Comment by Imouto-Kaede** [comment]
I think wood types 7 and 8 (nether wood types) aren't supported yet. You can only have woods 1 through 6 which are all the overworld wood types.

**Comment by Sn0wStorm** [comment]
What version of Minecraft are you using? 7 and 8 should be supported in 3.0

**Comment by Moyye99** [comment]
This is on Minecraft 1.16.4

**Comment by CanadianJokes** [comment]
I too am having this issue on my server. 

I haven't tested this first hand, but one player said they were able to age brews in nether wood barrels. 

It looks like it's enabled to age, but not enabled to be specifically called out as the wood to age in. 

I hope this narrows it down.

**Comment by Moyye99** [comment]
@Sn0wStorm Here's all I'm doing to get the error. Changing wood-type to 7 instead of 2 for mead.
![image](https://user-images.githubusercontent.com/56613755/104080129-4cf61d80-51f4-11eb-85fd-e5adbf48fc35.png)

**Comment by Moyye99** [comment]
I've done some looking into the code that was added for the 1.16 wood types. Perhaps this might have a clue for you? This is from the LegacyUtil.java file

![image](https://user-images.githubusercontent.com/56613755/104270037-8ed9ca80-5465-11eb-8e82-006248c302ca.png)

**Comment by GeneralSarcasam** [comment]
I am also experiencing this issue on version 3.0. When the plugin is reloaded with a barrel type of 7 or 8 specified in a recipe, it's produces the error as described.
![image](https://user-images.githubusercontent.com/75270972/104289689-724e8a00-5487-11eb-8a92-5fd0346c4431.png)
