### ISSUE TITLE
ERROR: Old Data took too long to load! Mutex: 0

### ISSUE THREAD

**Issue by EnvyEnfys** [DieReicheErethons/Brewery#362]
I was wondering what causes this and a way to fix it. ERROR: Old Data took too long to load! Mutex: 0

**Comment by Sn0wStorm** [comment]
How often does this happen?

How big is your Brewery/worlddata.yml file?

**Comment by EnvyEnfys** [comment]
Worlds:
  3a5f4cde-84ff-488b-9bf3-56217daa13e0: world
  28d5ba26-4f3a-45ea-a870-0cb6b999dcf2: world_nether
  8cb4df65-e2f9-4fd5-ac75-78ec92aeae79: world_the_end
  082c73fd-1f1f-4919-9b3d-7d9bf7c264bb: world
  da7f9e56-8ac3-4cce-bcd8-3600ce59579a: world_nether
  2194f44d-7e45-4d48-a5f8-45b16c73cb1a: world_the_end
  b3984315-4c2c-4dc6-a212-88dbf1fdfbdc: world
  6533053c-e87f-4e11-8fb6-215892b0ea27: world_nether
  8409206c-2c20-4d98-a716-136e5d832dd9: world_the_end
  206fe88e-7c7d-4037-8bef-3c25ebf254f5: world
  90ad9d44-4659-40ba-a9b9-e693f83dd290: world_nether
  f308524a-3e0d-4c8b-bb64-719d5c3584b7: world_the_end
  e51d7a40-0757-449c-905e-d1a0984db252: world
  45be5cdd-818f-47ed-bd3f-d1d5b0ab3078: world_nether
  2f245707-5911-4da4-92db-e6cc044936b2: world_the_end
  082798c8-1681-4212-880b-c0be5b588d05: world
  2b017f59-c421-490d-bdf5-47840dd3080c: world_nether
  c9164928-56d8-4c8e-8c4c-c87318bd4a91: world_the_end
  05d5ee1b-7a34-481a-92dc-887e88da6aa0: world
  3a7832da-d71a-4e72-bed6-9ce3416a8d75: world_nether
  119ce408-2564-4ee4-862e-e308fa24a1f0: world_the_end
  a873c80b-7e29-4137-ba68-7763f5c07df6: world
  2843d76e-c916-4046-ab0c-b8a6c8cf9d66: world
  0bacbf7d-becf-4377-ad6d-cec214fb391c: world_nether
  d783602d-9f0c-44a9-b833-3d4a6745648a: world_the_end
  d0545f21-4ae4-451b-8c42-00767b23483e: world
  5537c610-11dd-48af-a2d3-be92c8a06edd: world
  c6cf4aeb-748f-4b83-8e7c-1b1a51a908d6: world_nether
  32510b54-9fde-4794-9023-8a0f1e8727e8: world_the_end
  4f4004e9-0e0d-492d-bcb1-b98a4e781bb7: world
  02ced027-d317-4140-a00c-7293b0fc46ef: world_nether
  cc27bc83-744f-4884-a20c-f40eec494531: world_the_end
  daecef67-15d0-46f9-a32e-185c0905e1e5: world
  449bae64-747f-46cb-9274-885113d226d0: world_nether
  97cf0253-e660-42bc-962a-a0db18a64566: world_the_end
  a13d3fa0-d4af-41d6-b727-ee29368d7a87: world
  dece9b6a-ad3a-4064-9b25-9129e3291967: world_nether
  87d36cf9-4880-47c9-ab11-2ccc3f959865: world_the_end
  53a32fd5-646d-4099-a9ef-ed200303d482: world
  3f403bd5-1999-4f1f-a39d-62b9db963349: world
  d4851895-80cc-4b43-aa49-94b850128e6a: world
  0af1661f-202d-43c4-ab7b-0167cb26ccfa: world
  12cfbf3e-4cf8-460a-93e1-b789f72e73ed: world_nether
  08c0a83e-3983-490e-a378-a692da6e220b: world_the_end
  1681085a-9796-476c-bac5-d53d99591cbb: world
  5bfed60f-3eb4-4db7-8f88-41d70d4c6930: world_nether
  9e9cc04b-54d8-40b2-b2b9-793b5ee31e18: world_the_end
  ac0aa187-4fa0-43b0-bc51-0424fd2040c1: world
  9328dc84-aa58-41b0-b340-5c50d10dd158: world
  142f1cc2-9471-4fdb-a208-8eff938fb259: world_nether
  36de97bc-fdc9-4439-acc5-27ff90308f67: world_the_end
  6387a313-b1bd-4ea3-918a-765352f4b3c4: world
  f49b4679-7d33-48ee-ae8c-a913c14fd959: world_nether
  0dd6ae04-b090-41c5-a88c-25973e657aa4: world_the_end
  2d766dee-1e6f-44df-8ca0-6e58eae0e049: world
  58592bcd-44ff-43cd-aff6-431668140d70: world_nether
  7e8e7484-a3f0-4489-8d1c-653aaec5d37a: world_the_end
  22d8900d-5040-451a-b688-9ed4174d70f5: world
  bfecaea7-9236-467f-bf58-cf0037f442d9: world_nether
  5994891c-2728-42f0-8910-f17c34301a10: world_the_end
  a1ec2b60-6896-4d5f-96bd-cf02b19d375c: world
  80ca9bd0-f194-4657-a486-091a54fd1062: world_nether
  dbafbcb9-253f-47e3-8de8-72efd37bd7f5: world_the_end
  15487d5d-1755-4ee3-bcc4-998140202404: world
  dcff213c-19c9-4915-b33e-01a4f25ce5d2: world_nether
  2051e414-3f54-441d-849e-b1efe9ec0eca: world_the_end
  d92d0dd2-0ef0-407e-8273-67a1c16581cb: world
  4a666f6e-e7e4-42e6-b38e-769ad28a0c53: world_nether
  55573a39-9bc6-4128-aa88-c6538217fa65: world_the_end
  d879b14c-c8c9-4eac-b2a4-9d4c1b6ae862: world
  6c47d103-8bcf-47dd-a8d3-8638c5deaf14: world_nether
  8da9dcf6-80bc-4811-be69-10edd5b939c4: world_the_end

**Comment by EnvyEnfys** [comment]
I dont think this is normal?

**Comment by Sn0wStorm** [comment]
Maybe delete the file and see if it still happens. this doesn't look normal
