### ISSUE TITLE
Custom Drinks/Brews

### ISSUE THREAD

**Issue by Albeion** [DieReicheErethons/Brewery#365]
I am unsure if there is a discord I can submit this to but,
I saw it mentioned that you could make/code more drinks into the plugin, I have tried messing around with adding the code for a new drink for a few hours yet nothing seems to be working. I don't have much experience when it comes to coding, so I can not tell if it is a problem with my coding or not. I am basing the structure of the code based off all the other types that exist.
Help would be greatly appreciated!
- Albeion.
[Brewery Testing.docx](https://github.com/DieReicheErethons/Brewery/files/5769660/Brewery.Testing.docx)

**Comment by Sn0wStorm** [comment]
You need to be careful to do everything exactly as it needs to be, as yml is not a very forgiving format.

The best idea is to copy one of the existing recipes and then change the values to your liking.
On top of all the recipes, there is some notices to what all the different options do, like the woodtype

**Comment by Albeion** [comment]
Oh ok, thanks alot for your help!

**Comment by Albeion** [comment]
I did try to copy a recipe and replacing everything to what I needed, yet it still didn't work? Is there something else I need to do before that? Do I need to have ingredients put somewhere else for it to draw from?

**Comment by Albeion** [comment]
Figured it out :))
