### ISSUE TITLE
`enableWake` does not work

### ISSUE THREAD

**Issue by Wolf2323** [DieReicheErethons/Brewery#366]
We added a bunch of WakeUp location, but nothing happens.

The configuration option `enableWake` is never readed in the `BConfig` and i can not find any other use.
This could may be the reason, why the WakeUp locations do not wrok.

**Comment by DerDerakus** [comment]
Hallo. I have the same Problem. I also set the position new. Restartet the server, usw. but it dosnt work,

Servus. Ich hab das selbe Proble. Ich hab die Positionen neu gesetzt, den Server neugestartet, usw.. aber es funktioniert leider nicht.

PS:

**Comment by SmilinSarahK** [comment]
I have this same problem, however, I am assuming it is because possibly I use the sleepmost plugin... I have not done the research on this yet nor have I disabled sleep most and got a player 'drunk' to see what happens...

**Comment by Wolf2323** [comment]
it is not caused by your other plugin, i serched in the code, and the config option is not implemented in the code

**Comment by Sn0wStorm** [comment]
Wakeup points are working fine if you are not OP. For some reason LuckPerms gives you the bypass for login teleports if you are op. If you want to be teleported on login to a wakeup point, you need to set your permission `brewery.bypass.teleport` to `false`.

The enableWake option is not implemented, i must have forgotten that, so now it is always active
