### ISSUE TITLE
YML failes to load

### ISSUE THREAD

**Issue by GeneralJosh** [DieReicheErethons/Brewery#368]
My custom brewery config and the updated fresh install config fail to load when restarting the server, I did the fresh install to see if It was a config recipe related issue and the vonfig was rejected with the message:
[04:07:27] [Server thread/INFO]: [Brewery] ERROR: Could not read file config.yml, please make sure the file is in valid yml format (correct spaces etc.)

My config is uploaded [here](https://github.com/GeneralJosh/config.yml) if you see any issues but as far as I know It's been the same since I've been doing it for the past year

**Comment by Sn0wStorm** [comment]
If you make a lot of changes, you should use an online yml validator to check if the yml you created is valid.
In yours there is an error in line 897 and 922
