### ISSUE TITLE
Feature Request: drunk slurring repurposed as a general word swap/censor plugin/option

### ISSUE THREAD

**Issue by kuraiskrap** [DieReicheErethons/Brewery#369]
i couldnt find a option to make it so sober people would be slurred, needed atleast 1% drunk
is it possible to have a  0% drunk option for slurring, or just that feature as a separate plugin?

So im canadian as as a joke i used the plugins slurring to simply translate everything to canadian for canada day 
police becomes mounty, swearing became sorry, mostly as a joke
but could be a way for servers to censor swearing, without just a list of words that punishes people

i couldnt locate one that did what this does, and i see it being fairly versitile

**Comment by Sn0wStorm** [comment]
The word swapping is implemented very very simple, so it really is just for fun to change some words around without any accuracy. So as a general censor plugin it would probably not be reliable and versatile enough.
