### ISSUE TITLE
Can we make "milk in a bottle" to do the same effect that milk does removing effects?

### ISSUE THREAD

**Issue by TomLewis** [DieReicheErethons/Brewery#370]
Ahoy
Is there a way to clear all effects the same milk in a bucket does? 
I just want to be able to have a milk in a bottle/brew that does the same thing as normal milk, just without the need for a bucket, then I can put it in a kit item without giving out free buckets.

So far the only thing I can think of is to run a command to clear peoples effects, I think Essentails/CMI allows `/effect clear`.
```
# servercommands: List of Commands executed by the -Server- when drinking the brew (Can use %player_name%  %quality%)
# playercommands: List of Commands executed by the -Player- when drinking the brew (Can use %player_name%  %quality%)
```
Is there a cleaner preferred method to do this? For example is the milk mechanic registered in brewing?

**Comment by NitroxBro** [comment]
You can add milk bottle into the sobering items...I think)

**Comment by Sn0wStorm** [comment]
I think with a server command it would be the cleanest way. It could be the CMI command or i'm sure there is a vanilla command that does the same. There is no "Milk Effect" i think

**Comment by TomLewis** [comment]
I played around for a long while and I came up with something that works using the effect clear command, I was just curious if the "milk effect" was part of Brewing or not already to not require a command!
