### ISSUE TITLE
Why cant I use /brew give BrewName 10 Playername from console, so I can use it in kits?

### ISSUE THREAD

**Issue by TomLewis** [DieReicheErethons/Brewery#371]
This is a massive blow, I spent ages setting up a brew specifically to have it in a kit (run a command) the command works in-game but as soon as you try and do it from console, NOPE! denied. what gives, this means no other plugin can give a player a brew???

**Comment by NitroxBro** [comment]
Well, you might have problems with uniforming your brews, that why you can't give yourself a brew, but you can give it in kit. Every brew has it own item id(potion 3b for example), to become all your potions have same item is you must lead the amount of ingredients, sealing and brewing time and the quality of the brew. If these four indicators be the same, item id of all the brews will be the same too. Also read this for more info - https://github.com/DieReicheErethons/Brewery/issues/347   Good luck!

**Comment by Sn0wStorm** [comment]
Ah well you need the permission `brewery.cmd.create` for that command. I don't know if it is even possible to give permissions to the console? And I didn't know the console does not just have all permissions??

**Comment by TomLewis** [comment]
For some reason when I tried it from the console it didn't work, but when I have it in an Essentials kit to run the command it works.
So it does work how I wanted it to work, but what is weird is not being able to do it from the console.
