### ISSUE TITLE
Formatting Bad Potion Names

### ISSUE THREAD

**Issue by Maie13** [DieReicheErethons/Brewery#372]
I'm trying to format the names of a brew. It works fine for the normal and good brews but the first word of the bad brew is getting cut off and it doesn't apply the formatting. I've tried getting around the issue using various spacing and changing the format in the middle of the word, etc. but nothing seems to help. Any ideas?

This is what I'm using specifically:
name: &4Bad Command/&cOk Command/&6Good Command

**Comment by Sn0wStorm** [comment]
This might be a yml problem, but i don't know.
It is a very good idea to add ' ' around the whole string and then yml knows exactly that it all belongs to the string. But it has to be around the whole string! So in your case:

name: '&4Bad Command/&cOk Command/&6Good Command'

**Comment by Maie13** [comment]
That fixed it. Thanks!
