### ISSUE TITLE
Dupe Distilling Bug

### ISSUE THREAD

**Issue by Justinclewis94** [DieReicheErethons/Brewery#379]
I found how to reproduce issue #290 "Dupe Distilling Bug" and it still works today:

TO REPRODUCE:
1. Get a good, working brew you want to distill. Let's say Apple Cider that you want to brew into AppleJack.

2. Place the good brew in a brewing stand with a glowstone filter. This will start the distill process.

3. Place or activate a hopper under the brewing stand. This will pull the distilling brews out of the stand, but you'll notice the stand continues to distill, even while the stand is empty.

4. Before the empty distill process finishes, use another hopper to feed ANY un-sealed brew into the stand. These could be 1-star brews, undefinable distillate, etc...

5. When the distill process finishes, any brews fed into the stand will become AppleJack (or whatever the 1st brew would have become).

NOTES
Don't click anywhere in your inventory while the brewing stand inventory is open. This will reset the distill process.

This could potentially be automated to mass produce expensive 5-star brews using any cheap/useless brew.

**Comment by Justinclewis94** [comment]
The distillation process of brewing can only be stopped or started with the InventoryClickEvent (or something similar). Because of this, using hoppers to add/remove brews from a brewing stand can cause some weird problems.  Maybe trigger the distill process with a hopper move event as well?

**Comment by Sn0wStorm** [comment]
Do you by any chance have disabled the hopper move event? It's called `disable-move-event` in the `spigot.yml`

If that is set to true, the move event is disabled and brewery cannot stop the distill process as it cannot detect the hopper moving items out of the distiller.
If i test and disable the event, exactly what you described can happen, if the event is enabled like normal, the hopper cannot pull the potion out of the distiller.

**Comment by Sn0wStorm** [comment]
But even if this event is disabled, in v3.0 it checks again at the end of the process to see if the correct Brew is still in the distiller, so the dupe doesn't happen. Can you make sure you are on v3.0?

**Comment by Justinclewis94** [comment]
I don't actually own/manage the server that I was testing on.  They do a lot to reduce lag, so it's very likely that the hopper move event is disabled.  Looks like they last updated the brewery plugin Dec 2020, so I don't think it's 3.0
Sounds like it was just an improper server configuration bug, so you're welcome to close this issue.
