### ISSUE TITLE
Keine Color Codes als erste Stelle möglich.

### ISSUE THREAD

**Issue by HoudiniJD** [DieReicheErethons/Brewery#387]
Hallo, 
ich hätte eine Frage. Ist es möglich color codes zu benutzen. In diesem fall: 
name:
Lost Souls/&7Forgotten &2Soul/&cE&7t&ce&7r&cn&7a&cl &7Soul &8of &2S&7ain&2t P&7at&2r&7ic&2k
Ich kann dem 2 Gebräu und 3 einen coolen Namen geben aber leider nicht der ersten Version. Kann man das umgehen mit einem
unsichtbaren Symbol oder ähnlichem? 

Danke im Voraus!

**Comment by Sn0wStorm** [comment]
Man muss in yml dann einfach den gesamten String in ' ' packen.
Also     name: '&6Lost Souls/&7Forgotten &2Soul/&cE&7t&ce&7r&cn&7a&cl &7Soul &8of &2S&7ain&2t P&7at&2r&7ic&2k'
