### ISSUE TITLE
Can't add new recipes.

### ISSUE THREAD

**Issue by apelsin222** [DieReicheErethons/Brewery#388]
I tried putting this recipe in the config.yml:
   g_vodka:
     name: 'Rancid Vodka/&6Golden Vodka/&6Shimmering Golden Vodka'
     ingredients:
       - Potato/10
       - Gold_Nugget/2
     cookingtime: 18
     distillruns: 3
     age: 0
     color: ORANGE
     difficulty: 6
     alcohol: 20
     effects:
       - WEAKNESS/28
       - POISON/4
      But that didn't work. Does anyone know what I am doing wrong?

**Comment by Sn0wStorm** [comment]
Did you do /brew reload ?
Did it say anything as an error?

**Comment by Sn0wStorm** [comment]
Try changing one of the default recipes first and see if that works. Then when you add the new recipe, make sure it is in exactly the right format as the others, with the same indents and spacings.
