### ISSUE TITLE
[Request] Enable glowstone consumption during distillation step

### ISSUE THREAD

**Issue by VeteranDrenor** [DieReicheErethons/Brewery#391]
Hello,
Your work is amazing on this plugins ! I use brewery on my RPG server, and I would be able to be enable the glowstone consumption during the distillation process. It is possible to add this option in the configuration files? 

Thanks you :)

**Comment by Sn0wStorm** [comment]
If you would like it to consume the Glowstone, you could add it as an ingredient, so the players need to use it in the cauldron to brew the drinks?  
The glowstone in the distiller is seen more like a "distilling filter" that is not added into the drink, but only filters the alcohol.
