### ISSUE TITLE
Tried adding recipes broke the plugin

### ISSUE THREAD

**Issue by PHZ710** [DieReicheErethons/Brewery#393]
I tried to add the recipes that were suggested in the config and I somehow broke the entire plugin. Is it possible to get more details or a tutorial on how to create and add recipes?
I just copied and pasted each recipe but without the #s. 

ill copy and paste what I put in the config starting from eggnog to show one i didnt add. I also edited some of the replacement words could that have somehow messed things up? 
I have no idea where to start to fix it other than removing the recipes and rebooting the server which im about to do but sadly leaves me without the new recipes. 

  eggnog:
    name: Egg Liquor/Eggnog/Advocaat
    ingredients:
      - Egg/5
      - Sugar/2
      - Milk_Bucket/1
    cookingtime: 2
    color: 'ffe680'
    difficulty: 4
    alcohol: 10
    wood: 0
    age: 3
    lore: Made with raw egg
    
g_vodka:
    name: 'Rancid Vodka/&6Golden Vodka/&6Shimmering Golden Vodka'
	ingredients:
       - Potato/10
       - Gold_Nugget/2
    cookingtime: 18
    distillruns: 3
    age: 0
    color: ORANGE
    difficulty: 6
    alcohol: 20
    effects:
       - WEAKNESS/28
       - POISON/4

 fire_whiskey:
    name: Powdery Whiskey/Burning Whiskey/Blazing Whiskey
     ingredients:
       - Wheat/10
       - Blaze_Powder/2
    cookingtime: 12
    distillruns: 3
    distilltime: 55
    wood: 4
    age: 18
    color: ORANGE
    difficulty: 7
    alcohol: 28
    drinkmessage: 'You get a burning feeling in your mouth'
    
  hot_choc:
    name: Hot Chocolate
     ingredients:
       - cookie/3
    cookingtime: 2
    color: DARK_RED
    difficulty: 2
      effects:
       - FAST_DIGGING/40
      
 iced_coffee:
    name: Watery Coffee/Iced Coffee/Strong Iced Coffee
     ingredients:
       - cookie/8
       - snowball/4
       - milk_bucket/1
    cookingtime: 1
    color: BLACK
    difficulty: 4
     effects:
       - REGENERATION/30
       - SPEED/10

**Comment by PHZ710** [comment]
Yep just as I assumed removing the recipes I added fixed everything. So I guess my issue/problem is im unsure of how exactly you write in new recipes.

**Comment by Sn0wStorm** [comment]
You need to make sure that the spaces before each line are correct. Have a look at the other recipes, each line has a certain amount of spaces before it. Make sure the recipes you add are made in the exact same way. Make sure not to use Tabs but spaces. This is due to how yml works.

**Comment by PHZ710** [comment]
I looked at the other recipes and tried again with just Fire Whiskey and then restarted my server to find it broke the plugin again. How many spaces exactly? do they change on some lines cuz I counted 3 and then 3 more for adding the ingredients if that made sense.

**Comment by Sn0wStorm** [comment]
Just copy one of the default recipes, then it will have the correct amount of spaces already.
Also you don't need to restart the server, just use /brew reload and it will tell you if the config is failed
