### ISSUE TITLE
I can't brew anything

### ISSUE THREAD

**Issue by emvo0** [DieReicheErethons/Brewery#395]
Hello.
I installed this plugin on my clean 1.16.5 paper server and i have this weird bug.

Instead of mead cauldron is outputting a sugar brew.
I tested multiple recipes while following instructions from your site and none of them work as intended. (output is incorrect)

Problem persists on all three versions below.
Brewery-3.0
Brewery-2.1.2
Brewery-2.1.3-DEV.zip

Plz help

**Comment by Sn0wStorm** [comment]
You need to put the Brew from the Cauldron into a Barrel and wait for a while.
