### ISSUE TITLE
i need to be sure of something otherwise i can't sleep at night 

### ISSUE THREAD

**Issue by jory0111** [DieReicheErethons/Brewery#396]
so ive been looking trough code patch notes and even setup a test server to see if i was right or wrong. turns out to many variables to brute force it the config had 20 recipes including the example. I've tested out many variations and i'm going insane ive been looking into this for 2 days,. and as i cant code java i cant say for sure. so does this mod have hidden recipes? i know all things even the config kinda states that it doesn't,  i have to know for sure.   
# I don't want to add more Recipes to the default config, as they would be public and viewable by users to cheat.
# It is up to the Serveradmin to change and add Recipes, so players cannot cheat from the default config.
like it looks to me, you want server owners to add recipes. the patch note also says the same.
bstats shows that 70%> add custom recipes so, ive added in more default recipes . 

i know this makes it pretty clear that no this mod doesn't have hidden recipies. and the fact ive looked trough all the source code that no there are no hidden recipes i need to know for sure. i feel shitty having to waste your time with this so, please toss me a paypal link and ill send you 15 bucks might not be allot but at least a couple beers. and a way to make up for your lost time. i m very sorry. the server i am on doesn't have a changed config for clarity.  

i hope you will be able to put my mind at ease and i hope i haven't caused to much of an inconvenience.
thanks in advance for the help.
jory,

**Comment by Sn0wStorm** [comment]
Ah don't worry, no problem for asking.
You're right, there are no hidden recipes, only the ones in the config will be used.
You can also remove the default recipes from the config and then they are gone.
So again, no hardcoded recipes, only everything you see in the config.

**Comment by jory0111** [comment]
thanks a bunch dude appreciate it!!
