### ISSUE TITLE
Can't create brews that need other types of alcohol as ingredients

### ISSUE THREAD

**Issue by GeneralDarian** [DieReicheErethons/Brewery#397]
I'm trying to make a recipe for Brandy, which is made by distilling wine.

I would like to make brandy by "fermenting" wine first, creating a base called "heated wine", and then distilling it. Here is how I configured it:

https://pastebin.com/5S48N9fP
I saved the brandy recipe under "brandy", the heated wine under "brandy-base" and the wine under "wine".
However, putting wine in a cauldron doesn't work.

Is there a way to fix this?

**Comment by Sn0wStorm** [comment]
The paste is private.
The problem is usually using the right name for the ingredient. So if you call your base "heated wine" you need to use that name as the ingredient: 'brewery:heated wine'
If the heated wine has multiple names for its quality, use the middle one.

**Comment by mcgodbuild** [comment]
i know its possible to use brewery plugin created items into recipes. Its the base of the 50 coctail recipes i created
