### ISSUE TITLE
Can't make absinthe

### ISSUE THREAD

**Issue by fistiG** [DieReicheErethons/Brewery#399]
Hello everyone! I can't get an absinthe. Now I will explain everything:
I cannot add the herb to the cauldron, thus I cannot make this absinthe.
Will this be fixed or somehow explained?

**Comment by Sn0wStorm** [comment]
Which minecraft version are you on?
Have you changed anything in the config of brewery?
The Herb for absinthe is the grass that you cut with shears, please try different types of grass as well.

**Comment by fistiG** [comment]
> Which minecraft version are you on?
> Have you changed anything in the config of brewery?
> The Herb for absinthe is the grass that you cut with shears, please try different types of grass as well.

version 1.12.2
yeah, I changed config of brewery
I tried

**Comment by Sn0wStorm** [comment]
Maybe something is interfering with the recipe for absinthe? You can try to change the recipe for absinthe to maybe use some other ingredient and see if it works then.
