### ISSUE TITLE
 I can't add my own language

### ISSUE THREAD

**Issue by cajop** [DieReicheErethons/Brewery#400]
after adding the pl.yml file that I wrote myself, everything is replaced with the placecholder.
in config.yml I changed en to pl. am i doing something wrong or plugin prohibits adding my own languages?

**Comment by Sn0wStorm** [comment]
It should work adding your own language. Does the server log say anything is wrong?

**Comment by cajop** [comment]
> It should work adding your own language. Does the server log say anything is wrong?

Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 2, column 1:
    Brew_-times: -Razy
    ^
expected <block end>, but found '<anchor>'
 in 'string', line 97, column 21:
    Player_TriedToSay: '&v1 tried to say: &0&v2'
    
    I don't know what to do about it
