### ISSUE TITLE
Feature Request: Mixing Drinks

### ISSUE THREAD

**Issue by Elafir** [DieReicheErethons/Brewery#404]

**Comment by Feefkroete** [comment]
At the moment you can create mixed drinks by making a recipe which requires drinks from this plugin.

For example:

grvdkbeer:
    name: grassy vodka-beer
    ingredients:
    - **Brewery:beer/1**
    - **Brewery:vodka/1**
    - grass/2
    cookingtime: 2
    distillruns: 0
    difficulty: 6
    age: 0
    alcohol: 13
    color: GREEN

**Comment by Elafir** [comment]
I've been working on a fork with mixed drinks since I made this issue. It's somewhat bittersweet finding out that it already exists.
