### ISSUE TITLE
[Question]: Specify custom config path

### ISSUE THREAD

**Issue by Feefkroete** [DieReicheErethons/Brewery#405]
Hi everyone
I know that this is kind of weird but is there a way to specify a link or a custom path for the config file?
It would be useful to be able to set a github link as path and get updates automatically...
Thanks in advance^^
Matthi

**Comment by Feefkroete** [comment]
I found this in the source code...
![grafik](https://user-images.githubusercontent.com/62547250/116705660-0f98e400-a9cd-11eb-906c-4c8636a69cc6.png)

Could this work?
![grafik](https://user-images.githubusercontent.com/62547250/116706311-cd23d700-a9cd-11eb-961d-7c664b286298.png)

**Comment by Sn0wStorm** [comment]
The plugin includes a config updater, so if you update the plugin, the config gets updated to the newest version automatically.

Using a newer version of the config without updating the plugin would not be very useful?

**Comment by Feefkroete** [comment]
My intention was to get the plugin to get it's config from my github repository...
But it's no longer needed because of internal changes...
Thanks for the answer^^
