### ISSUE TITLE
[Feature Request] Brew Soup

### ISSUE THREAD

**Issue by Kovalski4** [DieReicheErethons/Brewery#410]
Brewery soups can easily integreta into plugin. Custom soups are a good feature for towny server. Player can make own cultural foods.

**Comment by bluewingtitan** [comment]
You allready are able to create custom recipes. Just make the result have no alcohol and add saturation at a wanted level with the wanted length as effect.

**Comment by Sn0wStorm** [comment]
If you want the item to look like a soup, you can use a custom texture.

**Comment by Sn0wStorm** [comment]
I don't think i will have the time to implement soups, there would be so many changes necessary. As i said, you could use a custom texture to make the item look like a soup.
