### ISSUE TITLE
Delay between servercommands

### ISSUE THREAD

**Issue by HoudiniJD** [DieReicheErethons/Brewery#411]
Hey there I got following file: 

  1307:
    name: Faded Crystal/&9Crystal's &3&M&NMortality/&9&LCrystal's &3&LC&3&L&Ma&9&Lly&3&L&mps&9&Lo
    ingredients:
    - CRYSTAL/4
    - GOLD_NUGGET/2
    - LIGHT_BLUE_DYE/1
    cookingtime: 26
    distillruns: 1
    color: '87cefa'
    difficulty: 10
    lore:
    - + &fThere is no clarity here...
    - ++ &fAs the waves crash against the sea,
    - ++ &fThere is almost a moment of clarity...
    - +++ &fTaste the salt from the waves
    - +++ &fand feel the wind sting your face as 
    - +++ &fCrystal's Calypso brings clarity
    servercommands:
    - 'execute at %player_name% run playsound minecraft:ambient.underwater.enter master %player_name%'
    drinktitle: '(&e☀&f)' 
    
    I asked myself if it's possible to add a delay with a servercommand?
    Means it runs one server command, waits X amount of time and runs the next one? 
    Is that possible?
    
    Example:     
    servercommands:
    - 'execute at %player_name% run playsound minecraft:ambient.underwater.enter master %player_name%'
    - wait 10 seconds - 
    - 'execute at %player_name% run summon bee'

**Comment by Sn0wStorm** [comment]
No this is not possible, sorry. I'm sure you could use a scripting language to do exactly that, something like "Skript" or "Lua"
