### ISSUE TITLE
All recipes that require aging but not distilling are now broken

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [DieReicheErethons/Brewery#412]
There's been an issue about recipes not working lately so I've tested and tested, and it seems like all the recipes that require ingredients that go in the cauldron and straight to a barrel do not work. Recipes that require ingredients going into the cauldron, then to the brewing stand, and then to the barrel DO work.

**Comment by Sn0wStorm** [comment]
Could you delete your Brewery config.yml file and then do /brew reload and try again? Maybe the config got corrupted.

**Comment by ReasonFoundDecoy** [comment]
This did the trick! Thanks for your help :D
