### ISSUE TITLE
Cheat Programm wertet Betrunken als Fly/Cheat program evaluates drunk as fly

### ISSUE THREAD

**Issue by toefte** [DieReicheErethons/Brewery#415]
Hey ich habe folgendes Problem ich nutze Brewery zusammen mit AC-Negativity dem Anti Cheat Plugin. Nun immer wenn spieler besoffen sind werden sie vom Server gekickt weil sie "Fly" genutzt haben. Schalte ich automatisch kicken aus bekomme ich jede sekunde eine Meldung über den Spieler das er Fly benutzt. Kann ich irgendwie Brewery und Negativity vereinen, so das die Leute betrunken sein können und es nicht als Fly gewertet wird ?

Hey I have the following problem I use Brewery together with AC-Negativity the Anti Cheat Plugin. Now whenever players are drunk they get kicked from the server because they used "Fly". If I turn off automatic kicking I get a message every second about the player using Fly. Can I somehow combine Brewery and Negativity, so that people can be drunk and it is not counted as Fly?

**Comment by Sn0wStorm** [comment]
Hi, dann scheint das Plugin wohl ein bisschen zu streng eingestellt zu sein. Wenn man betrunken ist wird man eben etwas herumgeschubst und kann auch mal schneller sein, als normal mit Laufen möglich wäre.
Also entweder das Plugin ein bisschen zurückschrauben, oder sonst bei Brewery in der config die Stärke vom betrunkenen torkeln etwas runterstellen. (stumblePercent)
