### ISSUE TITLE
Expanding to food!

### ISSUE THREAD

**Issue by TomLewis** [DieReicheErethons/Brewery#418]
I would LOVE to see Brewing system expanded to also include food, could use custom heads as food.
Have you thought about this before?

**Comment by Sn0wStorm** [comment]
I thought about doing this, but there are already plenty of custom items Plugins out there. It could be considered that creating food or drinks using a good custom item plugin could be added.

Though it seems to me like creating food in the Cauldron and Barrels does not make too much sense? And also food doesnt have alcohol, so instead maybe a completely separate food plugin would be better
