### ISSUE TITLE
Unable to use some drinks in cauldron?

### ISSUE THREAD

**Issue by ShadowXTP** [DieReicheErethons/Brewery#421]
Im trying to use Iced Coffee in one of my recipes, but I'm unable to place it in the cauldron for the recipe. I've used the Brewery:iced_coffee but it won't work for me, even though, I was able to put coffee itself in the cauldron.

**Comment by blackquiver** [comment]
So 'Iced Coffee' is your ingredient.

It has to be in the ingredients list, it also has to have be used in a 'cauldron recipe' as per the configs.

**Comment by Sn0wStorm** [comment]
You could try 'Brewery:Iced Coffee' to see if that works
