### ISSUE TITLE
some questions i have about this

### ISSUE THREAD

**Issue by 777Sergio777** [DieReicheErethons/Brewery#423]
since i dont know about this, i fell pretty lost when i think on it:

do i need any mod or something to use this? my friends doesnt want mods, but they are ok with plugins and datapacks that doesnt change the vanilla minecraft too much, this is a plugin right? can i use this in a vanilla server?

and well, this is secondary, but will thyis be translated to spanish?

**Comment by Sn0wStorm** [comment]
No mods, this is a plugin only for the server. This doesn't change the vanilla game, it only adds more features.

Spanish is available with `language: es`
