### ISSUE TITLE
Difference between a 5 star inperfect potion and 5 star perfect potion?

### ISSUE THREAD

**Issue by JollyWasTaken** [DieReicheErethons/Brewery#424]
**When brewing the apple cider I realized that with 2 days aging it's still 5 stars even though it requires 3, why is this? And is there something else that's meant to happen when it is done perfect?**

Like what does aging do to the quality?

**Comment by Sn0wStorm** [comment]
Apple Cider is a recipe with a rather low difficulty. This means that you don't have to get it perfectly right to get 5 star quality. So a few days more or less aging, a few more or less ingredients and boiling time will not make such a difference.

With for example Absinthe you have to be stricter to make good quality.

You can change this in the config

**Comment by JollyWasTaken** [comment]
Tysm, I get it now!
