### ISSUE TITLE
1.17 server crash

### ISSUE THREAD

**Issue by IronKerman** [DieReicheErethons/Brewery#426]
When i create and then open a small barrel i become a ticking entity and my server crashes any ideas how to fix this? 
i have included the crash report below
[crash-2021-08-03_20.41.40-server.txt](https://github.com/DieReicheErethons/Brewery/files/6926946/crash-2021-08-03_20.41.40-server.txt)

**Comment by IronKerman** [comment]
The big barrels also cause the server to crash

**Comment by Sn0wStorm** [comment]
Can you please remove the Brewery Plugin and see if the crash is still happening?
