### ISSUE TITLE
Literally cannot alter the config to make custom drinks because everything breaks

### ISSUE THREAD

**Issue by Athrizel** [DieReicheErethons/Brewery#436]
Literally every time I alter the config in ANY way, the barrels stop working and I can no longer make them. I've tried replacing the current config with the english config and that breaks it, I've tried modifying the base config file with what I want to do.... and that breaks it, if memory serves I had this same issue YEARS ago and never got a solution then.

If anyone could help me figure out why the hell this is happening, I would appreciate it because I am at my wits end here.

**Comment by Athrizel** [comment]
I think I fixed it, there were some errors with the custom ingredients I was putting in. I saw the errors in the log when I booted up the server.

**Comment by Athrizel** [comment]
ok so I figured out what the problem is, the recipe isn't formatted right? Could someone tell me what I did wrong here with the syntax?

  essence_of_a_god:
    name: Tainted Essence/Purified Essence/&5Eldritch Essence
    ingredients:
      - ghast_tear/6
      - eye-of-fire/5  # Custom-Item: Ender Eye
      - lost-star/1  # Custom-Item: Nether Star
    cookingtime: 9
    distillruns: 4
    distilltime: 60
    wood: 8
    age: 10
    color: BLACK
    difficulty: 7
    alcohol: -10
    lore:
      - + After all the effort
      - + you still failed
      - ++ Pure but not complete
      - +++&5A pefect recreation
      - +++&5of the one gods essence
      - +++&5may his grace guide you
    drinkmessage: 'You feel the thick caress of the one god's essence slither down your throat'
    effects: 
      - ABSORPTION/0-5/50-800
      - BAD_OMEN/500
      - DAMAGE_RESISTANCE/0-5/0-800
      - FIRE_RESISTANCE/0-5/0-800
      - HEALTH_BOOST/0-5/0-800
      - INCREASE_DAMAGE/0-5/0-800
      - JUMP/0-5/0-800
      - LUCK/0-5/0-800
      - NIGHT_VISION/0-5/0-800
      - REGENERATION/0-5/0-800
      - SATURATION/0-5/0-800
      - SPEED/0-5/0-800
      - WATER_BREATHING/0-5/0-800

**Comment by Athrizel** [comment]
NVM, you can close this now, I ran the darn thing through a YAML validator, we're good.

**Comment by Auseawesome** [comment]
If you are good close your issue
