### ISSUE TITLE
Brewing stand recipes gone.

### ISSUE THREAD

**Issue by HenriMation** [DieReicheErethons/Brewery#441]
Hello, I recently tried this plugin and I've had a problem.
I cant brew anything in the brewing stand.
I've tried multiple recipes and nothing works, I've tried restarting the server and nothing.
Is there anyway to fix this?

**Comment by HenriMation** [comment]
I can't brew any potions in the brewing stand. Every time I try to brew a potion it works, but when it finishes making the potion nothing happens. Like the ingredients and awkward potion do not disappear, and the potion trying to be made does not appear.

**Comment by Sn0wStorm** [comment]
This sounds more like another Plugin removing the recipes from the Brewing Stands
