### ISSUE TITLE
Cant include some of the Brewery Plugin Drinks to Brewery Recipes

### ISSUE THREAD

**Issue by TZTGa** [DieReicheErethons/Brewery#442]
I coded some of the drinks into a recipe. It did not empty the drink when I reloaded and right clicked the cauldron with the drink.
So I coded this into the config to see if the feature works. It did not with a few exceptions.
Coffee, all the beers , whiskey and vodka worked. None of the others worked.
test:
name: Cocktail
ingredients:
- Brewery:Coffee/2
- Brewery:Wheatbeer/2
- Brewery:Beer/2
- Brewery:Darkbeer/2
- Brewery:Wine/2
- Brewery:Mead/2
- Brewery:Ap_mead/2
- Brewery:cidre/2
- Brewery:Whiskey/2
- Brewery:Rum/2
- Brewery:Apple_liquor/2
- Brewery:vodka/2
- Brewery:Gin/2
- Brewery:Tequila/2
- Brewery:Shroom_Vodka/2
cookingtime: 5
distillruns: 2
distilltime: 60
wood: 4
age: 11
color: DARK_RED
difficulty: 3
alcohol: 14

**Comment by Sn0wStorm** [comment]
You need to use the **Middle Name** of the Drink. So instead of
`Brewery:Ap_mead/2`
it should be
`Brewery:Sweet Apple Mead/2`
