### ISSUE TITLE
How to add strength potion effect?

### ISSUE THREAD

**Issue by azzztec** [DieReicheErethons/Brewery#453]
red_vine:
    name: Поганое красное вино/Красное вино/Отличное красное вино
    ingredients:
      - SWEET_BERRIES/14
    cookingtime: 5
    distillruns: 0
    wood: 5
    age: 20
    color: '650013' # Dark Red-Brown
    difficulty: 17
    lore:
      - +++ &8Винцо          
    alcohol: 15
    effects:
      - HUNGER/2/30
      - STRENGTH/2/20

After reloading config i have this: **Effect: STRENGTH does not exist!**

**Comment by Sn0wStorm** [comment]
INCREASE_DAMAGE

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
