### ISSUE TITLE
Question: Do you plan to update your plugin to 1.18?

### ISSUE THREAD

**Issue by MrCookie112** [DieReicheErethons/Brewery#455]
**Do you plan to update your plugin to 1.18.1? I do not hide from you that I love your work and that the server where I play is based on your plugin and without this it is a great fun that leaves us.**

**Respectfully, a dedicated player.**

> Excuse me if I'm repeating myself, I also asked this question about the CurseForge.
> I didn't know how you prefer to have this kind of question communicated to you.

**Comment by Eutaxy1** [comment]
Look to my update in #478 , it's all thanks to #472
