### ISSUE TITLE
Trying to add potions - Brewery stops working entirely 

### ISSUE THREAD

**Issue by KeyEX99** [DieReicheErethons/Brewery#457]
Settings in "config.yml"
[plugins_Brewery_config.zip](https://github.com/DieReicheErethons/Brewery/files/7940600/plugins_Brewery_config.zip)

Console output:
https://pastebin.com/Q1zWZa65

The added potion was Red apple cider. I followed this video to add the potion:
https://www.youtube.com/watch?v=pRmT3QrYdgg

**Comment by JoloJanssen** [comment]
While i am not sure, but i think your brew title is wrong. While it doesn't matter for the "name" section, i believe the brew type name shouldn't have spaces and capital letters. Try editing this and see if it works.

**Comment by KeyEX99** [comment]
thanks I'll try that

**Comment by bigchunges402960402** [comment]
did that work?
