### ISSUE TITLE
Adding custom drinks

### ISSUE THREAD

**Issue by darklordtrr** [DieReicheErethons/Brewery#464]
i have try add custom drink but it wont work it say it added but dose not show up

**Comment by bigchunges402960402** [comment]
idfk how but for some reason its even more broken than anything else

**Comment by Sn0wStorm** [comment]
Start small by changing one thing on a default recipe and see if it works

**Comment by bigchunges402960402** [comment]
> Start small by changing one thing on a default recipe and see if it works

I learned how to do it properly and i think i will send the new updated format file so anyone can find and use it
