### ISSUE TITLE
How to use item from forge mod?

### ISSUE THREAD

**Issue by PalkerCode** [DieReicheErethons/Brewery#465]
Im using mohist (forge server fork) and i dont know how to use items from mods

**Comment by TheGreatWeegee** [comment]
not a creator of the plugin, but use debug mode and look for item written IDs (ones that are written with the colon, like harvestcraft:raspberryitem, etc)
metadata is not supported anymore in Bukkit/Spigot, I presume (author can correct me though), so you will need to find mods which are using different IDs
