### ISSUE TITLE
How to give brewery item?

### ISSUE THREAD

**Issue by miner1235** [DieReicheErethons/Brewery#466]
Hi, i'm miner, and i would like to create a "restaurant" where npc's sell drinks. Is there a way to give alcohol with command?

Thank's.

**Comment by Peskdt** [comment]
/brewery create 
![imagen](https://user-images.githubusercontent.com/91406867/161922810-9724dc12-6dc9-479b-a070-35c30cfa235f.png)

**Comment by Eutaxy1** [comment]
If you do `/brew create Absinthe 2 <name>` you should be able to place it into someone's inventory, provided they have ample space, and just do it without the name like in Peskdt's reply to give it to yourself

**Comment by miner1235** [comment]
Thatk you very much, I just didn't get the command.
