### ISSUE TITLE
Hex colors on Custom Items.

### ISSUE THREAD

**Issue by UnderstoodDev** [DieReicheErethons/Brewery#468]
A person recommended this plugin for my server, but when I tried it, I wanted to use my object system with names and lore modified with HEX colors, it happens that placing it in the file does not allow me to put it in the cauldron. Is it planned for a future update to support this?

customItems:
  Azúcar:
    material: sugar
    name: '{#002}Azúcar' (I tried {#------}, shortened....
    lore: 
    - '&fHola'

If anyone has any more ideas on how to test if it works let me know, but if it's added I'd appreciate it.

**Comment by Eutaxy1** [comment]
For the hex colors, you just input the color as `color: 'ffffff' #Description here as a reminder to your future self`, like in this example recipe

`bourbon:
    name: Watery Bourbon/Bourbon Whiskey/Kentucky Bourbon
    ingredients:
      - Wheat/10
      - Wheat_Seeds/5
    cookingtime: 12
    distillruns: 3
    distilltime: 90
    wood: 4
    age: 22
    color: '69120f' #Dark red-orange
    difficulty: 7
    alcohol: 40
    lore: '&7Goes good with soda'`

If it doesn't work let me know and I'll try to help you
