### ISSUE TITLE
It does not work properly on the 1.17.1 spigot server!

### ISSUE THREAD

**Issue by TheSaltyFish6** [DieReicheErethons/Brewery#473]
When i ran it in spigot 1.17.1 server,i found a bug that i can't use it.For example,if i put fermented wheat in a brewing stand,and put glowing stone dust in it.the gui will be crashed and u can't open it any more.The only way u can open it again is break it:(.so i hope that u can fix this problem and thx!lol!

**Comment by TheSaltyFish6** [comment]
sorry I'm Chinese my English is bad

**Comment by yyycfc** [comment]
哈哈咸鱼这都找到你了

**Comment by Sn0wStorm** [comment]
Likely an issue with a conflicting Plugin
