### ISSUE TITLE
Haste and Strength effect doesnt not exist

### ISSUE THREAD

**Issue by Sanictr** [DieReicheErethons/Brewery#474]
Strength and haste effects are not adding to the config file of this plugin

**Comment by TheGreatWeegee** [comment]
try INCREASE_DAMAGE for strength and/or INCREASE_SPEED for haste (?)

for a reason I don't remember minecraft names some of the effects differently in-code and in-game, so yeah

**Comment by Sanictr** [comment]
INCREASE_DAMAGE is works but INCREASE_SPEED doesnt

**Comment by Sn0wStorm** [comment]
Its just SPEED
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
