### ISSUE TITLE
How to change the inscription "barrel" when creating a barrel?

### ISSUE THREAD

**Issue by MarinCode456** [DieReicheErethons/Brewery#476]
I would like to translate this inscription into my own language. Is it possible to change it through the config or do I need to go into the code?

**Comment by Eutaxy1** [comment]
Check the plugins/Brewery/languages folder for one matching your language, if there isn't one you can probably create a new one following the format of an existing one, and when you do that go to line 8 in the config and change the language to whatever you called the file. For instance if you wanted french, you would change it from `language: en` to `language: fr`
