### ISSUE TITLE
Custom recipes do not work

### ISSUE THREAD

**Issue by XDarkAssassinX** [DieReicheErethons/Brewery#479]
I put these recipes in but none even makes, white wine makes red wine, hotchoc make chocolaty sap 

whitewine:
      name: Off Wine/White Wine/Chardonnay Wine
      ingredients:
        - Sweet_Berries/3
        - Sugar/1
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 10
      colour: 'ffffff'
      difficulty: 6
      alcohol: 6
      lore:
      - '+ &8Harsh-ish'
      - '+ &8Corked'
      - '++ &8Mellow'
      - '+++ &8Full-Bodied'
      
    hotchoc:
      name: Cold Chocolate/Hot Chocolate/Perfectly Sugared Hot Chocolate
      ingredients:
       - Cookie/3
       - Sugar/1
      cookingtime: 2
      distillruns: 0
      wood: 0
      age: 0
      color: DARK_RED
      difficulty: 2
      alcohol: 0
      effects:
       - HASTE/40

**Comment by XDarkAssassinX** [comment]
EDIT: doesn't even work when doing /brew create

**Comment by PingsDev** [comment]
Turn of debug mode and see if there are any errors on chat when you do /brewery reload

**Comment by bigchunges402960402** [comment]
ay bro can i upload that version u have made into spigot or whatever i give u credit and a link to ur github or whatever else jsut give me the green light pls
