### ISSUE TITLE
how the hell do i make custom pots with brewery 3.1

### ISSUE THREAD

**Issue by bigchunges402960402** [DieReicheErethons/Brewery#480]
because i am using tlauncher want to know how to do use the 3.1 version of it to make custom pots i am sick and tried of trial and error pls ong tell me

**Comment by Sn0wStorm** [comment]
https://github.com/DieReicheErethons/Brewery/wiki/Configuration
If you need examples, just use one of the existing recipes, or look at one of the commented out recipes in the config
