### ISSUE TITLE
Compile 1.18 update

### ISSUE THREAD

**Issue by Eutaxy1** [DieReicheErethons/Brewery#485]
This is not really an issue more just convenience (doesn’t affect me since I know how to compile anyways) but some people don’t and so it might be helpful to compile and create a new release. Thanks

**Comment by Eutaxy1** [comment]
Basically just make a new jar file release based on #472

**Comment by Sn0wStorm** [comment]
No need to recompile, as 3.1 works fine on 1.18

**Comment by Sn0wStorm** [comment]
If you need the fixes for Slimefun, you can use 3.1.1 on 1.18
