### ISSUE TITLE
Compile 1.19 update

### ISSUE THREAD

**Issue by fyhnfn** [DieReicheErethons/Brewery#486]
Add a 1.19 update and can you guys also add new barrels made of non-wood items like quartz, nether brick, brick, prismarine, blackstone and brick. Also add support for custom items, as in renamed item in the config.yml and add support for mangrove barrels.

**Comment by fyhnfn** [comment]
and also add Red Nether Brick barrels

**Comment by Sn0wStorm** [comment]
Non Wood Barrels might come in the future. Custom items are already supported, Mangrove barrels will be supported in the 1.19 update
