### ISSUE TITLE
Can you use items from mods?

### ISSUE THREAD

**Issue by bartaz61** [DieReicheErethons/Brewery#491]
Is it possible to use items from mods like pam's harvestcraft for the recipes?

**Comment by aspwil** [comment]
as far as I'm aware, this is a plugin that only supports spigot and paper servers.

i don't think its possible to run it in tandem with mods, but if you have gotten it running on a modded server. 

there is the command `/brew itemName` , run that while holding the item in your hand and see what it spits out

you could also try pressing `f3+h` to enable advanced item tooltips and copying the last line which should look something like modName:ItemName

put that in the config file as an ingredient, then try /brew reload and see if it spits out any errors.

I'm not a dev on this project so i don't know exactly what it supports but good luck

**Comment by ReasonFoundDecoy** [comment]
Brewery does have ExoticGarden support, which is a Slimefun addon. See here for more info: 
https://github.com/TheBusyBiscuit/ExoticGarden/tree/7f9a5f63e3c9c9adb37c92ecde75e98632b0e40f

**Comment by bartaz61** [comment]
I tested it with harvestcraft. Yes it is possible, you just need to use id
