### ISSUE TITLE
Seal table's crafting table wont work

### ISSUE THREAD

**Issue by Connerl6** [DieReicheErethons/Brewery#492]

**Comment by aspwil** [comment]
what does this mean?
can you not craft the sealing table?
does the sealing table not open when you right click?
does the sealing table not seal bottles?
are you using paper or spigot?
what version of brewery are you using?
what mine craft version of paper/spigot are you on?

the brew sealing table can only seal things that have a star rating in the item description, are you sure what your trying to seal has a rating (1-5) stars in the description?
