### ISSUE TITLE
Question/Suggestion for brew names to have hex/rgb formatting support

### ISSUE THREAD

**Issue by sarahmigo** [DieReicheErethons/Brewery#521]
Hi there,
Apologies if this has been asked previously, but is it possible to include the ability for HEX or RGB formatting for brew names within recipes? Thanks so much!

**Comment by akoot** [comment]
It is possible, you have to type it like this **##ffcccc** = `&x&f&f&c&c&c&c`

**Comment by sarahmigo** [comment]
> 
Thank you so much for letting me know, I really appreciate it!! 😄
