### ISSUE TITLE
Problem with custom textures.

### ISSUE THREAD

**Issue by kamarad290** [DieReicheErethons/Brewery#566]
Hi, I've searched all the forums or articles regarding custom textures for the Brewery plugin and even created a Resource pack using the demo Resource pack, but still my custom textures are not showing up. Only the custom beer texture is displayed, which only appears if I use the command **/give <nickname> minecraft:potion{CustomModelData:557}**. But otherwise, no custom texture changes.

I'm posting my **potion.json** file here: https://pastebin.com/sLRukHqD
Note: CustomModelData numbers (558-574) are my random numbers. I don't know if there are any specified ones I need to use or not, that's why I'm asking here.

Can someone help me please?

**Comment by PainOchoco** [comment]
Hi, are you on 1.19.3+? This is because Mojang introduced a new way of loading textures called "atlases". You can use https://github.com/Dominexis/Atlas-Logger to fix your pack.

**Comment by kamarad290** [comment]
It didn't do anything to my files (or at least I don't see any changes), but thank you, I can see the textures now, but only if I get items via /give, otherwise when I cook something it doesn't work.

**Comment by kamarad290** [comment]
Okay, I have it. I had to add my own CustomModelData to each item from the Brewery plugin. Thanks for the previous advice, maybe it helped a bit. If anyone has any more questions on this or needs any help, just feel free to PM me at discord **11th Doctor#6711** if you can't post here. Have noice day
