### ISSUE TITLE
1.18.2 Resource Pack Unable to Apply Brewery Textures

### ISSUE THREAD

**Issue by Fairby** [DieReicheErethons/Brewery#571]
Hello! I've been working on a custom texture pack for a server based on the provided texture pack example, but I keep running into an issue. Although it's able to apply a single texture (i.e., the beer texture), when I use the standard format to add multiple textures, it simply stops working altogether. Does anyone have a fix for this?

The code for the potion.json file is this:

{
    "parent": "item/generated",
    "textures": {
        "layer0": "item/potion_overlay",
        "layer1": "item/potion"
    },

    "overrides": [
		{"predicate": {"custom_model_data":300011}, "model": "item/Stately_Red_Wine"
		},
    "overrides": [
		{"predicate": {"custom_model_data":300029}, "model": "item/Soju"
		},
    "overrides": [
		{"predicate": {"custom_model_data":400017}, "model": "item/Marmite"
		}
	]
}

**Comment by RedDevel2** [comment]
Not for the above issue
Adding 1 to for example ID: 300029
will then change the texture for every other ID with a higher number (300030, 300031... 400000 etc.)

**Comment by Vutka1** [comment]
> The code for the potion.json file is this:
> 
> ```
> "overrides": [
> 	{"predicate": {"custom_model_data":300011}, "model": "item/Stately_Red_Wine"
> 	},
> "overrides": [
> 	{"predicate": {"custom_model_data":300029}, "model": "item/Soju"
> 	},
> "overrides": [
> 	{"predicate": {"custom_model_data":400017}, "model": "item/Marmite"
> 	}
> ]
> ```

As I know, you shouldn't have multiple «**_"overrides":_**» sections in a file. Instead, you should make only one section and type all the custom models paths inside it _(see provided screenshot, making it like this works fine on my server)_

Try doing this and reply if it helps (or not)
![image](https://github.com/DieReicheErethons/Brewery/assets/93795732/c77effc8-a550-4d4a-a8e2-ab906cde4573)
_don't forget **NOT** to put any commas after the very last model in the file or it will screw up all the models and turn them into purple._

**Comment by Fairby** [comment]
Thank you so much for your response! Unfortunately, altering the code this way didn't make the textures work. I've double-checked the structure of the folders, the names of the items, everything I can think of. This is the code I adjusted and used:

{
    "parent": "item/generated",
    "textures": {
        "layer0": "item/potion_overlay",
        "layer1": "item/potion"
    },

    "overrides": [
		{"predicate": {"custom_model_data":300011}, "model": "item/stately_red_wine"},
		{"predicate": {"custom_model_data":300029}, "model": "item/soju"},
		{"predicate": {"custom_model_data":400017}, "model": "item/marmite"}
	]
}

**Comment by Vutka1** [comment]
I suppose, now you've misplaced the ending brackets ( "}" symbols), as they should be placed on a new string, under the opening brackets, not on the same line _(once again, see my screenshot for the reference)_. Now that is what causes the problem, I think.

Try changing what you currently have
```
"overrides": [
	{"predicate": {"custom_model_data":300011}, "model": "item/stately_red_wine"},
	{"predicate": {"custom_model_data":300029}, "model": "item/soju"},
	{"predicate": {"custom_model_data":400017}, "model": "item/marmite"}
]
```

To this:
```
"overrides": [
	{"predicate": {"custom_model_data":300011}, "model": "item/stately_red_wine"
	},
	{"predicate": {"custom_model_data":300029}, "model": "item/soju"
	},
	{"predicate": {"custom_model_data":400017}, "model": "item/marmite"
	}
]
```

**Comment by Fairby** [comment]
It worked! Thank you so much!

**Comment by Vutka1** [comment]
You're welcome =)
There should be a button somewhere to close the issue, by the way.
