### ISSUE TITLE
add Item Lore

### ISSUE THREAD

**Issue by IrusVirus** [DieReicheErethons/Brewery#59]
(Ich wollte Ticket #15 nochmals asprechen)

Könnte man bei den Rezepten auch eine Lore hinzufügen?

Damit könnte man einem Getränk die Lore "&0Flasche1" geben. Ein Resource-Pack welches CIT-Items unterstützt und eine Grafik darstellt sobald ein Item in der Lore "Flasche1" stehen hat, würde dann eine Wein-, Bier- oder Whiskyflasche darstellen.
Zumindest würden wir dafür sehr dankbar sein da wir ein umfassendes Resource-Pack haben :)

**Comment by Sn0wStorm** [comment]
Eingebaut in v2.0
