### ISSUE TITLE
Change the stars

### ISSUE THREAD

**Issue by Tolmwn** [DieReicheErethons/Brewery#595]
Hey guys, i love your plugin but im the owner from a server and i cant find the file where i can change the stars colour and how much stars to be. I want from the 5 stars to be 3,5 stars and the colour yellow. I have screenshots like that what i want !!

That what i have ⬇⬇
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/bf208eb5-2144-41d5-b473-516b2ad55f00)
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/4313a3eb-6ebb-47ab-b612-32506eaf3f53)

That what i want its that ⬇⬇
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/f655bfe3-964c-43b2-a0fe-de3d48428fdd)
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/863e0305-c54f-43d4-b017-6b37d99ab1ba)

I have only this files ⬇⬇
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/4f555a24-d691-4f5d-979b-3c635466df76)
![image](https://github.com/DieReicheErethons/Brewery/assets/136921445/1c66abf9-261e-4b0f-9a32-0bde458dcf48)

Please tag me when you reply :)

**Comment by Vutka1** [comment]
There's currently no way to change this without editing the plugin itself. @Tolmwn

**Comment by Tolmwn** [comment]
Its fine, i fount it how its work. Its like with a command
