### ISSUE TITLE
Is there a way to use metadata for items?

### ISSUE THREAD

**Issue by Archeron-Ivicus** [DieReicheErethons/Brewery#60]
First of all, I just want to say this is an amazing plugin, you have done some amazing work!

We are using Brewery on a modded 1.6.4 server (Attack of the B-Team) and all of the standard recipes work perfectly, and I even managed to add a couple that use modded items, which was amazing. However, I recently tried to make one using blueberries, an item that had metadata (Ex: not the exact numbers, but 700 is a blackberry and 700:1 is a blueberry). I can put this into the ingredients list, but once I add it to a recipe, the plugin stops working correctly. The commands remain functional, but nothing can be brewed. Is there a specific way that you add metadata items, or is it just not possible? Any help would be greatly appreciated!

**Comment by Sn0wStorm** [comment]
This was added a while ago: Metadata is supported with "," as 700,1 for blueberry, or INK_SAC,10 for lime dye.
