### ISSUE TITLE
Barrels do not work for anyone apart from OP

### ISSUE THREAD

**Issue by FrozenBeard** [DieReicheErethons/Brewery#69]
Using Spigot 1.7.10, Players cannot interact with barrels.
This is an example error of some interaction http://pastebin.com/cr9RiCgw
OP's (Just me) seem to be able to use barrels.

**Comment by Feuerstern** [comment]
That's because Brewery currently does NOT support WorldGuard 6. Just use the old 5.9 and it'll work fine up to all Bukkit-API server softwares for Minecraft 1.8 ;)

**Comment by FrozenBeard** [comment]
It's not in a WG region, I only have a WG region for my spawn, will that
still conflict? It is in a GriefPrevention Region, Really old GP 7.8 still
on PirateCraft.
A few other plugins recently moved to WG 6 and wont work with WG 5 any
more, is this a big job to update to the new API's? Thanks for your
responce :)

**Comment by Grafe** [comment]
I fixed the WorldGuard issues, can you try this build?
http://server.die-reiche-erethons.com/plugins/brewery-1.3.jar

**Comment by FrozenBeard** [comment]
Superb! I added it to my server at 6pm GMT so its been running an hour and
a half and barrels seem to work and brew now, my players are estatic with
brewing booze! I assume you managed to find the issue? Thank you again.

**Comment by Grafe** [comment]
No problem and thank you for the report :)
