### ISSUE TITLE
cant seem to make espresso

### ISSUE THREAD

**Issue by PaleHorse42** [DieReicheErethons/Brewery#70]
please help, im in chromahills.net

**Comment by PaleHorse42** [comment]
i love the plugin but cant make espresso. help

**Comment by Grafe** [comment]
What is not working? Can you post your config file?

**Comment by PaleHorse42** [comment]
I actually can't, its not my server, the server its on is Chromahills.
 GhostRyder 

     On Monday, January 5, 2015 7:12 AM, Grafe <notifications@github.com> wrote:
   

 What is not working? Can you post your config file?—

**Comment by Sn0wStorm** [comment]
There is no Espresso in the default config, so the admin of the server may have created it. Please ask them how to brew it.
