### ISSUE TITLE
A few things:

### ISSUE THREAD

**Issue by LegendaryAdmin** [DieReicheErethons/Brewery#72]
1. Whenever some one logs out from the game, or enters our mini game (battle arena) the soul sand becomes a real item and they can pick it up. 

2. Sugar cannot be added to cauldrons

Running on Spigot 1.8
Brewery 1.3.1

**Comment by Sn0wStorm** [comment]
1. If a player leaves the server, everyone can pick up the soulsand? or just the player that left?

2. Sugar can be added to cauldrons. Make sure to add it to the cooked section!

**Comment by LegendaryAdmin** [comment]
Everyone can pick up the soulsand.

As for the sugar....I should have noticed that >.< thanks!

**Comment by Mareron** [comment]
I get the same Problem on my Server.
Player pukes, player relogs, player can pick up soul sand.
