### ISSUE TITLE
Command blocks with "/brew create..."

### ISSUE THREAD

**Issue by Exagerate** [DieReicheErethons/Brewery#73]
I would love to have an auto unlimited bar where players could click a button to spawn a brew via a command block.

Currently my setup for the commandblock is "sudo @p brew create mojito 10" and the player is given a "you don't have permission to use this command" error. Obviously we don't want to give every player the command to create brews.

My suggestion is to add an extra part to the /brew create (which is a great add by the way) which lets you define which player to give it to. e.g. /brew create mojito 10 [playername]

Thanks for your time!

**Comment by Sn0wStorm** [comment]
That would be a good idea!

**Comment by Sn0wStorm** [comment]
Implemented, command is now /brew create <Recipe> [Quality] [Player] 
Quality and Player being optional
