### ISSUE TITLE
Barrels not working?

### ISSUE THREAD

**Issue by Pulverizer** [DieReicheErethons/Brewery#74]
I've tried creating barrels but it just won't work.
I'm running some Spigot 1.8 version, not sure which, and Brewery 1.3.1 and nothing else.

**Comment by Sn0wStorm** [comment]
It should work fine... Try a small barrel!

**Comment by Pulverizer** [comment]
Honestly, I have tried! It doesn't.

**Comment by Pulverizer** [comment]
I'll upload my server set-up soon.

**Comment by Pulverizer** [comment]
Here's a zip of my server set-up.
I had set myself as op to test your plugin.
https://drive.google.com/file/d/0B3mkhN_bOhvsRnNvT3M3QlFiN0k/view?usp=sharing

**Comment by Pulverizer** [comment]
@Sn0wStorm Worked it out yet?

**Comment by Deiscorides** [comment]
It doesn't like like there's a "Brewery" or "PluginMetrics" folder in your "plugins" folder. Maybe Spigot isn't setup/setting it up correctly? Do you see "[Brewery] Brewery Enabled!" in your server console?

**Comment by Pulverizer** [comment]
Yes, I have both of those...
And it does say it's enabled.

**Comment by weeryan17** [comment]
I'm having the same problem

**Comment by Kirrasio** [comment]
My barrel does not work with the latest grief prevention. It tells me to turn it off in console.
