### ISSUE TITLE
Login preventer cant be disabled

### ISSUE THREAD

**Issue by Mareron** [DieReicheErethons/Brewery#75]
I tried setting the configuration so that the Passing out (Kick on overdrink) is enabled but the Login prevention is disabled.
The result was that the Login prevention still kicked in after getting to 100% Drunkness.
Adding the permission to avoid the login prevention didnt help either.

An Idea that I had was to add a configurable Time, for how long you will be prevented from logging back in.

**Comment by Sn0wStorm** [comment]
The Problem was that you could drink over 100% drunkeness. Being over 100 the plugin would not let you join.

Overdrinking and thus being passed out for a while has been removed d5296bdc8c983aef259d419c322dd76fed52176e
