### ISSUE TITLE
Duplication Error

### ISSUE THREAD

**Issue by Gahshunk** [DieReicheErethons/Brewery#78]
Upon ~snip (Sn0wStorm)~ , I was able to take unlimited amounts of the brew into bottles. Even reconstructing it did not fix the error. Is this a doing of the plugin through a bug or can we safely say I'm an idiot. :P
Error log follows as is: http://pastebin.com/22Kviijb
Thanks in advance~

**Comment by Sn0wStorm** [comment]
Thank you so much for this report!  
I was able to reproduce this error and will get it fixed the next few days. Until it is fixed, i removed the details of your description, so that it cannot be abused!

Thanks also for the error log, i will be able to work on the plugin this weekend

**Comment by Gahshunk** [comment]
Thank you c:
