### ISSUE TITLE
Zutaten: Nur bestimmte Item-Namen

### ISSUE THREAD

**Issue by Malfrador** [DieReicheErethons/Brewery#79]
( Mal auf deutsch, ist einfacher ^^ )

Existiert die Möglichkeit bei den Zutaten nur Items mit bestimmten Namen zuzulassen? Wenn ja, wie?

~ Malf

**Comment by Sn0wStorm** [comment]
Die Möglichkeit gibt es im Moment nicht.  
Es wäre sicher möglich das einzubauen, aber wofür wäre das nützlich?

**Comment by Malfrador** [comment]
Naja, man kann z.B. "Gerste" und "Weizen" als umbenannte Items nutzen und daraus dann verschiedene Biere brauen, so in die Richtung würden wir das brauchen, hätte ja sein können das es möglich ist ;)

**Comment by Sn0wStorm** [comment]
Custom Items in v2.0 hinzugefügt
