### ISSUE TITLE
Remove recipes information from ended brews

### ISSUE THREAD

**Issue by tschaffter** [DieReicheErethons/Brewery#81]
Here is a screenshot of the label of an aging beer in a barrel:

![2015-04-22_10 31 03](https://cloud.githubusercontent.com/assets/3056480/7270239/fd3f5c30-e8da-11e4-96e6-13b38f489023.png)

and another one when the beer is removed from the barrel:

![2015-04-22_10 31 05](https://cloud.githubusercontent.com/assets/3056480/7270245/0b2df00e-e8db-11e4-9d60-c6992d26e395.png)

First of all, how does Brewery supports the case where a brew is removed from a barrel (the label of the brew changes) and then is placed again inside it after a random amount of time?

After aging or distilling a brew, the aging time and number of distillation cycles are visible on the label of the brew (fermentation time disappears). This can spoil players trying to infer the recipes if they got their hands on one of the brew from someone else. For example, another player found the recipes and is selling brews OR he gives one brew to other players so they can experience being drunk. What do you think?

**Comment by Sn0wStorm** [comment]
Brewery has a database for each and every potion made. It stores everything: ingredients, aging time, etc. When the potion is removed from a barrel, the information is no longer shown, but still there, so it will show again when put back into a barrel. Also from this information the quality, alc, effects, etc is calculated.

For the purpose of hiding these informations in a brews lore forever there is the command /brew unlabel
Its permission is defaulting to players i think. Am i missing something here?

**Comment by tschaffter** [comment]
So if I remove a brew from a barrel, wait some random time before placing back inside it, the aging process would resume?

The command */brew unlabel* removes the number of years aged in a barrel but keep the info that it has been aged. Well, I guess that for most of the recipes it's known from common knowledge (e.g. a whisky need to be aged). This command solves my issue. :)

> When the potion is removed from a barrel, the information is no longer shown, but still there, so it will show again when put back into a barrel. Also from this information the quality, alc, effects, etc is calculated.

This is interesting and seems related to [this issue](https://github.com/DieReicheErethons/Brewery/issues/80) I posted yesterday.
