### ISSUE TITLE
53 years barrel aged bier is still a Fine Beer

### ISSUE THREAD

**Issue by tschaffter** [DieReicheErethons/Brewery#83]
I followed the default beer recipe from the config file for testing purpose (ultimately I'd customize each recipes so that nobody could find the top quality recipes by looking at the config file on GitHub).

I did the fermentation according to the recipe and selected the correct wood type for the barrel. After 53 years of aging in the barrel, the brew is still considered as a top-quality "Fine Beer".

![2015-04-23_06 35 23](https://cloud.githubusercontent.com/assets/3056480/7290740/a1e6b810-e984-11e4-8ce5-aab7eacafaa5.png)

I'd expect the quality of the brew to decrease over time, with this time being proportional to the difficulty coefficient of this brewing.

**Comment by Sn0wStorm** [comment]
The quality does decrease when ageing too long. How much depends on the difficulty setting in the recipe. With a low difficulty the brew is much more forgiving.
As said earlier, the quality ranges from 1-10 while fine beer represents 7-10, so the quality may have already degraded.

**Comment by tschaffter** [comment]
Indeed, I was 0% drunk after drinking this beer. It's completely wrong to call this beer "Fine Beer" to me.

It seems that almost all the issues I posted are because the quality of the brew is not computed as I thought. I'll bring this discussion in a dedicated thread.
