### ISSUE TITLE
Can not sell/buy/exchange more than one brew using ShowCaseStandalone

### ISSUE THREAD

**Issue by tschaffter** [DieReicheErethons/Brewery#84]
[ShowCaseStandalone (SCS)](http://dev.bukkit.org/bukkit-plugins/scs/) is a great plugin to sell/buy/exchange items among players.

Here is what happens when a player tries to sell "Fine Beer" using SCS:
1. He creates a showcase using the "Fine Beer" in his hand: _/scs sell this 1 1_ (there is 1 beer in the showcase, 1 beer for $1).
2. He right-clicks on the showcase to open its inventory, places more "Fine Beers".
3. At the time he closes the showcase inventory, all additional beers disappear.

I believe this is due because Brewery gives a unique ID to each brew even if they come from the same batch of 3 brews (the three brews have the exact same information on their labels).

What about implementing a command _/brew finalize_ that would cast the brew currently in your hand to Skunky Beer/Beer/Fine Beer depending on the brew parameters. Then each Fine Beer, for example, would have the same ID and so they could be sold using a showcase.

**Comment by Sn0wStorm** [comment]
The actions when drinking depend on quality and other parameters. The quality ranges from 1-10, the three names only represent parts of the quality range, though "fine beer" could mean anything from quality 7-10. Also there may be different amount of alcohol independent from quality. So it makes sense to have those variables stored.

Each brew is supposed to be unique. This plugin was never designed to support selling in such manner. And while it would be possible, it would be far from easy to implement.
Much more possible would be certain plugin hooks to make them support brews with different ids.
