### ISSUE TITLE
Could not pass event InventoryCloseEvent to Brewery v1.3.2

### ISSUE THREAD

**Issue by Blackyvk** [DieReicheErethons/Brewery#86]
I get this error alot in console
http://hastebin.com/ibefufipoh.avrasm

**Comment by Sn0wStorm** [comment]
It seems to be caused by the Barrel not finding something in the LogBlock integration. Which version of LogBlock are you using?

**Comment by Blackyvk** [comment]
version: '1.94-dev-SNAPSHOT (build #256)'
