### ISSUE TITLE
"Indefinable" brew, always!

### ISSUE THREAD

**Issue by xHosoMx** [DieReicheErethons/Brewery#87]
I get an "Indefinable" brew every time i try to brew a custom potion! What's wrong?
I am following the configured steps, but nothing happens!

Here is my config:

... 

11:
      name: Poor Ossijoram/Ossijoram/Strong Ossijoram
      ingredients:
      - GLOWSTONE_DUST/5
      - GOLDEN_CARROT /5
      - SPECKLED_MELON/5
      cookingtime: 3
      distillruns: 3
      difficulty: 1
      age: 0
      alcohol: 0
      color: ORANGE
      effects:
      - SPEED/3-5/10-60
      - JUMP/1-3/10-60
      - FAST_DIGGING/3-5/10-60
      - HUNGERX/3-0/20-1
      - WEAKNESSX/3-0/20-1
      - CONFUSIONX/3-0/20-1

And in the "cooked" section:

cooked:
   WHEAT: Fermented wheat
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: Mushroom brew
   INK_SACK: Colored brew
   MILK_BUCKET: Milky water
   NETHER_STAR: Alchemized Nether Star
   DRAGON_EGG: Dragon Essence
   EYE_OF_ENDER: Ender Essence
   RABBIT_FOOT: Fermented rabbit foot
   CARROT: Fermented carrot
   GOLDEN_APPLE: Fermented golden apple
   SPIDER_EYE: Cooked spider eye
   BONE: Alchemic brew of Dissolved bones
   SKULL: Alchemic brew of Dissolved skull
   GOLDEN_CARROT: Fermented golden carrot
   SPECKLED_MELON: Fermented glistering melon
   NETHER_WARTS: Fermented nether warts
   MAGMA_CREAM: Boiled magma cream
   GHAST_TEAR: Dissolved ghast tear
   FERMENTED_SPIDER_EYE: Putrid spider eye brew
   REDSTONE: Redstone infuse
   GLOWSTONE_DUST: Glowstone infuse
   SUGAR: Sugar infuse
   SULPHUR: Sulphur infuse
   BLAZE_POWDER: Blaze infuse

**Comment by xHosoMx** [comment]
I forgot:
Runnung Bukkit 1.8 r0.1
And Brewery 1.3.1, latest
version for 1.8 server

**Comment by xHosoMx** [comment]
Solved!

**Comment by BeyonderCraft** [comment]
Hey I have the same problem but how did you fix your problem please reply soon working on my server so please reply.
