### ISSUE TITLE
Old Brews Not Working

### ISSUE THREAD

**Issue by DanHosaur** [DieReicheErethons/Brewery#90]
There was an issue and we deleted the config file and let the plugin make a new config file but everyone's brew before we deleted the old config file doesn't work anymore. It doesn't give effects at all.

**Comment by Deiscorides** [comment]
If you added recipes to the recipe list, you'll need to re-add them. If the order of the number of the brew recipes is rearranged, the brews won't work. They need to keep the exact numbering. Always keep backups of your config.yml file, even if it is just for reference.
