### ISSUE TITLE
Lore Text and Chat Text

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#91]
It would be nice to have an option to add Lore text description to a recipe for when you mouse over the brew item in your inventory. For the Chat text, when a player drinks the brew, the text is posted in chat for them to see. The text can be specific to the level of quality, using / to divide them. Here's an example:

   1:
      name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
      loretext: The brew smells like it has been left in the sun too long./This looks like a good beer./The brew beckons you to drink it.
      chattext: This wheatbeer smells skunky and tastes awful./This wheatbeer tastes good./This is the most delicious wheatbeer you've ever had! You need another.
      ingredients: 
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 3
      alcohol: 5

**Comment by Kbryst** [comment]
Just replying to this because I would LOVE to see it as well.

**Comment by Sn0wStorm** [comment]
Implemented in v2.0
