### ISSUE TITLE
Duplicate Numbered Recipes don't give console errors

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#92]
I recently discovered that if 2 recipes are numbered the same, the plugin will load fine without errors. There should probably be an error listed for this kind of thing in the console during startup.

**Comment by Sn0wStorm** [comment]
There is no way for the Plugin to know if there are duplicate numbers. It is loaded by the yaml implementation and then iterated over by the plugin. If there are duplicates they are probably simply skipped.
