### ISSUE TITLE
No console error for bottle color spelling errors

### ISSUE THREAD

**Issue by Deiscorides** [DieReicheErethons/Brewery#93]
I found out that if "color: GRAY" is used instead of "color: GREY" the recipe will cause the cauldron to be rendered unusable when you try to take the brew from it. Even if you break the cauldron and replace it, it will still be unusable. It causes the cauldron to continue "seething". Once the spelling error was corrected the recipe was completely fixed.

**Comment by Sn0wStorm** [comment]
Fixed in d5296bdc8c983aef259d419c322dd76fed52176e
