### ISSUE TITLE
Rezeptzutaten - Namen, Zahlen... ?

### ISSUE THREAD

**Issue by Rejeus** [DieReicheErethons/Brewery#98]
Hi!

Erstmal cooles Plugin! :)

Dann eine Frage...

Einige Objekte/Produkte haben in Minecraft den gleichen Bezeichnungsnamen (Block-Namen) und werden nur durch die ID unterschieden. Wenn ich in den Rezepten zb rote Farbe (Rose red) einbinden will, ist es laut Minecraft ja entweder Dye (was leider für eine Menge andere Farben usw steht) und/oder 351:1.

Muss ich da im Rezept nun 351:1 oder 351,1 oder DYE eintragen? Oder langt es wenn ich "Rose Red" eintrage? Und muss ich das genauso bei cooked eintragen oder da wieder die andere Bezeichnung? Weil zum Beispiel Cocoa Beans haben ebenfalls DYE als Bezeichnung/Datenwert.

Ich habe theoretisch schon einiges ausprobiert. Weiß aber nun nicht ob ich etwas falsch gemacht habe oder ob ich etwas übersehen habe. Oder geht dies gar nicht mit diesen Objekten?

Grüße
Ben

**Comment by Feuerstern** [comment]
Hi,
der Code ist mir zwar nicht wirklich geläufig, aber wenn ich es richtig erkenne, solltest Du einfach ID:Schadenswert benutzen können.
~LG

**Comment by NghtShad** [comment]
I used Google translate so I may be wrong but it sounds like you are wondering what to use for certain items that are dye type items. This is what I used in mine. 
Rose Bush = 174,5
Rose Red Dye = 351,1
Cocoa Beans = 351,3

So in ingredients I would have - 351,3/4 if I wanted to add 4 cocoa beans.

**Comment by Rejeus** [comment]
Thx :)

**Comment by Rejeus** [comment]
Mit 351,3 und auch mit anderen Zahlen, funktioniert es leider nicht.

with 351,3 etc. it do not works. :/

**Comment by NghtShad** [comment]
Here is a sample of one of my recipes that works with cocoa beans.

   71:
      name: Stale Black Coffee/Black Coffee/&6Strong Black Coffee
      ingredients:
      - 351,3/3
      - 351/1
      cookingtime: 4
      distillruns: 0
      age: 0
      color: BLACK
      difficulty: 2
      effects:
      - REGENERATIONX/0-3/2-35
      - SPEEDX/0-3/30-140
      - JUMPX/3/20-35

It is cocoa and ink sac. I also made sure that cocoa is listed under

cooked:
   351,3: Dark brew

That is what works for me.
