### ISSUE TITLE
Puffer Fish

### ISSUE THREAD

**Issue by NghtShad** [DieReicheErethons/Brewery#99]
I am having troubles making puffer fish work as an ingredient option. Every other item I have used so far has worked by either using the material name from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html 
or the itemID from http://www.minecraftinfo.com/IDList.htm. 

The exception to all of this so far as been Puffer fish. I have tried FISH,3 , RAW_FISH,3 , 349,3 and also PUFFERFISH or PUFFER_FISH but in all cases it has not worked. Has anyone else been able to use pufferfish as an ingredient? If so what did you use to get it to work?

**Comment by NghtShad** [comment]
Any assistance with figuring out what to use for Puffer Fish would be great. I have now found an issue with just Raw Fish and White Wool

**Comment by xXTrixieXx** [comment]
Did you try adding the ingredient to the "cooked" section as well? EX: Wheat turns to Fermented Wheat

**Comment by NghtShad** [comment]
I had tried that with no success. As it turns out Bukkit does not see any difference between Raw fish, Puffer Fish, Salmon or any other of the raw fish types. They are all just RAW_FISH. This means that any of them can be used in a recipe but it is the only way to get Puffer fish to work as an ingredient.

**Comment by xXTrixieXx** [comment]
name: Wizards Timebomb
      ingredients:
      - SUGAR_CANE/5
      - red_flower 1/1
      - red_flower 2/2
      - nether_wart/8
      - fish 3/1
      - GHAST_TEAR/3
      cookingtime: 3
      distillruns: 2
      wood: 4
      age: 11
      color: DARK_RED
      difficulty: 3
      alcohol: 23
      effects:
      - FIRE_RESISTANCE/20
      - HEAL/1
      - WEAKNESS/2-3/50-60
      - POISONX/1-0/20-0



Thats my config for using my puffer fish:) i had to put the 3 because its item number

**Comment by NghtShad** [comment]
would'nt it be fish,3? same with your Red_flower. Thought red_flower,1 or red_flower,2 was the proper formatting.
